import { VOCAB_CAT_MAP } from "../src/constants.js";
import { STATIC_VOCAB } from "../src/static_vocab.js";
import { DE_STATIC_VOCAB } from "../src/de_static_vocab.js";
import { writeFileSync } from "fs";

const bulk = (cat, words) => Object.fromEntries(words.map((w) => [w, cat]));
const SUPP = {
  ...bulk("Tallord og mengde", ["zéro", "onze", "douze", "treize", "quinze", "seize", "dix-sept", "dix-huit", "dix-neuf", "trente", "quarante", "cinquante", "soixante", "soixante-dix", "quatre-vingts", "quatre-vingt-dix", "deuxième", "troisième", "quatrième", "cinquième", "sixième", "septième", "huitième", "neuvième"]),
  ...bulk("Tid og frekvens", ["midi", "après-midi", "Il est quelle heure ?", "Il est midi", "Il est minuit"]),
  ...bulk("Utdanning og arbeid", ["policier", "pompier", "serveur", "serveuse"]),
  ...bulk("Hilsener og høflighet", ["monsieur", "madame", "Bonjour !", "Salut !", "Comment allez-vous ?", "Comment ça va ?", "Ça va bien", "Enchanté(e)", "À bientôt", "À tout à l'heure", "Allô", "Je vous appelle de la part de", "Pouvez-vous rappeler ?", "Ne quittez pas"]),
  ...bulk("Natur og vær", ["étoile", "terre", "Il fait beau", "Il pleut", "Il neige", "Il fait chaud", "Il fait froid", "Il y a du vent", "température", "parapluie"]),
  ...bulk("Adjektiver", ["heureux", "malheureux", "tranquille", "sympa", "gentil", "méchant", "poli", "intelligent", "sage", "fou", "occupé", "ouvert", "fermé", "impossible", "nécessaire", "utile", "inutile", "agréable", "sérieux", "parfait", "proche", "lointain", "dur", "interdit", "obligatoire"]),
  ...bulk("Adverb og bindeord", ["avec", "sans", "pour", "contre", "parmi", "malgré", "grâce à", "à cause de", "vers", "dès", "avant", "après", "ni", "lorsque", "ainsi", "quelquefois", "autrefois", "tellement", "exactement", "heureusement", "malheureusement", "facilement", "à gauche", "à droite", "tout droit", "près de", "loin de", "à côté de", "en face de", "au coin de"]),
  ...bulk("Vanlige verb", ["préférer", "rêver", "se dépêcher", "déranger", "s'ennuyer", "composter", "réserver", "envoyer", "brancher", "débrancher", "emménager", "déménager", "charger le téléphone", "continuer jusqu'à"]),
  ...bulk("Kommunikasjon og tanker", ["je ne sais pas", "je ne comprends pas", "pouvez-vous répéter", "il y a", "allons-y", "attention", "c'est vrai", "pas du tout", "tout à fait", "n'importe", "chose", "façon", "raison", "chance", "Au secours !", "J'ai besoin d'aide"]),
  ...bulk("Mat og drikke", ["commander", "commande", "pourboire", "une table pour deux", "je voudrais", "plat principal", "un verre de", "une bouteille de", "sans gluten", "végétarien", "c'est délicieux"]),
  ...bulk("Shopping og tjenester", ["pointure", "rayon", "caisse", "ticket de caisse", "réduction", "connexion Wi-Fi", "code", "application"]),
  ...bulk("Transport og reiser", ["en retard", "à l'heure", "station", "tramway", "prendre le bus", "carrefour", "vol", "aller simple", "salle d'attente", "office de tourisme", "carte postale", "timbre"]),
  ...bulk("Hjem og hverdagsliv", ["se réveiller", "se doucher", "s'habiller", "se brosser les dents", "rentrer à la maison", "faire la cuisine", "faire les courses", "toilettes", "ascenseur", "poubelle", "courrier", "boîte aux lettres", "robinet", "douche", "chauffage", "électricité"]),
  ...bulk("Steder og rom", ["centre-ville"]),
  ...bulk("Samfunn og politikk", ["police"]),
  ...bulk("Kropp og helse", ["urgence"]),
};

const frCat = (fr) => VOCAB_CAT_MAP[fr] || SUPP[fr] || null;

const frByNo = {};
for (const k of ["core", "everyday", "tdf"]) for (const e of STATIC_VOCAB[k]) if (!(e.no in frByNo)) frByNo[e.no] = e.fr;

let tdfFallback = 0, covered = 0;
const missing = [];
const out = {};
for (const k of ["core", "everyday", "tdf"]) {
  for (const e of DE_STATIC_VOCAB[k]) {
    const frWord = frByNo[e.no];
    let cat = frWord ? frCat(frWord) : null;
    if (!cat && k === "tdf") { cat = "Tour de France"; tdfFallback++; }
    if (cat) { out[e.fr] = cat; covered++; }
    else missing.push(`${e.fr} (${e.no})`);
  }
}

const body = Object.entries(out).map(([w, c]) => `  "${w.replace(/"/g, '\\"')}": "${c}",`).join("\n");
const file = `// Swiss-German word → Norwegian category (mirrors VOCAB_CAT_ORDER) so the
// German Ordbanken groups words like the French one. Generated by
// scripts/regen_de_cat.mjs: joins DE_STATIC_VOCAB to the French STATIC_VOCAB on
// the shared Norwegian gloss and reuses VOCAB_CAT_MAP, plus a supplement for
// words French leaves uncategorised (all remaining Tour-de-France terms bucket
// to "Tour de France"). Swiss spelling only — always "ss".
export const DE_VOCAB_CAT_MAP = {
${body}
};
`;
writeFileSync("/Users/peterhegg/Documents/Jobb/Apper/Språkappen/src/de_vocab_cat_map.js", file);
console.log("German entries categorised:", covered, "/ 802");
console.log("TDF fallback used:", tdfFallback);
console.log("still missing:", missing.length);
if (missing.length) console.log(missing.join(" | "));
