export const PROXY_URL = import.meta.env.VITE_PROXY_URL;
export const APP_TOKEN = import.meta.env.VITE_APP_TOKEN;

export const SYSTEM_PROMPT = `Du er en tålmodig fransktutor for en norsk nybegynner (A1/A2) med dysleksi. Eleven har to bøker: en roman av Houellebecq og en bok om kulturlivet i Paris på 1920-tallet.

KOMMUNIKASJON:
- Norsk som hovedspråk — innfør gradvis mer fransk i takt med elevens fremgang
- Aldri mer fransk enn eleven mestrer
- Forklar grammatikk gjennom eksempler, aldri lange regelforklaringer
- Korte avsnitt og tydelig struktur
- Kort, oppmuntrende tilbakemelding — ikke overdrevet

UTTALE:
- Skriv alltid fonetisk uttale på norsk i parentes etter nye ord: bonjour (bånsjur)
- Minn jevnlig eleven på å si ordene høyt

PROGRESJON:
- Bygg alltid videre på det eleven kan fra før
- Bruk ord og temaer fra Houellebecq og Paris på 1920-tallet aktivt

TEKSTHJELP: Eleven limer inn tekst på fransk. Bruk skjønn: én setning/par ord → bryt ned ord for ord. Lengre tekst → norsk sammendrag (2-3 setninger), oversett avsnitt for avsnitt, plukk ut 2-3 grammatiske mønstre. Avslutt med FORSLAG: [svar1] | [svar2] | [svar3].
FRI: Svar fritt på spørsmål om fransk. Kan spille franskmannen Pierre hvis eleven vil — start på norsk og innfør gradvis mer fransk, bruk *kursiv* for handlinger. Avslutt gjerne med FORSLAG: [svar1] | [svar2] | [svar3].`;

export const BOOK_EXCERPTS = [
  { book: "Houellebecq", hint: "Om en enkel dag", text: "Il faisait beau, le ciel était bleu." },
  { book: "Houellebecq", hint: "En filosofisk observasjon", text: "La vie est simple quand on ne pense pas trop." },
  { book: "Paris 1920", hint: "Kunstnernes møtesteder", text: "Les artistes se retrouvaient dans les cafés de Montparnasse." },
  { book: "Paris 1920", hint: "Paris som kunstnerby", text: "Paris était la capitale du monde de l'art dans les années vingt." },
  { book: "Paris 1920", hint: "Jazzens ankomst", text: "Le jazz américain est arrivé à Paris après la guerre." },
];

export const VOCAB_LIST = [
  // Hilsener
  { fr: "bonjour", no: "hallo / god dag", phonetic: "bånsjur" },
  { fr: "bonsoir", no: "god kveld", phonetic: "bånswår" },
  { fr: "au revoir", no: "ha det bra", phonetic: "o rəvwår" },
  { fr: "merci", no: "takk", phonetic: "merssi" },
  { fr: "s'il vous plaît", no: "vær så snill", phonetic: "sil vu plæ" },
  { fr: "oui", no: "ja", phonetic: "wi" },
  { fr: "non", no: "nei", phonetic: "nån" },
  { fr: "pardon", no: "unnskyld", phonetic: "pardån" },
  { fr: "de rien", no: "ingen årsak", phonetic: "də rjæn" },
  // Pronomen
  { fr: "je", no: "jeg", phonetic: "sjø" },
  { fr: "tu", no: "du", phonetic: "ty" },
  { fr: "il", no: "han", phonetic: "il" },
  { fr: "elle", no: "hun", phonetic: "æl" },
  { fr: "nous", no: "vi", phonetic: "nu" },
  { fr: "vous", no: "dere / De", phonetic: "vu" },
  // Vanlige verb
  { fr: "être", no: "å være", phonetic: "ætr" },
  { fr: "avoir", no: "å ha", phonetic: "avwår" },
  { fr: "aller", no: "å gå / dra", phonetic: "alæ" },
  { fr: "venir", no: "å komme", phonetic: "vənir" },
  { fr: "voir", no: "å se", phonetic: "vwår" },
  { fr: "parler", no: "å snakke", phonetic: "parlæ" },
  { fr: "manger", no: "å spise", phonetic: "månsjæ" },
  { fr: "boire", no: "å drikke", phonetic: "bwår" },
  { fr: "lire", no: "å lese", phonetic: "lir" },
  { fr: "écrire", no: "å skrive", phonetic: "ekrir" },
  { fr: "aimer", no: "å like / elske", phonetic: "emæ" },
  { fr: "savoir", no: "å vite", phonetic: "savwår" },
  { fr: "faire", no: "å gjøre / lage", phonetic: "fær" },
  { fr: "habiter", no: "å bo", phonetic: "abitæ" },
  // Steder – Paris
  { fr: "Paris", no: "Paris", phonetic: "pari" },
  { fr: "café", no: "kafé", phonetic: "kafæ" },
  { fr: "rue", no: "gate", phonetic: "ry" },
  { fr: "ville", no: "by", phonetic: "vil" },
  { fr: "quartier", no: "bydel / nabolag", phonetic: "kartjæ" },
  { fr: "musée", no: "museum", phonetic: "myzæ" },
  { fr: "gare", no: "togstasjon", phonetic: "går" },
  { fr: "hôtel", no: "hotell", phonetic: "otæl" },
  { fr: "restaurant", no: "restaurant", phonetic: "rEstorån" },
  { fr: "bibliothèque", no: "bibliotek", phonetic: "biblijotæk" },
  { fr: "Seine", no: "Seinen (elven)", phonetic: "sæn" },
  // Tid
  { fr: "aujourd'hui", no: "i dag", phonetic: "osjurdwi" },
  { fr: "demain", no: "i morgen", phonetic: "dəmæn" },
  { fr: "hier", no: "i går", phonetic: "jær" },
  { fr: "maintenant", no: "nå", phonetic: "mæntnå" },
  { fr: "toujours", no: "alltid", phonetic: "tusjur" },
  { fr: "jamais", no: "aldri", phonetic: "sjamæ" },
  { fr: "souvent", no: "ofte", phonetic: "suvån" },
  // Adjektiver
  { fr: "beau / belle", no: "vakker", phonetic: "bo / bæl" },
  { fr: "grand / grande", no: "stor", phonetic: "grå / grågd" },
  { fr: "petit / petite", no: "liten", phonetic: "pəti / pətit" },
  { fr: "bon / bonne", no: "god / bra", phonetic: "bån / bOn" },
  { fr: "nouveau / nouvelle", no: "ny", phonetic: "nuvo / nuvæl" },
  { fr: "vieux / vieille", no: "gammel", phonetic: "vjø / vjæj" },
  { fr: "simple", no: "enkel", phonetic: "sæmpl" },
  // Kunst og kultur
  { fr: "artiste", no: "kunstner", phonetic: "artist" },
  { fr: "peintre", no: "maler", phonetic: "pæntr" },
  { fr: "écrivain", no: "forfatter", phonetic: "ekriven" },
  { fr: "roman", no: "roman", phonetic: "romån" },
  { fr: "livre", no: "bok", phonetic: "livr" },
  { fr: "tableau", no: "maleri", phonetic: "tablo" },
  { fr: "jazz", no: "jazz", phonetic: "dsjaz" },
  { fr: "musique", no: "musikk", phonetic: "myzik" },
  { fr: "guerre", no: "krig", phonetic: "gær" },
  { fr: "étranger", no: "utlending / fremmed", phonetic: "etrånsjæ" },
  { fr: "époque", no: "epoke / tid", phonetic: "epok" },
  // Mat og drikke
  { fr: "pain", no: "brød", phonetic: "pæn" },
  { fr: "vin", no: "vin", phonetic: "væn" },
  { fr: "eau", no: "vann", phonetic: "o" },
  { fr: "fromage", no: "ost", phonetic: "fromåsj" },
  { fr: "bière", no: "øl", phonetic: "bjær" },
  // Verden og natur
  { fr: "soleil", no: "sol", phonetic: "solæj" },
  { fr: "ciel", no: "himmel / sky", phonetic: "sjæl" },
  { fr: "vie", no: "liv", phonetic: "vi" },
  { fr: "monde", no: "verden", phonetic: "månd" },
  { fr: "homme", no: "mann / menneske", phonetic: "Om" },
  { fr: "femme", no: "kvinne", phonetic: "fam" },
  { fr: "ami / amie", no: "venn / venninne", phonetic: "ami" },
  { fr: "temps", no: "tid / vær", phonetic: "tå" },
  { fr: "année", no: "år", phonetic: "anæ" },
];

export const VOCAB_CAT_ORDER = [
  "Hilsener og høflighet",
  "Pronomen",
  "Tallord og mengde",
  "Vanlige verb",
  "Bevegelse",
  "Kommunikasjon og tanker",
  "Følelser og identitet",
  "Adjektiver",
  "Adverb og bindeord",
  "Tid og frekvens",
  "Steder – Paris",
  "Steder og rom",
  "Familie og relasjoner",
  "Kropp og helse",
  "Klær og utseende",
  "Mat og drikke",
  "Hjem og hverdagsliv",
  "Shopping og tjenester",
  "Transport og reiser",
  "Natur og vær",
  "Dyr",
  "Land og geografi",
  "Kunst og kultur",
  "Sport og fritid",
  "Tour de France",
  "Utdanning og arbeid",
  "Samfunn og politikk",
  "Andre ord",
];


import { STATIC_VOCAB } from "./static_vocab.js";
export { STATIC_VOCAB };

export const VOCAB_CAT_MAP = {
  // ── Hilsener og høflighet ─────────────────────────────────────────────────
  "bonjour": "Hilsener og høflighet", "bonsoir": "Hilsener og høflighet",
  "bonne nuit": "Hilsener og høflighet", "au revoir": "Hilsener og høflighet",
  "à bientôt": "Hilsener og høflighet", "salut": "Hilsener og høflighet",
  "merci": "Hilsener og høflighet", "merci beaucoup": "Hilsener og høflighet",
  "s'il vous plaît": "Hilsener og høflighet", "s'il te plaît": "Hilsener og høflighet",
  "oui": "Hilsener og høflighet", "non": "Hilsener og høflighet",
  "pardon": "Hilsener og høflighet", "excusez-moi": "Hilsener og høflighet",
  "de rien": "Hilsener og høflighet", "je vous en prie": "Hilsener og høflighet",
  "enchanté": "Hilsener og høflighet", "comment allez-vous": "Hilsener og høflighet",
  "ça va": "Hilsener og høflighet", "bienvenue": "Hilsener og høflighet",
  "félicitations": "Hilsener og høflighet", "bonne chance": "Hilsener og høflighet",
  "d'accord": "Hilsener og høflighet", "bien sûr": "Hilsener og høflighet",
  "voilà": "Hilsener og høflighet",

  // ── Pronomen ──────────────────────────────────────────────────────────────
  "je": "Pronomen", "tu": "Pronomen", "il": "Pronomen", "elle": "Pronomen",
  "nous": "Pronomen", "vous": "Pronomen", "ils": "Pronomen", "elles": "Pronomen",
  "on": "Pronomen", "me": "Pronomen", "te": "Pronomen", "se": "Pronomen",
  "lui": "Pronomen", "leur": "Pronomen", "moi": "Pronomen", "toi": "Pronomen",
  "soi": "Pronomen", "eux": "Pronomen", "ce": "Pronomen", "cela": "Pronomen",
  "ça": "Pronomen", "ceci": "Pronomen", "qui": "Pronomen", "que": "Pronomen",
  "quoi": "Pronomen", "dont": "Pronomen", "où": "Pronomen",
  "quelqu'un": "Pronomen", "quelque chose": "Pronomen", "tout le monde": "Pronomen",
  "personne": "Pronomen", "rien": "Pronomen", "chacun": "Pronomen",

  // ── Tallord og mengde ─────────────────────────────────────────────────────
  "un": "Tallord og mengde", "deux": "Tallord og mengde", "trois": "Tallord og mengde",
  "quatre": "Tallord og mengde", "cinq": "Tallord og mengde", "six": "Tallord og mengde",
  "sept": "Tallord og mengde", "huit": "Tallord og mengde", "neuf": "Tallord og mengde",
  "dix": "Tallord og mengde", "vingt": "Tallord og mengde", "cent": "Tallord og mengde",
  "mille": "Tallord og mengde", "premier": "Tallord og mengde", "dernier": "Tallord og mengde",
  "beaucoup": "Tallord og mengde", "peu": "Tallord og mengde", "assez": "Tallord og mengde",
  "trop": "Tallord og mengde", "plus": "Tallord og mengde", "moins": "Tallord og mengde",
  "combien": "Tallord og mengde", "plusieurs": "Tallord og mengde",
  "quelques": "Tallord og mengde", "chaque": "Tallord og mengde",
  "tout": "Tallord og mengde", "tous": "Tallord og mengde", "toute": "Tallord og mengde",
  "nombre": "Tallord og mengde", "moitié": "Tallord og mengde",
  "ensemble": "Tallord og mengde", "environ": "Tallord og mengde",

  // ── Vanlige verb ──────────────────────────────────────────────────────────
  "être": "Vanlige verb", "avoir": "Vanlige verb", "faire": "Vanlige verb",
  "aller": "Vanlige verb", "venir": "Vanlige verb", "voir": "Vanlige verb",
  "savoir": "Vanlige verb", "pouvoir": "Vanlige verb", "vouloir": "Vanlige verb",
  "devoir": "Vanlige verb", "falloir": "Vanlige verb", "valoir": "Vanlige verb",
  "mettre": "Vanlige verb", "prendre": "Vanlige verb", "donner": "Vanlige verb",
  "aimer": "Vanlige verb", "vouloir dire": "Vanlige verb",
  "sembler": "Kommunikasjon og tanker", "paraître": "Kommunikasjon og tanker", "devenir": "Vanlige verb",
  "tenir": "Vanlige verb", "rendre": "Vanlige verb", "laisser": "Vanlige verb",
  "permettre": "Vanlige verb", "garder": "Vanlige verb", "perdre": "Vanlige verb",
  "gagner": "Vanlige verb", "utiliser": "Vanlige verb", "changer": "Vanlige verb",
  "finir": "Vanlige verb", "commencer": "Vanlige verb", "essayer": "Vanlige verb",
  "continuer": "Vanlige verb", "aider": "Vanlige verb", "ouvrir": "Vanlige verb",
  "fermer": "Vanlige verb", "rappeler": "Vanlige verb", "appeler": "Vanlige verb",
  "suivre": "Vanlige verb", "montrer": "Vanlige verb", "compter": "Vanlige verb",
  "décider": "Vanlige verb", "choisir": "Vanlige verb", "créer": "Vanlige verb",
  "vivre": "Vanlige verb", "mourir": "Vanlige verb", "naître": "Vanlige verb",
  "habiter": "Vanlige verb",

  // ── Bevegelse ─────────────────────────────────────────────────────────────
  "partir": "Bevegelse", "arriver": "Bevegelse", "rentrer": "Bevegelse",
  "retourner": "Bevegelse", "revenir": "Bevegelse", "sortir": "Bevegelse",
  "entrer": "Bevegelse", "monter": "Bevegelse", "descendre": "Bevegelse",
  "marcher": "Bevegelse", "courir": "Bevegelse", "tomber": "Bevegelse",
  "passer": "Bevegelse", "traverser": "Bevegelse", "rester": "Bevegelse",
  "voyager": "Bevegelse", "avancer": "Bevegelse", "reculer": "Bevegelse",
  "tourner": "Bevegelse", "s'approcher": "Bevegelse", "s'éloigner": "Bevegelse",
  "rejoindre": "Bevegelse", "longer": "Bevegelse", "contourner": "Bevegelse",
  "se situer": "Bevegelse", "s'étendre": "Bevegelse", "border": "Bevegelse",
  "surplomber": "Bevegelse", "relier": "Bevegelse", "séparer": "Bevegelse",

  // ── Kommunikasjon og tanker ───────────────────────────────────────────────
  "parler": "Kommunikasjon og tanker", "dire": "Kommunikasjon og tanker",
  "demander": "Kommunikasjon og tanker", "répondre": "Kommunikasjon og tanker",
  "écrire": "Kommunikasjon og tanker", "lire": "Kommunikasjon og tanker",
  "écouter": "Kommunikasjon og tanker", "entendre": "Kommunikasjon og tanker",
  "comprendre": "Kommunikasjon og tanker", "expliquer": "Kommunikasjon og tanker",
  "connaître": "Kommunikasjon og tanker", "penser": "Kommunikasjon og tanker",
  "croire": "Kommunikasjon og tanker", "savoir": "Kommunikasjon og tanker",
  "oublier": "Kommunikasjon og tanker", "se souvenir": "Kommunikasjon og tanker",
  "remarquer": "Kommunikasjon og tanker", "apprendre": "Kommunikasjon og tanker",
  "enseigner": "Kommunikasjon og tanker", "étudier": "Kommunikasjon og tanker",
  "chercher": "Kommunikasjon og tanker", "trouver": "Kommunikasjon og tanker",
  "raconter": "Kommunikasjon og tanker", "annoncer": "Kommunikasjon og tanker",
  "publier": "Kommunikasjon og tanker", "attendre": "Kommunikasjon og tanker",
  "imaginer": "Kommunikasjon og tanker", "réfléchir": "Kommunikasjon og tanker",
  "décider": "Kommunikasjon og tanker", "choisir": "Kommunikasjon og tanker",
  "question": "Kommunikasjon og tanker", "réponse": "Kommunikasjon og tanker",
  "mot": "Kommunikasjon og tanker", "phrase": "Kommunikasjon og tanker",
  "langue": "Kommunikasjon og tanker", "texte": "Kommunikasjon og tanker",
  "message": "Kommunikasjon og tanker", "lettre": "Kommunikasjon og tanker",
  "appel": "Kommunikasjon og tanker", "nouvelles": "Kommunikasjon og tanker",

  // ── Følelser og identitet ─────────────────────────────────────────────────
  "sentir": "Følelser og identitet", "ressentir": "Følelser og identitet",
  "aimer": "Følelser og identitet", "détester": "Følelser og identitet",
  "apprécier": "Følelser og identitet", "admirer": "Følelser og identitet",
  "respecter": "Følelser og identitet", "craindre": "Følelser og identitet",
  "espérer": "Følelser og identitet", "regretter": "Følelser og identitet",
  "sourire": "Følelser og identitet", "pleurer": "Følelser og identitet",
  "rire": "Følelser og identitet", "souffrir": "Følelser og identitet",
  "amour": "Følelser og identitet", "bonheur": "Følelser og identitet",
  "tristesse": "Følelser og identitet", "peur": "Følelser og identitet",
  "joie": "Følelser og identitet", "colère": "Følelser og identitet",
  "surprise": "Følelser og identitet", "confiance": "Følelser og identitet",
  "honte": "Følelser og identitet", "fierté": "Følelser og identitet",
  "calme": "Følelser og identitet", "stress": "Følelser og identitet",
  "liberté": "Følelser og identitet", "rêve": "Følelser og identitet",
  "désir": "Følelser og identitet", "besoin": "Følelser og identitet",
  "caractère": "Følelser og identitet", "personnalité": "Følelser og identitet",
  "humeur": "Følelser og identitet", "sentiment": "Følelser og identitet",

  // ── Adjektiver ────────────────────────────────────────────────────────────
  "grand": "Adjektiver", "grand / grande": "Adjektiver",
  "petit": "Adjektiver", "petit / petite": "Adjektiver",
  "bon": "Adjektiver", "bon / bonne": "Adjektiver",
  "mauvais": "Adjektiver", "beau": "Adjektiver", "beau / belle": "Adjektiver",
  "nouveau": "Adjektiver", "nouveau / nouvelle": "Adjektiver",
  "vieux": "Adjektiver", "vieux / vieille": "Adjektiver",
  "jeune": "Adjektiver", "fort": "Adjektiver", "faible": "Adjektiver",
  "lent": "Adjektiver", "rapide": "Adjektiver",
  "facile": "Adjektiver", "difficile": "Adjektiver",
  "intéressant": "Adjektiver", "ennuyeux": "Adjektiver",
  "content": "Adjektiver", "triste": "Adjektiver", "fatigué": "Adjektiver",
  "malade": "Adjektiver", "propre": "Adjektiver", "sale": "Adjektiver",
  "plein": "Adjektiver", "vide": "Adjektiver", "seul": "Adjektiver",
  "vrai": "Adjektiver", "faux": "Adjektiver", "simple": "Adjektiver",
  "autre": "Adjektiver", "même": "Adjektiver", "haut": "Adjektiver",
  "bas": "Adjektiver", "long": "Adjektiver", "court": "Adjektiver",
  "large": "Adjektiver", "étroit": "Adjektiver", "lourd": "Adjektiver",
  "léger": "Adjektiver", "chaud": "Adjektiver", "froid": "Adjektiver",
  "important": "Adjektiver", "possible": "Adjektiver", "libre": "Adjektiver",
  "dernier": "Adjektiver", "prochain": "Adjektiver", "certain": "Adjektiver",
  "différent": "Adjektiver", "même": "Adjektiver", "pareil": "Adjektiver",
  "principal": "Adjektiver", "général": "Adjektiver", "spécial": "Adjektiver",
  "rouge": "Adjektiver", "bleu": "Adjektiver", "vert": "Adjektiver",
  "jaune": "Adjektiver", "blanc": "Adjektiver", "noir": "Adjektiver",
  "gris": "Adjektiver", "marron": "Adjektiver", "rose": "Adjektiver",
  "orange": "Adjektiver", "violet": "Adjektiver", "beige": "Adjektiver",
  "ensoleillé": "Adjektiver", "nuageux": "Adjektiver", "pluvieux": "Adjektiver",
  "venteux": "Adjektiver", "orageux": "Adjektiver", "neigeux": "Adjektiver",
  "brumeux": "Adjektiver", "torride": "Adjektiver",
  "nordique": "Adjektiver", "méditerranéen": "Adjektiver",
  "atlantique": "Adjektiver", "continental": "Adjektiver",
  "tropical": "Adjektiver", "subtropical": "Adjektiver",
  "polaire": "Adjektiver", "tempéré": "Adjektiver", "aride": "Adjektiver",
  "montagneux": "Adjektiver", "côtier": "Adjektiver", "insulaire": "Adjektiver",
  "fluvial": "Adjektiver", "maritime": "Adjektiver", "volcanique": "Adjektiver",
  "glaciaire": "Adjektiver", "forestier": "Adjektiver", "désertique": "Adjektiver",
  "urbain": "Adjektiver", "rural": "Adjektiver",

  // ── Adverb og bindeord ────────────────────────────────────────────────────
  "aussi": "Adverb og bindeord", "très": "Adverb og bindeord",
  "trop": "Adverb og bindeord", "bien": "Adverb og bindeord",
  "mal": "Adverb og bindeord", "encore": "Adverb og bindeord",
  "déjà": "Adverb og bindeord", "puis": "Adverb og bindeord",
  "alors": "Adverb og bindeord", "donc": "Adverb og bindeord",
  "mais": "Adverb og bindeord", "et": "Adverb og bindeord",
  "ou": "Adverb og bindeord", "car": "Adverb og bindeord",
  "comme": "Adverb og bindeord", "si": "Adverb og bindeord",
  "vraiment": "Adverb og bindeord", "seulement": "Adverb og bindeord",
  "surtout": "Adverb og bindeord", "peut-être": "Adverb og bindeord",
  "d'abord": "Adverb og bindeord", "ensuite": "Adverb og bindeord",
  "enfin": "Adverb og bindeord", "quand": "Adverb og bindeord",
  "comment": "Adverb og bindeord", "pourquoi": "Adverb og bindeord",
  "parce que": "Adverb og bindeord", "pendant": "Adverb og bindeord",
  "depuis": "Adverb og bindeord", "jusqu'à": "Adverb og bindeord",
  "pourtant": "Adverb og bindeord", "cependant": "Adverb og bindeord",
  "néanmoins": "Adverb og bindeord", "par contre": "Adverb og bindeord",
  "en effet": "Adverb og bindeord", "c'est-à-dire": "Adverb og bindeord",
  "autrement": "Adverb og bindeord", "également": "Adverb og bindeord",

  // ── Tid og frekvens ───────────────────────────────────────────────────────
  "aujourd'hui": "Tid og frekvens", "demain": "Tid og frekvens",
  "hier": "Tid og frekvens", "maintenant": "Tid og frekvens",
  "toujours": "Tid og frekvens", "jamais": "Tid og frekvens",
  "souvent": "Tid og frekvens", "parfois": "Tid og frekvens",
  "tôt": "Tid og frekvens", "tard": "Tid og frekvens",
  "bientôt": "Tid og frekvens", "longtemps": "Tid og frekvens",
  "semaine": "Tid og frekvens", "mois": "Tid og frekvens",
  "année": "Tid og frekvens", "heure": "Tid og frekvens",
  "minute": "Tid og frekvens", "seconde": "Tid og frekvens",
  "matin": "Tid og frekvens", "soir": "Tid og frekvens",
  "nuit": "Tid og frekvens", "jour": "Tid og frekvens",
  "journée": "Tid og frekvens", "temps": "Tid og frekvens",
  "printemps": "Tid og frekvens", "été": "Tid og frekvens",
  "automne": "Tid og frekvens", "hiver": "Tid og frekvens",
  "époque": "Tid og frekvens", "période": "Tid og frekvens",
  "siècle": "Tid og frekvens", "moment": "Tid og frekvens",
  "instant": "Tid og frekvens", "avenir": "Tid og frekvens",
  "passé": "Tid og frekvens", "futur": "Tid og frekvens",
  "lundi": "Tid og frekvens", "mardi": "Tid og frekvens",
  "mercredi": "Tid og frekvens", "jeudi": "Tid og frekvens",
  "vendredi": "Tid og frekvens", "samedi": "Tid og frekvens",
  "dimanche": "Tid og frekvens",
  "janvier": "Tid og frekvens", "février": "Tid og frekvens",
  "mars": "Tid og frekvens", "avril": "Tid og frekvens",
  "mai": "Tid og frekvens", "juin": "Tid og frekvens",
  "juillet": "Tid og frekvens", "août": "Tid og frekvens",
  "septembre": "Tid og frekvens", "octobre": "Tid og frekvens",
  "novembre": "Tid og frekvens", "décembre": "Tid og frekvens",
  "vite": "Tid og frekvens", "lentement": "Tid og frekvens",
  "rapidement": "Tid og frekvens",

  // ── Steder – Paris ────────────────────────────────────────────────────────
  "Paris": "Steder – Paris", "café": "Steder – Paris",
  "quartier": "Steder – Paris", "musée": "Steder – Paris",
  "la Seine": "Steder – Paris", "boulangerie": "Steder – Paris",
  "brasserie": "Steder – Paris", "Louvre": "Steder – Paris",
  "Montmartre": "Steder – Paris", "Versailles": "Steder – Paris",
  "arrondissement": "Steder – Paris", "tour Eiffel": "Steder – Paris",
  "Notre-Dame": "Steder – Paris", "Champs-Élysées": "Steder – Paris",
  "terrasse": "Steder – Paris", "bistrot": "Steder – Paris",

  // ── Steder og rom ─────────────────────────────────────────────────────────
  "rue": "Steder og rom", "gare": "Steder og rom", "hôtel": "Steder og rom",
  "restaurant": "Steder og rom", "bibliothèque": "Steder og rom",
  "ville": "Steder og rom", "village": "Steder og rom",
  "école": "Utdanning og arbeid", "cinéma": "Kunst og kultur",
  "théâtre": "Kunst og kultur", "hôpital": "Kropp og helse",
  "banque": "Shopping og tjenester", "bureau": "Utdanning og arbeid",
  "magasin": "Shopping og tjenester", "marché": "Shopping og tjenester",
  "supermarché": "Steder og rom", "pharmacie": "Steder og rom",
  "poste": "Steder og rom", "mairie": "Steder og rom",
  "église": "Steder og rom", "cathédrale": "Steder og rom",
  "place": "Steder og rom", "parc": "Steder og rom",
  "jardin": "Hjem og hverdagsliv", "chemin": "Steder og rom",
  "bâtiment": "Steder og rom", "immeuble": "Steder og rom",
  "ici": "Steder og rom", "là": "Steder og rom",
  "loin": "Steder og rom", "près": "Steder og rom",
  "dehors": "Steder og rom", "dedans": "Steder og rom",
  "droite": "Steder og rom", "gauche": "Steder og rom",
  "nord": "Steder og rom", "sud": "Steder og rom",
  "est": "Steder og rom", "ouest": "Steder og rom",
  "nord-est": "Steder og rom", "nord-ouest": "Steder og rom",
  "sud-est": "Steder og rom", "sud-ouest": "Steder og rom",
  "haut": "Steder og rom", "bas": "Steder og rom",
  "devant": "Steder og rom", "derrière": "Steder og rom",
  "entre": "Steder og rom", "à côté": "Steder og rom",
  "en face": "Steder og rom", "au bout": "Steder og rom",

  // ── Familie og relasjoner ─────────────────────────────────────────────────
  "famille": "Familie og relasjoner", "père": "Familie og relasjoner",
  "mère": "Familie og relasjoner", "fils": "Familie og relasjoner",
  "fille": "Familie og relasjoner", "frère": "Familie og relasjoner",
  "sœur": "Familie og relasjoner", "mari": "Familie og relasjoner",
  "femme": "Familie og relasjoner", "enfant": "Familie og relasjoner",
  "bébé": "Familie og relasjoner", "grand-père": "Familie og relasjoner",
  "grand-mère": "Familie og relasjoner", "oncle": "Familie og relasjoner",
  "tante": "Familie og relasjoner", "cousin": "Familie og relasjoner",
  "cousine": "Familie og relasjoner", "ami": "Familie og relasjoner",
  "amie": "Familie og relasjoner", "ami / amie": "Familie og relasjoner",
  "voisin": "Familie og relasjoner", "voisine": "Familie og relasjoner",
  "couple": "Familie og relasjoner", "mariage": "Familie og relasjoner",
  "fiançailles": "Familie og relasjoner", "divorce": "Familie og relasjoner",
  "homme": "Familie og relasjoner", "garçon": "Familie og relasjoner",
  "personne": "Familie og relasjoner", "gens": "Familie og relasjoner",
  "monde": "Land og geografi",

  // ── Kropp og helse ────────────────────────────────────────────────────────
  "tête": "Kropp og helse", "main": "Kropp og helse",
  "bras": "Kropp og helse", "jambe": "Kropp og helse",
  "pied": "Kropp og helse", "dos": "Kropp og helse",
  "corps": "Kropp og helse", "cœur": "Kropp og helse",
  "yeux": "Kropp og helse", "œil": "Kropp og helse",
  "bouche": "Kropp og helse", "nez": "Kropp og helse",
  "oreille": "Kropp og helse", "cheveux": "Kropp og helse",
  "dent": "Kropp og helse", "ventre": "Kropp og helse",
  "gorge": "Kropp og helse", "doigt": "Kropp og helse",
  "genou": "Kropp og helse", "épaule": "Kropp og helse",
  "poitrine": "Kropp og helse", "visage": "Kropp og helse",
  "peau": "Kropp og helse", "sang": "Kropp og helse",
  "médecin": "Kropp og helse", "docteur": "Kropp og helse",
  "hôpital": "Kropp og helse", "médicament": "Kropp og helse",
  "douleur": "Kropp og helse", "santé": "Kropp og helse",
  "maladie": "Kropp og helse", "fièvre": "Kropp og helse",
  "rhume": "Kropp og helse", "toux": "Kropp og helse",
  "fatigue": "Kropp og helse", "repos": "Kropp og helse",
  "se lever": "Kropp og helse", "se coucher": "Kropp og helse",
  "se laver": "Kropp og helse", "dormir": "Kropp og helse",
  "manger": "Kropp og helse", "boire": "Kropp og helse",
  "faim": "Kropp og helse", "soif": "Kropp og helse",

  // ── Klær og utseende ──────────────────────────────────────────────────────
  "vêtements": "Klær og utseende", "robe": "Klær og utseende",
  "pantalon": "Klær og utseende", "chemise": "Klær og utseende",
  "veste": "Klær og utseende", "manteau": "Klær og utseende",
  "chaussures": "Klær og utseende", "chapeau": "Klær og utseende",
  "sac": "Shopping og tjenester", "lunettes": "Klær og utseende",
  "jupe": "Klær og utseende", "pull": "Klær og utseende",
  "jean": "Klær og utseende", "t-shirt": "Klær og utseende",
  "imperméable": "Klær og utseende", "écharpe": "Klær og utseende",
  "gants": "Klær og utseende", "taille": "Klær og utseende",
  "mode": "Klær og utseende", "style": "Klær og utseende",

  // ── Mat og drikke ─────────────────────────────────────────────────────────
  "pain": "Mat og drikke", "vin": "Mat og drikke",
  "eau": "Mat og drikke", "fromage": "Mat og drikke",
  "bière": "Mat og drikke", "café": "Mat og drikke",
  "thé": "Mat og drikke", "lait": "Mat og drikke",
  "beurre": "Mat og drikke", "viande": "Mat og drikke",
  "poisson": "Mat og drikke", "poulet": "Mat og drikke",
  "légume": "Mat og drikke", "fruit": "Mat og drikke",
  "pomme": "Mat og drikke", "tomate": "Mat og drikke",
  "salade": "Mat og drikke", "soupe": "Mat og drikke",
  "dessert": "Mat og drikke", "gâteau": "Mat og drikke",
  "chocolat": "Mat og drikke", "sucre": "Mat og drikke",
  "sel": "Mat og drikke", "huile": "Mat og drikke",
  "repas": "Mat og drikke", "petit-déjeuner": "Mat og drikke",
  "déjeuner": "Mat og drikke", "dîner": "Mat og drikke",
  "menu": "Mat og drikke", "plat": "Mat og drikke",
  "entrée": "Mat og drikke", "addition": "Mat og drikke",
  "cuisiner": "Mat og drikke", "recette": "Mat og drikke",
  "ingrédient": "Mat og drikke", "goût": "Mat og drikke",
  "saveur": "Mat og drikke", "épice": "Mat og drikke",
  "farine": "Mat og drikke", "œuf": "Mat og drikke",
  "baguette": "Mat og drikke", "croissant": "Mat og drikke",
  "champagne": "Mat og drikke", "cognac": "Mat og drikke",
  "cidre": "Mat og drikke", "jus": "Mat og drikke",
  "apéritif": "Mat og drikke", "fromagerie": "Mat og drikke",
  "crêpe": "Mat og drikke", "tarte": "Mat og drikke",

  // ── Hjem og hverdagsliv ───────────────────────────────────────────────────
  "maison": "Hjem og hverdagsliv", "appartement": "Hjem og hverdagsliv",
  "chambre": "Hjem og hverdagsliv", "cuisine": "Hjem og hverdagsliv",
  "salon": "Hjem og hverdagsliv", "salle de bain": "Hjem og hverdagsliv",
  "lit": "Hjem og hverdagsliv", "table": "Hjem og hverdagsliv",
  "chaise": "Hjem og hverdagsliv", "canapé": "Hjem og hverdagsliv",
  "fenêtre": "Hjem og hverdagsliv", "porte": "Hjem og hverdagsliv",
  "escalier": "Hjem og hverdagsliv", "couloir": "Hjem og hverdagsliv",
  "clé": "Hjem og hverdagsliv", "loyer": "Hjem og hverdagsliv",
  "propriétaire": "Hjem og hverdagsliv", "locataire": "Hjem og hverdagsliv",
  "télévision": "Hjem og hverdagsliv", "téléphone": "Hjem og hverdagsliv",
  "ordinateur": "Hjem og hverdagsliv", "lumière": "Hjem og hverdagsliv",
  "bruit": "Hjem og hverdagsliv", "ranger": "Hjem og hverdagsliv",
  "nettoyer": "Hjem og hverdagsliv", "laver": "Hjem og hverdagsliv",
  "cuisiner": "Hjem og hverdagsliv", "vie quotidienne": "Hjem og hverdagsliv",
  "habitude": "Hjem og hverdagsliv", "routine": "Hjem og hverdagsliv",

  // ── Shopping og tjenester ─────────────────────────────────────────────────
  "argent": "Shopping og tjenester", "prix": "Shopping og tjenester",
  "payer": "Shopping og tjenester", "acheter": "Shopping og tjenester",
  "vendre": "Shopping og tjenester", "euro": "Shopping og tjenester",
  "carte": "Shopping og tjenester", "chèque": "Shopping og tjenester",
  "ticket": "Shopping og tjenester", "boutique": "Shopping og tjenester",
  "taille": "Shopping og tjenester", "soldes": "Shopping og tjenester",
  "remise": "Shopping og tjenester", "gratuit": "Shopping og tjenester",
  "cher": "Shopping og tjenester", "bon marché": "Shopping og tjenester",

  // ── Transport og reiser ───────────────────────────────────────────────────
  "train": "Transport og reiser", "bus": "Transport og reiser",
  "métro": "Transport og reiser", "voiture": "Transport og reiser",
  "vélo": "Transport og reiser", "avion": "Transport og reiser",
  "bateau": "Transport og reiser", "taxi": "Transport og reiser",
  "aéroport": "Transport og reiser", "billet": "Transport og reiser",
  "voyage": "Transport og reiser", "valise": "Transport og reiser",
  "passeport": "Transport og reiser", "frontière": "Transport og reiser",
  "destination": "Transport og reiser", "réservation": "Transport og reiser",
  "départ": "Transport og reiser", "arrivée": "Transport og reiser",
  "retard": "Transport og reiser", "correspondance": "Transport og reiser",
  "quai": "Transport og reiser", "piste": "Transport og reiser",
  "embarquement": "Transport og reiser", "douane": "Transport og reiser",
  "horaire": "Transport og reiser", "aller-retour": "Transport og reiser",
  "location": "Transport og reiser", "autoroute": "Transport og reiser",

  // ── Natur og vær ──────────────────────────────────────────────────────────
  "soleil": "Natur og vær", "ciel": "Natur og vær",
  "nuage": "Natur og vær", "pluie": "Natur og vær",
  "neige": "Natur og vær", "vent": "Natur og vær",
  "mer": "Natur og vær", "montagne": "Natur og vær",
  "forêt": "Natur og vær", "fleuve": "Natur og vær",
  "rivière": "Natur og vær", "lac": "Natur og vær",
  "plage": "Natur og vær", "île": "Natur og vær",
  "campagne": "Natur og vær", "colline": "Natur og vær",
  "vallée": "Natur og vær", "côte": "Natur og vær",
  "falaise": "Natur og vær", "désert": "Natur og vær",
  "jungle": "Natur og vær", "savane": "Natur og vær",
  "prairie": "Natur og vær", "marais": "Natur og vær",
  "glacier": "Natur og vær", "volcan": "Natur og vær",
  "canyon": "Natur og vær", "plateau": "Natur og vær",
  "fjord": "Natur og vær", "péninsule": "Natur og vær",
  "cap": "Natur og vær", "baie": "Natur og vær",
  "golfe": "Natur og vær", "détroit": "Natur og vær",
  "delta": "Natur og vær", "archipel": "Natur og vær",
  "orage": "Natur og vær", "tonnerre": "Natur og vær",
  "éclair": "Natur og vær", "brouillard": "Natur og vær",
  "verglas": "Natur og vær", "tempête": "Natur og vær",
  "ouragan": "Natur og vær", "tornade": "Natur og vær",
  "inondation": "Natur og vær", "sécheresse": "Natur og vær",
  "canicule": "Natur og vær", "grêle": "Natur og vær",
  "givre": "Natur og vær", "brume": "Natur og vær",
  "rosée": "Natur og vær", "chaleur": "Natur og vær",
  "gel": "Natur og vær", "dégel": "Natur og vær",
  "précipitations": "Natur og vær", "humidité": "Natur og vær",
  "météo": "Natur og vær", "climat": "Natur og vær",
  "environnement": "Natur og vær", "paysage": "Natur og vær",
  "nature": "Natur og vær", "arbre": "Natur og vær",
  "fleur": "Natur og vær", "herbe": "Natur og vær",
  "feuille": "Natur og vær", "pierre": "Natur og vær",
  "il fait beau": "Natur og vær", "il pleut": "Natur og vær",
  "il neige": "Natur og vær", "il gèle": "Natur og vær",
  "il fait chaud": "Natur og vær", "il fait froid": "Natur og vær",
  "le temps est couvert": "Natur og vær", "le temps est dégagé": "Natur og vær",
  "chaîne de montagnes": "Natur og vær", "point culminant": "Natur og vær",
  "superficie": "Natur og vær", "altitude": "Natur og vær",
  "bassin": "Natur og vær", "relief": "Natur og vær",

  // ── Dyr ───────────────────────────────────────────────────────────────────
  "chien": "Dyr", "chat": "Dyr", "cheval": "Dyr",
  "oiseau": "Dyr", "poisson": "Dyr", "vache": "Dyr",
  "cochon": "Dyr", "mouton": "Dyr", "lapin": "Dyr",
  "loup": "Dyr", "renard": "Dyr", "cerf": "Dyr",
  "aigle": "Dyr", "canard": "Dyr", "poule": "Dyr",
  "grenouille": "Dyr", "abeille": "Dyr", "papillon": "Dyr",
  "serpent": "Dyr", "lion": "Dyr", "tigre": "Dyr",
  "éléphant": "Dyr", "singe": "Dyr", "ours": "Dyr",

  // ── Land og geografi ──────────────────────────────────────────────────────
  "France": "Land og geografi", "Italie": "Land og geografi",
  "Espagne": "Land og geografi", "Allemagne": "Land og geografi",
  "Angleterre": "Land og geografi", "Belgique": "Land og geografi",
  "Suisse": "Land og geografi", "Portugal": "Land og geografi",
  "Pays-Bas": "Land og geografi", "Suède": "Land og geografi",
  "Norvège": "Land og geografi", "Danemark": "Land og geografi",
  "Finlande": "Land og geografi", "Pologne": "Land og geografi",
  "Russie": "Land og geografi", "Autriche": "Land og geografi",
  "Grèce": "Land og geografi", "Turquie": "Land og geografi",
  "Irlande": "Land og geografi", "Luxembourg": "Land og geografi",
  "Roumanie": "Land og geografi", "États-Unis": "Land og geografi",
  "Canada": "Land og geografi", "Mexique": "Land og geografi",
  "Brésil": "Land og geografi", "Argentine": "Land og geografi",
  "Maroc": "Land og geografi", "Algérie": "Land og geografi",
  "Tunisie": "Land og geografi", "Égypte": "Land og geografi",
  "Sénégal": "Land og geografi", "Chine": "Land og geografi",
  "Japon": "Land og geografi", "Inde": "Land og geografi",
  "Australie": "Land og geografi", "Afrique du Sud": "Land og geografi",
  "Europe": "Land og geografi", "Afrique": "Land og geografi",
  "Amérique": "Land og geografi", "Asie": "Land og geografi",
  "pays": "Land og geografi", "capitale": "Land og geografi",
  "continent": "Land og geografi", "territoire": "Land og geografi",
  "département": "Land og geografi", "commune": "Land og geografi",
  "province": "Land og geografi", "métropole": "Land og geografi",
  "frontière": "Land og geografi", "population": "Land og geografi",
  "équateur": "Land og geografi", "tropiques": "Land og geografi",
  "pôle": "Land og geografi", "hémisphère": "Land og geografi",
  "latitude": "Land og geografi", "longitude": "Land og geografi",
  "littoral": "Land og geografi", "Hexagone": "Land og geografi",
  "Méditerranée": "Land og geografi", "Loire": "Land og geografi",
  "Rhône": "Land og geografi", "Garonne": "Land og geografi",
  "Seine": "Land og geografi", "mer du Nord": "Land og geografi",
  "golfe de Gascogne": "Land og geografi",
  "Normandie": "Land og geografi", "Île-de-France": "Land og geografi",
  "Aquitaine": "Land og geografi", "Occitanie": "Land og geografi",
  "Auvergne": "Land og geografi", "Bourgogne": "Land og geografi",
  "Champagne": "Land og geografi", "Lorraine": "Land og geografi",
  "Nord-Pas-de-Calais": "Land og geografi", "Pays de la Loire": "Land og geografi",
  "Centre-Val de Loire": "Land og geografi", "Languedoc": "Land og geografi",
  "Limousin": "Land og geografi", "Franche-Comté": "Land og geografi",
  "Rhône-Alpes": "Land og geografi", "Corse": "Land og geografi",
  "Monaco": "Land og geografi",
  "Lyon": "Land og geografi", "Marseille": "Land og geografi",
  "Bordeaux": "Land og geografi", "Toulouse": "Land og geografi",
  "Nantes": "Land og geografi", "Strasbourg": "Land og geografi",
  "Nice": "Land og geografi", "Rennes": "Land og geografi",
  "Grenoble": "Land og geografi", "Montpellier": "Land og geografi",
  "Lille": "Land og geografi", "Brest": "Land og geografi",
  "Rouen": "Land og geografi", "Clermont-Ferrand": "Land og geografi",

  // ── Kunst og kultur ───────────────────────────────────────────────────────
  "artiste": "Kunst og kultur", "peintre": "Kunst og kultur",
  "écrivain": "Kunst og kultur", "roman": "Kunst og kultur",
  "livre": "Kunst og kultur", "tableau": "Kunst og kultur",
  "jazz": "Kunst og kultur", "musique": "Kunst og kultur",
  "étranger": "Kunst og kultur",
  "chanson": "Kunst og kultur", "film": "Kunst og kultur",
  "exposition": "Kunst og kultur", "peinture": "Kunst og kultur",
  "sculpture": "Kunst og kultur", "architecture": "Kunst og kultur",
  "concert": "Kunst og kultur", "spectacle": "Kunst og kultur",
  "festival": "Kunst og kultur", "opéra": "Kunst og kultur",
  "danse": "Kunst og kultur", "ballet": "Kunst og kultur",
  "poème": "Kunst og kultur", "poésie": "Kunst og kultur",
  "auteur": "Kunst og kultur", "réalisateur": "Kunst og kultur",
  "acteur": "Kunst og kultur", "actrice": "Kunst og kultur",
  "scène": "Kunst og kultur", "public": "Kunst og kultur",
  "art": "Kunst og kultur", "culture": "Kunst og kultur",
  "patrimoine": "Kunst og kultur", "chef-d'œuvre": "Kunst og kultur",
  "mouvement": "Kunst og kultur", "courant": "Kunst og kultur",
  "siècle": "Kunst og kultur", "classique": "Kunst og kultur",
  "moderne": "Kunst og kultur", "contemporain": "Kunst og kultur",

  // ── Sport og fritid ───────────────────────────────────────────────────────
  "sport": "Sport og fritid", "football": "Sport og fritid",
  "natation": "Sport og fritid", "tennis": "Sport og fritid",
  "ski": "Sport og fritid", "équipe": "Sport og fritid",
  "match": "Sport og fritid", "victoire": "Sport og fritid",
  "défaite": "Sport og fritid", "jeu": "Sport og fritid",
  "jouer": "Sport og fritid", "gagner": "Sport og fritid",
  "perdre": "Sport og fritid", "champion": "Sport og fritid",
  "stade": "Sport og fritid", "entraîneur": "Sport og fritid",
  "joueur": "Sport og fritid", "loisir": "Sport og fritid",
  "vacances": "Sport og fritid", "baignade": "Sport og fritid",
  "randonnée": "Sport og fritid", "camping": "Sport og fritid",
  "photographie": "Sport og fritid", "jardinage": "Sport og fritid",

  // ── Tour de France ────────────────────────────────────────────────────────
  "cycliste": "Tour de France", "peloton": "Tour de France",
  "maillot jaune": "Tour de France", "étape": "Tour de France",
  "col": "Tour de France", "sprint": "Tour de France",
  "grimpeur": "Tour de France", "coureur": "Tour de France",
  "leader": "Tour de France", "abandon": "Tour de France",
  "chrono": "Tour de France", "contre-la-montre": "Tour de France",
  "Alpes": "Tour de France", "Pyrénées": "Tour de France",
  "Tour de France": "Tour de France", "podium": "Tour de France",
  "maillot": "Tour de France", "classement": "Tour de France",
  "échappée": "Tour de France", "peloton de tête": "Tour de France",
  "montée": "Tour de France", "descente": "Tour de France",
  "kilomètre": "Tour de France", "ravitaillement": "Tour de France",
  "domestique": "Tour de France", "équipier": "Tour de France",
  "sprinter": "Tour de France", "puncheur": "Tour de France",
  "baroudeur": "Tour de France", "directeur sportif": "Tour de France",
  "peloton principal": "Tour de France",

  // ── Utdanning og arbeid ───────────────────────────────────────────────────
  "travail": "Utdanning og arbeid", "emploi": "Utdanning og arbeid",
  "profession": "Utdanning og arbeid", "métier": "Utdanning og arbeid",
  "université": "Utdanning og arbeid", "professeur": "Utdanning og arbeid",
  "élève": "Utdanning og arbeid", "étudiant": "Utdanning og arbeid",
  "classe": "Utdanning og arbeid", "cours": "Utdanning og arbeid",
  "leçon": "Utdanning og arbeid", "examen": "Utdanning og arbeid",
  "diplôme": "Utdanning og arbeid", "chef": "Utdanning og arbeid",
  "collègue": "Utdanning og arbeid", "salaire": "Utdanning og arbeid",
  "entreprise": "Utdanning og arbeid", "réunion": "Utdanning og arbeid",
  "médecin": "Utdanning og arbeid", "avocat": "Utdanning og arbeid",
  "ingénieur": "Utdanning og arbeid", "journaliste": "Utdanning og arbeid",
  "infirmier": "Utdanning og arbeid", "architecte": "Utdanning og arbeid",
  "travailler": "Utdanning og arbeid",

  // ── Samfunn og politikk ───────────────────────────────────────────────────
  "gouvernement": "Samfunn og politikk",
  "président": "Samfunn og politikk", "élection": "Samfunn og politikk",
  "loi": "Samfunn og politikk", "droits": "Samfunn og politikk",
  "liberté": "Samfunn og politikk", "égalité": "Samfunn og politikk",
  "fraternité": "Samfunn og politikk", "citoyen": "Samfunn og politikk",
  "société": "Samfunn og politikk", "économie": "Samfunn og politikk",
  "politique": "Samfunn og politikk", "parti": "Samfunn og politikk",
  "vote": "Samfunn og politikk", "paix": "Samfunn og politikk",
  "histoire": "Samfunn og politikk", "révolution": "Samfunn og politikk",
  "démocratie": "Samfunn og politikk", "République": "Samfunn og politikk",
  "parlement": "Samfunn og politikk", "assemblée": "Samfunn og politikk",
  "armée": "Samfunn og politikk", "soldats": "Samfunn og politikk",
  "surveillance": "Samfunn og politikk", "trêve": "Samfunn og politikk",
  "guerre": "Samfunn og politikk",

  // ── Fra ordbank: manglende enkeltord ─────────────────────────────────────
  "à": "Adverb og bindeord", "selon": "Adverb og bindeord",
  "tout de suite": "Adverb og bindeord",
  "dixième": "Tallord og mengde", "quatorze": "Tallord og mengde",
  "porter": "Vanlige verb", "exclut": "Vanlige verb",
  "impoli": "Adjektiver",
  "lune": "Natur og vær",
  "vie": "Følelser og identitet",
  "problème": "Kommunikasjon og tanker",
  "attaque": "Tour de France",
  "attaquer": "Tour de France", "bidon": "Tour de France",
  "capitaine de route": "Tour de France", "casque": "Tour de France",
  "chaîne": "Tour de France", "commissaire": "Tour de France",
  "compteur": "Tour de France", "cuissard": "Tour de France",
  "dérailleur": "Tour de France", "frein": "Tour de France",
  "fuite": "Tour de France", "gps": "Tour de France",
  "guidon": "Tour de France", "maillot vert": "Tour de France",
  "mécano": "Tour de France", "oreillette": "Tour de France",
  "pédale": "Tour de France", "roue": "Tour de France",
  "rouleur": "Tour de France", "sacoche": "Tour de France",
  "selle": "Tour de France", "soigneur": "Tour de France",
  "vainqueur": "Tour de France",
  "championne": "Sport og fritid",
  "en fait": "Adverb og bindeord", "quand même": "Adverb og bindeord",
};

export const GRAMMAR_TOPICS = [
  {
    id: "etre",
    title: "être — å være",
    subtitle: "Grunnleggende konjugasjon",
    description: "Lær å konjugere être (å være) for alle pronomen. Dette er det viktigste verbet på fransk!",
    pairs: [
      { fr: "je suis", no: "jeg er", phonetic: "sjø swi" },
      { fr: "tu es", no: "du er", phonetic: "ty æ" },
      { fr: "il est", no: "han er", phonetic: "il æ" },
      { fr: "elle est", no: "hun er", phonetic: "æl æ" },
      { fr: "nous sommes", no: "vi er", phonetic: "nu sOm" },
      { fr: "vous êtes", no: "dere er", phonetic: "vu æt" },
      { fr: "ils sont", no: "de er", phonetic: "il sån" },
    ],
  },
  {
    id: "avoir",
    title: "avoir — å ha",
    subtitle: "Grunnleggende konjugasjon",
    description: "Lær å konjugere avoir (å ha). Brukes også for å danne fortid på fransk.",
    pairs: [
      { fr: "j'ai", no: "jeg har", phonetic: "sjæ" },
      { fr: "tu as", no: "du har", phonetic: "ty a" },
      { fr: "il a", no: "han har", phonetic: "il a" },
      { fr: "elle a", no: "hun har", phonetic: "æl a" },
      { fr: "nous avons", no: "vi har", phonetic: "nu avån" },
      { fr: "vous avez", no: "dere har", phonetic: "vu avæ" },
      { fr: "ils ont", no: "de har", phonetic: "il zån" },
    ],
  },
  {
    id: "articles",
    title: "Artikler — le, la, un, une",
    subtitle: "Kjønn og artikler",
    description: "På fransk har alle substantiv kjønn — hankjønn (le/un) eller hunkjønn (la/une). Foran vokal brukes l'. Bestemt flertall: les. Ubestemt flertall: des. Kjønnet må pugges ord for ord — det finnes ingen enkel regel.",
    pairs: [
      { fr: "le café", no: "kaféen", phonetic: "lə kafæ" },
      { fr: "la rue", no: "gaten", phonetic: "la ry" },
      { fr: "l'homme", no: "mannen", phonetic: "lOm" },
      { fr: "un livre", no: "en bok", phonetic: "øn livr" },
      { fr: "une femme", no: "en kvinne", phonetic: "yn fam" },
      { fr: "les artistes", no: "kunstnerne", phonetic: "læ zartist" },
      { fr: "des cafés", no: "noen kaféer", phonetic: "dæ kafæ" },
      { fr: "le monde", no: "verden (hankjønn)", phonetic: "lə månd" },
      { fr: "la musique", no: "musikken (hunkjønn)", phonetic: "la myzik" },
      { fr: "l'ami", no: "vennen (hankjønn)", phonetic: "lami" },
      { fr: "l'amie", no: "venninnen (hunkjønn)", phonetic: "lami" },
      { fr: "un homme", no: "en mann", phonetic: "øn Om" },
      { fr: "une ville", no: "en by", phonetic: "yn vil" },
      { fr: "le temps", no: "tiden / været (hankjønn)", phonetic: "lə tå" },
      { fr: "la vie", no: "livet (hunkjønn)", phonetic: "la vi" },
    ],
  },
  {
    id: "negation",
    title: "Negasjon — ne...pas, jamais, plus, rien",
    subtitle: "Å si nei på fransk",
    description: "Grunnform: ne + verb + pas. Ne forkortes til n' foran vokal. Varianter: ne...jamais (aldri), ne...plus (ikke lenger), ne...rien (ingenting), ne...personne (ingen). I muntlig fransk sløyfes ne ofte.",
    pairs: [
      { fr: "je ne suis pas", no: "jeg er ikke", phonetic: "sjø nə swi pa" },
      { fr: "tu n'es pas", no: "du er ikke", phonetic: "ty næ pa" },
      { fr: "il n'est pas", no: "han er ikke", phonetic: "il næ pa" },
      { fr: "je n'ai pas", no: "jeg har ikke", phonetic: "sjø næ pa" },
      { fr: "ce n'est pas bon", no: "det er ikke bra", phonetic: "sə næ pa bån" },
      { fr: "je n'aime pas ça", no: "jeg liker ikke det", phonetic: "sjø næm pa sa" },
      { fr: "je ne parle jamais", no: "jeg snakker aldri", phonetic: "sjø nə parl sjamæ" },
      { fr: "il n'y a plus de café", no: "det er ikke mer kaffe", phonetic: "il nja ply də kafæ" },
      { fr: "je ne vois rien", no: "jeg ser ingenting", phonetic: "sjø nə vwa rjæn" },
      { fr: "elle ne vient plus", no: "hun kommer ikke lenger", phonetic: "æl nə vjæn ply" },
      { fr: "il ne parle à personne", no: "han snakker ikke med noen", phonetic: "il nə parl a pærsOn" },
    ],
  },
  {
    id: "er-verbs",
    title: "-er verb — parler",
    subtitle: "Første konjugasjonsgruppe",
    description: "De fleste franske verb slutter på -er. Lær mønsteret med parler (å snakke) — det gjelder for hundrevis av verb!",
    pairs: [
      { fr: "je parle", no: "jeg snakker", phonetic: "sjø parl" },
      { fr: "tu parles", no: "du snakker", phonetic: "ty parl" },
      { fr: "il parle", no: "han snakker", phonetic: "il parl" },
      { fr: "nous parlons", no: "vi snakker", phonetic: "nu parlån" },
      { fr: "vous parlez", no: "dere snakker", phonetic: "vu parlæ" },
      { fr: "ils parlent", no: "de snakker", phonetic: "il parl" },
      { fr: "j'aime Paris", no: "jeg liker Paris", phonetic: "sjæm pari" },
    ],
  },
  {
    id: "questions",
    title: "Spørsmål",
    subtitle: "Å spørre på fransk",
    description: "Lær de vanligste spørreutrykkene. Du kan alltid legge est-ce que foran en setning for å gjøre det til et spørsmål.",
    pairs: [
      { fr: "Où habitez-vous?", no: "Hvor bor du?", phonetic: "u abitæ vu" },
      { fr: "Êtes-vous artiste?", no: "Er du kunstner?", phonetic: "æt vu zartist" },
      { fr: "Aimez-vous Paris?", no: "Liker du Paris?", phonetic: "æmæ vu pari" },
      { fr: "Qu'est-ce que c'est?", no: "Hva er det?", phonetic: "kæskə sæ" },
      { fr: "Avez-vous un livre?", no: "Har du en bok?", phonetic: "avæ vu øn livr" },
      { fr: "Parlez-vous souvent?", no: "Snakker du ofte?", phonetic: "parlæ vu suvå" },
    ],
  },
  {
    id: "passe-compose",
    title: "Passé composé",
    subtitle: "Fortid med avoir og être",
    description: "Fortidsformen brukes for å si hva du har gjort. De fleste verb bruker avoir: j'ai + partisipp. Ca. 17 bevegelsesverb (aller, venir, partir, arriver, naître, mourir...) bruker être som hjelpeverb — og partisippen bøyes da etter subjektets kjønn og tall.",
    pairs: [
      { fr: "j'ai mangé", no: "jeg spiste / jeg har spist", phonetic: "sjæ månsjæ" },
      { fr: "tu as parlé", no: "du snakket", phonetic: "ty a parlæ" },
      { fr: "il a vu", no: "han så", phonetic: "il a vy" },
      { fr: "nous avons lu", no: "vi leste", phonetic: "nu zavån ly" },
      { fr: "elle a aimé le café", no: "hun likte kaféen", phonetic: "æl a æmæ lə kafæ" },
      { fr: "j'ai écrit un livre", no: "jeg skrev en bok", phonetic: "sjæ ekri øn livr" },
      { fr: "je suis allé(e) à Paris", no: "jeg dro til Paris (aller → être-hjelp.)", phonetic: "sjø swi zalæ a pari" },
      { fr: "elle est venue au café", no: "hun kom til kaféen (venir → être-hjelp.)", phonetic: "æl æ vøny o kafæ" },
      { fr: "nous sommes allés au musée", no: "vi dro til museet (aller → être-hjelp.)", phonetic: "nu sOm zalæ o myzæ" },
      { fr: "tu es venu(e) à Paris", no: "du kom til Paris (venir → être-hjelp.)", phonetic: "ty æ vøny a pari" },
      { fr: "ils sont venus hier", no: "de kom i går (venir → être-hjelp.)", phonetic: "il sån vøny jær" },
      { fr: "elle a bu du vin au restaurant", no: "hun drakk vin på restauranten", phonetic: "æl a by dy væn o restårå" },
    ],
  },
  // --- Fase 2: Hverdagsfransk ---
  {
    id: "partitifs",
    title: "Partitivartikler — du, de la, des",
    subtitle: "Litt av noe",
    description: "Når du snakker om en ubestemt mengde bruker du du (hankjønn), de la (hunkjønn) eller de l' (foran vokal). Tenk: 'noe brød', 'litt musikk'.",
    pairs: [
      { fr: "du pain", no: "noe brød / brød", phonetic: "dy pæn" },
      { fr: "de la musique", no: "noe musikk / musikk", phonetic: "də la myzik" },
      { fr: "de l'eau", no: "noe vann / vann", phonetic: "də lo" },
      { fr: "des amis", no: "noen venner", phonetic: "dæ zami" },
      { fr: "je mange du fromage", no: "jeg spiser ost", phonetic: "sjø månj dy fromåsj" },
      { fr: "elle boit de la bière", no: "hun drikker øl", phonetic: "æl bwa də la bjær" },
      { fr: "il n'y a pas de café", no: "det er ikke noe kaffe", phonetic: "il nja pa də kafæ" },
    ],
  },
  {
    id: "reflexifs",
    title: "Refleksive verb — se lever",
    subtitle: "Handlinger du gjør mot deg selv",
    description: "Refleksive verb har et pronomen (me, te, se, nous, vous) foran verbet. De brukes ofte om daglige rutiner: stå opp, vaske seg, føle seg.",
    pairs: [
      { fr: "je me lève", no: "jeg står opp", phonetic: "sjø mə læv" },
      { fr: "tu te lèves", no: "du står opp", phonetic: "ty tə læv" },
      { fr: "il se lève", no: "han står opp", phonetic: "il sə læv" },
      { fr: "je me lave", no: "jeg vasker meg", phonetic: "sjø mə lav" },
      { fr: "elle se sent bien", no: "hun har det bra", phonetic: "æl sə sån bjæn" },
      { fr: "nous nous levons", no: "vi står opp", phonetic: "nu nu ləvån" },
      { fr: "je me souviens", no: "jeg husker", phonetic: "sjø mə suvjæn" },
    ],
  },
  {
    id: "possessifs",
    title: "Possessiver — mon, ma, mes",
    subtitle: "Eierskap og tilhørighet",
    description: "Possessivene bøyes etter kjønnet på DET MAN EIER, ikke eieren. Hankjønn: mon/ton/son. Hunkjønn: ma/ta/sa (men mon/ton/son foran vokal). Flertall: mes/tes/ses. Vi: notre/nos. Dere/De: votre/vos. De: leur/leurs.",
    pairs: [
      { fr: "mon ami", no: "vennen min (hankjønn)", phonetic: "mån ami" },
      { fr: "ma ville", no: "byen min (hunkjønn)", phonetic: "ma vil" },
      { fr: "mes livres", no: "bøkene mine (flertall)", phonetic: "mæ livr" },
      { fr: "ton ami", no: "vennen din (hankjønn)", phonetic: "tån ami" },
      { fr: "mon amie", no: "venninnen min (mon foran vokal!)", phonetic: "mån ami" },
      { fr: "sa femme", no: "kona hans / kona hennes", phonetic: "sa fam" },
      { fr: "son livre", no: "boken hans/hennes", phonetic: "sån livr" },
      { fr: "notre café", no: "kaféen vår", phonetic: "nOtr kafæ" },
      { fr: "nos livres", no: "bøkene våre", phonetic: "no livr" },
      { fr: "votre livre", no: "boken din/deres (formelt)", phonetic: "vOtr livr" },
      { fr: "vos amis", no: "vennene dine/deres (formelt)", phonetic: "vo zami" },
      { fr: "leur restaurant", no: "restauranten deres", phonetic: "lœr restårå" },
      { fr: "leurs livres", no: "bøkene deres", phonetic: "lœr livr" },
    ],
  },
  {
    id: "futur-proche",
    title: "Futur proche — aller + infinitif",
    subtitle: "Nær fremtid",
    description: "Den enkleste måten å si hva du skal gjøre: bruk aller (å gå/dra) konjugert + et infinitiv. Tilsvarer norsk 'skal' eller 'kommer til å'.",
    pairs: [
      { fr: "je vais boire du vin", no: "jeg skal drikke vin", phonetic: "sjø væ bwar dy væn" },
      { fr: "tu vas manger", no: "du skal spise", phonetic: "ty va månsjæ" },
      { fr: "il va faire beau", no: "det skal bli fint vær", phonetic: "il va fær bo" },
      { fr: "nous allons voir Paris", no: "vi skal se Paris", phonetic: "nu zalån vwar pari" },
      { fr: "qu'est-ce que tu vas faire?", no: "hva skal du gjøre?", phonetic: "kæskə ty va fær" },
      { fr: "elle va lire un livre", no: "hun skal lese en bok", phonetic: "æl va lir øn livr" },
      { fr: "ils vont venir demain", no: "de skal komme i morgen", phonetic: "il vån vənir dəmæn" },
    ],
  },
  {
    id: "accord-adjectif",
    title: "Adjektivbøyning — kjønn og tall",
    subtitle: "Adjektiv må bøyes",
    description: "Adjektiver bøyes etter substantivets kjønn og tall. Grunnregel: legg til -e for hunkjønn, -s for flertall, -es for hunkjønn flertall. Uregelmessige: beau/belle, vieux/vieille, nouveau/nouvelle. Noen adjektiv står FORAN substantivet (beau, vieux, nouveau, grand, petit, bon, mauvais).",
    pairs: [
      { fr: "un grand café", no: "en stor kafé", phonetic: "øn grå kafæ" },
      { fr: "une grande ville", no: "en stor by", phonetic: "yn grågd vil" },
      { fr: "un livre simple", no: "en enkel bok", phonetic: "øn livr sæmpl" },
      { fr: "une belle musique", no: "en vakker musikk (beau → belle i hunkjønn)", phonetic: "yn bæl myzik" },
      { fr: "de beaux tableaux", no: "vakre malerier (beau → beaux i flertall)", phonetic: "də bo tablo" },
      { fr: "une belle femme", no: "en vakker kvinne", phonetic: "yn bæl fam" },
      { fr: "les artistes sont bons", no: "kunstnerne er gode (bon → bons i flertall)", phonetic: "læ zartist sån bån" },
      { fr: "un vieux livre", no: "en gammel bok (hankjønn)", phonetic: "øn vjø livr" },
      { fr: "une vieille ville", no: "en gammel by (vieux → vieille i hunkjønn)", phonetic: "yn vjæj vil" },
      { fr: "un nouveau roman", no: "en ny roman (hankjønn)", phonetic: "øn nuvo romå" },
      { fr: "une nouvelle vie", no: "et nytt liv (nouveau → nouvelle i hunkjønn)", phonetic: "yn nuvæl vi" },
      { fr: "un beau tableau", no: "et vakkert maleri", phonetic: "øn bo tablo" },
      { fr: "une bonne bière", no: "en god øl (bon → bonne i hunkjønn)", phonetic: "yn bOn bjær" },
    ],
  },
  {
    id: "prepositions-lieux",
    title: "Preposisjoner — land og byer",
    subtitle: "Å si hvor du er og drar",
    description: "Til/i by: à. Til/i hunkjønnsland: en. Til/i hankjønnsland: au. Fra by: de. Fra land: de/du/des. Frankrike er hunkjønn — en France.",
    pairs: [
      { fr: "je vais à Paris", no: "jeg drar til Paris (by → à)", phonetic: "sjø væ a pari" },
      { fr: "il habite en France", no: "han bor i Frankrike (hunkjønnsland → en)", phonetic: "il abit å frås" },
      { fr: "j'habite en France", no: "jeg bor i Frankrike", phonetic: "sjabit å frås" },
      { fr: "elle vient de Paris", no: "hun kommer fra Paris (by → de)", phonetic: "æl vjæn də pari" },
      { fr: "nous allons en France", no: "vi drar til Frankrike", phonetic: "nu zalån å frås" },
      { fr: "il habite à Paris", no: "han bor i Paris (by → à)", phonetic: "il abit a pari" },
      { fr: "je viens de Paris", no: "jeg kommer fra Paris", phonetic: "sjø vjæn də pari" },
    ],
  },
  // --- Fase 3: Mellomtrinn ---
  {
    id: "imperatif",
    title: "Imperativ — beordre og be",
    subtitle: "Å gi beskjeder",
    description: "Imperativ brukes for å gi ordre, råd eller oppfordringer. Drop subjektet — bare bruk verbformen direkte. Tu-form mister -s for -er verb: parler → parle (ikke parles).",
    pairs: [
      { fr: "Viens!", no: "Kom!", phonetic: "vjæn" },
      { fr: "Mange!", no: "Spis! (tu-form: manger → mange)", phonetic: "månj" },
      { fr: "Parlez souvent!", no: "Snakk ofte! (vous-form)", phonetic: "parlæ suvå" },
      { fr: "Ne parle pas!", no: "Ikke snakk! (tu-form med negasjon)", phonetic: "nə parl pa" },
      { fr: "Lis ce livre!", no: "Les denne boken!", phonetic: "li sə livr" },
      { fr: "Buvez de l'eau!", no: "Drikk vann! (vous-form)", phonetic: "byvæ də lo" },
      { fr: "Venez voir Paris!", no: "Kom og se Paris!", phonetic: "vənæ vwar pari" },
    ],
  },
  {
    id: "imparfait",
    title: "Imparfait — beskrivelse i fortid",
    subtitle: "Slik var det",
    description: "Imparfait brukes for å beskrive hvordan noe var, hva som pleide å skje, eller bakgrunnssituasjoner. Mønster: stamme + -ais, -ais, -ait, -ions, -iez, -aient.",
    pairs: [
      { fr: "il faisait beau", no: "det var fint vær", phonetic: "il fəzæ bo" },
      { fr: "c'était une belle ville", no: "det var en vakker by", phonetic: "sætæ yn bæl vil" },
      { fr: "j'aimais la musique", no: "jeg likte musikk", phonetic: "sjæmæ la myzik" },
      { fr: "nous habitions à Paris", no: "vi bodde i Paris", phonetic: "nu zabitjån a pari" },
      { fr: "elle aimait lire", no: "hun likte å lese", phonetic: "æl æmæ lir" },
      { fr: "il y avait du vin", no: "det var vin (der)", phonetic: "il javæ dy væn" },
      { fr: "je lisais souvent", no: "jeg leste ofte", phonetic: "sjø lizæ suvå" },
    ],
  },
  {
    id: "imparfait-vs-passe",
    title: "Imparfait vs. passé composé",
    subtitle: "Fortid i kontekst",
    description: "Passé composé = avsluttet hendelse ('jeg spiste'). Imparfait = pågående tilstand eller vane ('jeg spiste alltid'). Begge kan brukes i samme setning.",
    pairs: [
      { fr: "hier, j'ai mangé du pain", no: "i går spiste jeg brød (avsluttet)", phonetic: "jær sjæ månsjæ dy pæn" },
      { fr: "avant, je mangeais souvent du pain", no: "før spiste jeg ofte brød (vane)", phonetic: "avå sjø månsjæ suvå dy pæn" },
      { fr: "il lisait quand je suis venu", no: "han leste da jeg kom", phonetic: "il lizæ kå sjø swi vøny" },
      { fr: "elle buvait du vin pendant que je lisais", no: "hun drakk vin mens jeg leste", phonetic: "æl byvæ dy væn pådå kə sjø lizæ" },
      { fr: "nous avons vu le musée", no: "vi så museet (avsluttet)", phonetic: "nu zavån vy lə myzæ" },
      { fr: "il faisait beau quand nous sommes allés au café", no: "det var fint da vi gikk på kafé", phonetic: "il fəzæ bo kå nu sOm zalæ o kafæ" },
      { fr: "j'ai écrit un livre il y a deux ans", no: "jeg skrev en bok for to år siden", phonetic: "sjæ ekri øn livr il ja dø å" },
    ],
  },
  {
    id: "conditionnel",
    title: "Kondisjonalis — ville og skulle",
    subtitle: "Det hypotetiske",
    description: "Kondisjonalis uttrykker ønsker, hypoteser og høflige forespørsler. Dannes av infinitiv + imparfait-endinger: -ais, -ais, -ait, -ions, -iez, -aient.",
    pairs: [
      { fr: "je voudrais un café", no: "jeg vil gjerne ha en kaffe (høflig)", phonetic: "sjø vudræ øn kafæ" },
      { fr: "ce serait beau", no: "det ville vært vakkert", phonetic: "sə sræ bo" },
      { fr: "j'aimerais voir Paris", no: "jeg skulle gjerne sett Paris", phonetic: "sjæmræ vwar pari" },
      { fr: "tu aimerais venir?", no: "kunne du tenke deg å komme?", phonetic: "ty æmræ vənir" },
      { fr: "il faudrait boire de l'eau", no: "man burde drikke vann", phonetic: "il fodræ bwar də lo" },
      { fr: "si j'avais le temps...", no: "hvis jeg hadde tid...", phonetic: "si sjavæ lə tå" },
      { fr: "vous voudriez du vin?", no: "ønsker dere vin?", phonetic: "vu vudrijæ dy væn" },
    ],
  },
  {
    id: "pronoms-relatifs",
    title: "Relativpronomen — qui, que, dont, où",
    subtitle: "Å binde setninger sammen",
    description: "Qui = som (subjekt). Que = som (objekt). Dont = som / hvis / av/om hvem. Où = der / hvor. De binder to setninger til én og unngår gjentakelse.",
    pairs: [
      { fr: "c'est l'homme qui parle", no: "det er mannen som snakker", phonetic: "sæ lOm ki parl" },
      { fr: "voilà le livre que j'ai lu", no: "der er boken jeg leste", phonetic: "vwala lə livr kə sjæ ly" },
      { fr: "Paris est la ville où j'habite", no: "Paris er byen jeg bor i", phonetic: "pari æ la vil u sjabit" },
      { fr: "c'est le livre dont je parle", no: "det er boken jeg snakker om", phonetic: "sæ lə livr dån sjø parl" },
      { fr: "l'artiste dont je parle", no: "kunstneren jeg snakker om", phonetic: "lartist dån sjø parl" },
      { fr: "la femme qui est venue", no: "kvinnen som kom", phonetic: "la fam ki æ vəny" },
      { fr: "le café que tu aimes", no: "kaféen du liker", phonetic: "lə kafæ kə ty æm" },
    ],
  },
  // --- Fase 4: Litterær inngang ---
  {
    id: "comparatif",
    title: "Komparativ og superlativ",
    subtitle: "Mer, mindre, best",
    description: "Komparativ: plus + adj + que (mer enn), moins + adj + que (mindre enn), aussi + adj + que (like). Superlativ: le/la/les plus + adj (den/det mest).",
    pairs: [
      { fr: "le café est plus grand que le restaurant", no: "kaféen er større enn restauranten", phonetic: "lə kafæ æ ply grå kə lə restårå" },
      { fr: "il parle moins souvent que moi", no: "han snakker sjeldnere enn meg", phonetic: "il parl mwæn suvå kə mwa" },
      { fr: "c'est le meilleur café", no: "det er den beste kaféen", phonetic: "sæ lə mæjœr kafæ" },
      { fr: "il est aussi grand que moi", no: "han er like stor som meg", phonetic: "il æ osi grå kə mwa" },
      { fr: "c'est la plus belle ville", no: "det er den vakreste byen", phonetic: "sæ la ply bæl vil" },
      { fr: "je lis moins souvent qu'hier", no: "jeg leser sjeldnere enn i går", phonetic: "sjø li mwæn suvå kjær" },
      { fr: "c'est le plus beau", no: "det er det vakreste", phonetic: "sæ lə ply bo" },
    ],
  },
  {
    id: "gerondif",
    title: "Gérondif — en + participe présent",
    subtitle: "Samtidige handlinger",
    description: "Gérondif dannes med en + verb-stamme + -ant. Tilsvarer norsk 'mens jeg...' eller 'ved å...'. Brukes mye i literær og muntlig fransk.",
    pairs: [
      { fr: "en lisant", no: "mens jeg leser / ved å lese", phonetic: "å lizå" },
      { fr: "en mangeant", no: "mens jeg spiser / ved å spise", phonetic: "å månsjå" },
      { fr: "en écrivant", no: "mens jeg skriver / ved å skrive", phonetic: "å nekrivå" },
      { fr: "en buvant du vin", no: "mens han drikker vin", phonetic: "å byvå dy væn" },
      { fr: "elle lit en mangeant", no: "hun leser mens hun spiser", phonetic: "æl li å månsjå" },
      { fr: "j'aime écrire en buvant du café", no: "jeg liker å skrive mens jeg drikker kaffe", phonetic: "sjæm ekrir å byvå dy kafæ" },
      { fr: "tout en parlant", no: "mens han/hun snakket", phonetic: "tu tå parlå" },
    ],
  },
  // --- Fase 5: Avansert ---
  {
    id: "subjonctif",
    title: "Subjonktiv — il faut que...",
    subtitle: "Nødvendighet og følelser",
    description: "Subjonktiv brukes etter uttrykk for nødvendighet, ønsker og følelser. Triggere: il faut que, je veux que, bien que, avant que. Kjennetegn: -e, -es, -e, -ions, -iez, -ent.",
    pairs: [
      { fr: "il faut que tu viennes", no: "du må komme", phonetic: "il fo kə ty vjæn" },
      { fr: "je veux que tu viennes aussi", no: "jeg vil at du også skal komme", phonetic: "sjø vø kə ty vjæn osi" },
      { fr: "il est important que vous parliez", no: "det er viktig at dere snakker", phonetic: "il æ æmpOrtå kə vu parljæ" },
      { fr: "bien qu'il soit simple", no: "selv om det er enkelt", phonetic: "bjæn kil swa sæmpl" },
      { fr: "j'aime que tu sois là", no: "jeg er glad for at du er her", phonetic: "sjæm kə ty swa la" },
      { fr: "avant que tu viennes", no: "før du kommer", phonetic: "avå kə ty vjæn" },
      { fr: "il faut que nous parlions", no: "vi må snakke", phonetic: "il fo kə nu parljån" },
    ],
  },
  {
    id: "voix-passive",
    title: "Passiv — être + participe passé",
    subtitle: "Når noe skjer med noe",
    description: "Passiv dannes med être + perfektum partisipp. Partisippen bøyes etter subjektets kjønn og tall. Tilsvarer norsk 'bli' eller 'ble'.",
    pairs: [
      { fr: "le tableau est peint", no: "maleriet er malt", phonetic: "lə tablo æ pæn" },
      { fr: "le livre a été écrit", no: "boken ble skrevet", phonetic: "lə livr a etæ ekri" },
      { fr: "le livre est écrit par Houellebecq", no: "boken er skrevet av Houellebecq", phonetic: "lə livr æ ekri par wælbæk" },
      { fr: "le livre a été lu", no: "boken ble lest", phonetic: "lə livr a etæ ly" },
      { fr: "le livre est lu dans le monde", no: "boken leses i hele verden", phonetic: "lə livr æ ly då lə månd" },
      { fr: "le livre a été écrit à Paris", no: "boken ble skrevet i Paris", phonetic: "lə livr a etæ ekri a pari" },
      { fr: "le livre sera lu demain", no: "boken vil bli lest i morgen", phonetic: "lə livr sra ly dəmæn" },
    ],
  },
];

export const EXIT_PHRASES = [
  "Er du sikker på at du vil avslutte?",
  "Êtes-vous sûr de vouloir quitter?",
  "Allerede ferdig for i dag?",
  "Déjà fini pour aujourd'hui?",
  "Vil du virkelig forlate Pierre?",
  "Vous voulez vraiment quitter Pierre?",
  "Vi savner deg allerede!",
  "On va vous manquer!",
  "Husker du at du skal lese Houellebecq på fransk én dag?",
  "N'oubliez pas — Houellebecq vous attend en français!",
  "Sikker? Du var så nær fremgang!",
  "Sûr? Vous étiez si proche du progrès!",
  "Et lite franskord til før du går?",
  "Encore un petit mot français avant de partir?",
  "Au revoir betyr ikke for alltid.",
  "Au revoir ne veut pas dire pour toujours.",
  "Ta gjerne med deg noen franske ord ut i verden!",
  "Emportez quelques mots français dans le monde!",
  "Kom tilbake snart — Pierre venter.",
  "Revenez vite — Pierre vous attend.",
];

export const MODES = [
  { id: "dagens-glose", label: "Dagens øvelse – glose", icon: "◆", desc: "5 nye ord daglig" },
  { id: "glose", label: "Gloseøvelse", icon: "◈", desc: "Øv på alle ordene dine" },
  { id: "dagens-grammatikk", label: "Daglig grammatikk", icon: "◑", desc: "Ny grammatikkregel per dag" },
  { id: "grammatikk-ovelse", label: "Grammatikkøvelse", icon: "◐", desc: "Repeter lærte grammatikkregler" },
  { id: "teksthjelp", label: "Teksthjelp", icon: "◫", desc: "Lim inn tekst på fransk" },
  { id: "fri", label: "Spør fritt", icon: "✦", desc: "Still spørsmål om fransk" },
];

export const STARTER = {
  teksthjelp: "Lim inn en setning eller lengre tekst på fransk — jeg tilpasser meg automatisk.\n\nDu kan også velge en setning fra bøkene dine nedenfor.",
  fri: "Hva lurer du på om fransk? Du kan også skrive «Pierre» hvis du vil øve med en virtuell franskmann.",
};

export const CHAT_MODES = ["teksthjelp", "fri"];

export const MASTERY_LABELS = ["ikke lært", "kjennskap", "bekjent", "lært", "godt lært", "mestret"];
export const MASTERY_COLORS = [
  "rgba(26,18,16,0.25)",
  "#c8783a",
  "#c8a03a",
  "#7ab050",
  "#3a8a50",
  "#1a7a38",
];

export const SR_INTERVALS = [1, 2, 4, 8, 16, 32];

export const MASTERY_POINTS = 20;
export const MASTERY_PAUSE_MIN = 20;
export const MASTERY_PAUSE_MAX = 40;

export const ORDMESTER_GOALS = [
  { target: 150, reward: "Vinylplate" },
  { target: 300, reward: "Vinylplate" },
  { target: 450, reward: "Vinylplate" },
  { target: 600, reward: "Vinylplate" },
  { target: 750, reward: "Tur til Frankrike" },
];

export const VOCAB_GOALS = [
  // --- Fase 1: Grunnmur (0–800) ---
  { id: "core",       label: "Grunnleggende fransk",          desc: "Funksjonsord, pronomen, kjerneverb og basissubstantiv",                target: 400 },
  { id: "everyday",  label: "Hverdagssituasjoner",            desc: "Bestilling av mat og drikke på restaurant, café og bar",               target: 200 },
  { id: "tdf",       label: "Tour de France",                 desc: "Etapper, felt, tid og avstand – lukket domene",                        target: 200 },
  // --- Fase 2: Utvidelse av hverdagsfransk (800–1 950) ---
  { id: "senses",    label: "Beskrivelse, rom og sanser",     desc: "Farger, lys, former, rom og sanselig beskrivelse",                     target: 120 },
  { id: "food",      label: "Mat, drikke og matlaging",       desc: "Råvarer, tilberedning, smak og fransk kjøkken",                        target: 200 },
  { id: "body",      label: "Kropp, helse og rutine",         desc: "Kroppsdeler, symptomer, daglige rutiner og medisin",                   target: 150 },
  { id: "family",    label: "Familie og relasjoner",          desc: "Familiemedlemmer, vennskap, hjemmeliv og følelser mellom folk",        target: 150 },
  { id: "travel",    label: "Feriereiser og transport",       desc: "Reise, hotell, flyplass, tog og å finne veien",                        target: 180 },
  { id: "core2",     label: "Grunnleggende fransk — avansert",desc: "Mer nyanserte bindeord, preposisjoner og frekvente verb",              target: 150 },
  { id: "geo",       label: "Geografi og natur",              desc: "Land, landskap, vær, klima og Frankrikes regioner",                    target: 200 },
  // --- Fase 3: Mellomtrinn – samfunn og kultur (1 950–3 400) ---
  { id: "everyday2", label: "Hverdagssituasjoner — avansert", desc: "Shopping, bank, lege, apotek og mer komplekse situasjoner",            target: 150 },
  { id: "identity",  label: "Følelser og identitet",          desc: "Indre liv, personlighetstrekk, selvbeskrivelse og relasjoner",         target: 170 },
  { id: "popculture",label: "Populærkultur og underholdning", desc: "Musikk, film, TV, idrett, sosiale medier og mote",                    target: 200 },
  { id: "history",   label: "Historie",                       desc: "Revolusjon, verdenskrigene, de fem republikkene og sentrale hendelser", target: 230 },
  { id: "arts",      label: "Kunst og kulturliv",             desc: "Kunstretninger, musikk, litteratur, teater, kino og museer",           target: 200 },
  { id: "politics",  label: "Det politiske system",           desc: "Statsapparat, partier, valg og demokratiske institusjoner",            target: 200 },
  { id: "tdf2",      label: "Tour de France — avansert",      desc: "Taktikk, lagdynamikk, fjell og sendetekst i detalj",                  target: 150 },
  { id: "gastro",    label: "Matlaging og gastronomi — avansert", desc: "Fransk gastronomi, vin, regionale spesialiteter og finmat",        target: 150 },
  // --- Fase 4: Litterær inngang (3 400–4 650) ---
  { id: "prose1",    label: "Litterær prosa — nivå 1",        desc: "Litterære bindeord, fortidsformer i tekst og beskrivende prosa",       target: 200 },
  { id: "work",      label: "Fag, yrker og arbeidsliv",       desc: "Profesjoner, arbeidsplass, utdanning og fagspråk",                    target: 200 },
  { id: "abstract",  label: "Abstrakt og filosofisk",         desc: "Årsak, konsekvens, tvil, ironi og abstrakte substantiv",               target: 150 },
  { id: "geo2",      label: "Geografi — avansert",            desc: "Frankrikes regioner i dybden, oversjøiske territorier og Europa",     target: 200 },
  { id: "body2",     label: "Kropp og helse — avansert",      desc: "Medisinske konsultasjoner, psykisk helse og kroppssystemer",          target: 150 },
  { id: "popculture2",label:"Populærkultur — avansert",       desc: "Filmanalyse, musikkritikk og internetkultur på fransk",               target: 200 },
  { id: "everyday3", label: "Hverdagssituasjoner — avansert 2",desc: "Juridiske forhold, kontrakter, forsikring og formelle situasjoner",  target: 150 },
  // --- Fase 5: Avansert kulturforståelse (4 650–6 050) ---
  { id: "prose2",    label: "Litterær prosa — nivå 2",        desc: "Houellebecqs register: fremmedgjøring, kropp og moderne Frankrike",    target: 250 },
  { id: "history2",  label: "Historie — avansert",            desc: "Historiografi, kollektiv hukommelse og commemorasjon",                target: 200 },
  { id: "politics2", label: "Det politiske system — avansert",desc: "Politisk debattspråk, medier, journalistikk og kommentar",            target: 200 },
  { id: "aesthetics",label: "Beskrivelse og estetikk — avansert", desc: "Kunstbeskrivelse, estetisk vurdering, stil og arkitektur",        target: 150 },
  { id: "paris1920", label: "Paris 1920 — kunst og modernitet",desc: "Avantgarde, surrealisme, dadaisme og kunsthistorisk terminologi",    target: 200 },
  { id: "nature",    label: "Natur, miljø og vitenskap",      desc: "Miljø, klimaendringer, biologi, kjemi og vitenskapsspråk",            target: 200 },
  { id: "core3",     label: "Grunnleggende fransk — avansert 2", desc: "Idiomer, kollokasjoner og register – formelt vs. uformelt",        target: 200 },
  // --- Fase 6: Ekspertnivå og direkte lesing (6 050–8 000) ---
  { id: "medicine",  label: "Medisin og psykologi",           desc: "Psykiatri, farmakologi og biologisk vokabular til Sérotonine",        target: 200 },
  { id: "philosophy",label: "Filosofi og samfunn",            desc: "Eksistensialisme, sosiologi og franske filosofiske begreper",         target: 250 },
  { id: "gastro2",   label: "Mat og vin — ekspert",           desc: "Sommeliervokabular, ost, regionale retter og kulinarisk kritikk",     target: 200 },
  { id: "prose3",    label: "Litterær prosa — nivå 3",        desc: "Komplekse litterære grep, intertekstualitet, metafor og retorikk",    target: 250 },
  { id: "tdf3",      label: "Tour de France — ekspert",       desc: "Historiske TdF-referanser, sykkelkultur og kjendisvokabular",         target: 150 },
  { id: "houellebecq",label:"Houellebecq — direkte lesing",   desc: "Sérotonines spesifikke vokabular: depresjon, ironi og samtids-Frankrike", target: 300 },
  { id: "paris_adv", label: "Paris kulturliv — direkte lesing",desc: "Kunsthistorisk og kulturkritisk vokabular fra 1920-boken",          target: 250 },
  { id: "free",      label: "Avansert lesing og fri forståelse",desc: "Avisspråk, kompleks argumentasjon og nær-innfødt leseforståelse",   target: 350 },
];

export const WORDS_KEY = "fransk-laering-ord-v2";
export const GRAMMAR_WORDS_KEY = "fransk-grammar-words";
export const GRAMMAR_PROGRESS_KEY = "fransk-grammar-progress";
export const STREAK_KEY = "fransk-streak";
export const BEST_STREAK_KEY = "fransk-best-streak";
export const DAGENS_GLOSE_KEY = "fransk-dagens-glose";
export const SESSION_KEY = "fransk-session-msgs";
export const SESSION_SCREEN_KEY = "fransk-session-screen";
export const ANSWER_COUNT_KEY = "fransk-global-answer-count";
export const GENERATED_VOCAB_KEY = "fransk-generated-vocab";

export const gold = "#c8783a";
export const dark = "#f5f0e6";
export const cream = "#1a1210";
export const card = "#ffffff";
export const brd = "rgba(0,0,0,0.09)";
export const grn = "#3a8a50";
export const red = "#c83a3a";
