// Auto-generated: German (de-CH) target word -> Norwegian category name.
// Built by position-joining de_static_vocab against French static_vocab
// (shared Norwegian gloss + order) and reading each French word's category
// from VOCAB_CAT_MAP in constants.js. Regenerate from source; do not hand-edit.
// HARD RULE: never the ss-ligature in German strings.

export const DE_VOCAB_CAT_MAP = {
  // Hilsener og høflighet
  "natürlich": "Hilsener og høflighet", "einverstanden": "Hilsener og høflighet",
  "bitte": "Hilsener og høflighet", "Merci": "Hilsener og høflighet",
  "bitte sehr": "Hilsener og høflighet", "Entschuldigung Sie": "Hilsener og høflighet",
  "Entschuldigung": "Hilsener og høflighet", "Grüezi": "Hilsener og høflighet",
  "Guten Abend": "Hilsener og høflighet", "Gute Nacht": "Hilsener og høflighet",
  "Auf Wiedersehen": "Hilsener og høflighet", "Hoi": "Hilsener og høflighet",
  "es geht": "Hilsener og høflighet", "da ist es": "Hilsener og høflighet",
  // Pronomen
  "nichts": "Pronomen", "jemand": "Pronomen", "etwas": "Pronomen", "alle": "Pronomen",
  "ich": "Pronomen", "du": "Pronomen", "er": "Pronomen", "sie": "Pronomen", "wir": "Pronomen",
  "ihr": "Pronomen", "man": "Pronomen", "mich": "Pronomen",
  // Tallord og mengde
  "wie viel": "Tallord og mengde", "genug": "Tallord og mengde", "wenig": "Tallord og mengde",
  "mehrere": "Tallord og mengde", "jede": "Tallord og mengde", "zusammen": "Tallord og mengde",
  "eins": "Tallord og mengde", "zwei": "Tallord og mengde", "drei": "Tallord og mengde",
  "vier": "Tallord og mengde", "fünf": "Tallord og mengde", "sechs": "Tallord og mengde",
  "sieben": "Tallord og mengde", "acht": "Tallord og mengde", "neun": "Tallord og mengde",
  "zehn": "Tallord og mengde", "vierzehn": "Tallord og mengde", "zwanzig": "Tallord og mengde",
  "hundert": "Tallord og mengde", "tausend": "Tallord og mengde", "erste": "Tallord og mengde",
  "zehnte": "Tallord og mengde",
  // Vanlige verb
  "geben": "Vanlige verb", "nehmen": "Vanlige verb", "setzen": "Vanlige verb",
  "öffnen": "Vanlige verb", "schliessen": "Vanlige verb", "anrufen": "Vanlige verb",
  "anfangen": "Vanlige verb", "fertigmachen": "Vanlige verb", "wohnen": "Vanlige verb",
  "leben": "Vanlige verb", "ändern": "Vanlige verb", "versuchen": "Vanlige verb",
  "helfen": "Vanlige verb", "weitermachen": "Vanlige verb", "tragen": "Vanlige verb",
  "erlauben": "Vanlige verb", "müssen": "Vanlige verb", "sein": "Vanlige verb",
  "haben": "Vanlige verb", "fahren": "Vanlige verb", "machen": "Vanlige verb",
  "kommen": "Vanlige verb", "wollen": "Vanlige verb", "können": "Vanlige verb",
  "sehen": "Vanlige verb", "halten": "Vanlige verb", "zeigen": "Vanlige verb",
  // Bevegelse
  "abreisen": "Bevegelse", "bleiben": "Bevegelse", "ankommen": "Bevegelse",
  "verbringen": "Bevegelse", "gehen": "Bevegelse", "rennen": "Bevegelse",
  "nachhausekommen": "Bevegelse", "rausgehen": "Bevegelse", "hochgehen": "Bevegelse",
  "runtergehen": "Bevegelse", "überqueren": "Bevegelse", "abbiegen": "Bevegelse",
  // Kommunikasjon og tanker
  "verstehen": "Kommunikasjon og tanker", "fragen": "Kommunikasjon og tanker",
  "finden": "Kommunikasjon og tanker", "denken": "Kommunikasjon og tanker",
  "glauben": "Kommunikasjon og tanker", "hören": "Kommunikasjon og tanker",
  "suchen": "Kommunikasjon og tanker", "kennen": "Kommunikasjon og tanker",
  "warten": "Kommunikasjon og tanker", "antworten": "Kommunikasjon og tanker",
  "wirken": "Kommunikasjon og tanker", "Wort": "Kommunikasjon og tanker",
  "Frage": "Kommunikasjon og tanker", "Antwort": "Kommunikasjon og tanker",
  "Problem": "Kommunikasjon og tanker", "wissen": "Kommunikasjon og tanker",
  "lesen": "Kommunikasjon og tanker", "schreiben": "Kommunikasjon og tanker",
  "sprechen": "Kommunikasjon og tanker", "sagen": "Kommunikasjon og tanker",
  "wählen": "Kommunikasjon og tanker", "entscheiden": "Kommunikasjon og tanker",
  "lernen": "Kommunikasjon og tanker", "erklären": "Kommunikasjon og tanker",
  "vergessen": "Kommunikasjon og tanker", "Sprache": "Kommunikasjon og tanker",
  // Følelser og identitet
  "fühlen": "Følelser og identitet", "mögen": "Følelser og identitet",
  "hassen": "Følelser og identitet", "ruhig": "Følelser og identitet",
  "leiden": "Følelser og identitet",
  // Adjektiver
  "gross": "Adjektiver", "klein": "Adjektiver", "gut": "Adjektiver", "schlecht": "Adjektiver",
  "schön": "Adjektiver", "neu": "Adjektiver", "alt": "Adjektiver", "jung": "Adjektiver",
  "stark": "Adjektiver", "schwach": "Adjektiver", "langsam": "Adjektiver",
  "einfach": "Adjektiver", "schwierig": "Adjektiver", "interessant": "Adjektiver",
  "langweilig": "Adjektiver", "zufrieden": "Adjektiver", "traurig": "Adjektiver",
  "müde": "Adjektiver", "krank": "Adjektiver", "sauber": "Adjektiver", "schmutzig": "Adjektiver",
  "voll": "Adjektiver", "leer": "Adjektiver", "allein": "Adjektiver", "wahr": "Adjektiver",
  "falsch": "Adjektiver", "warm": "Adjektiver", "kalt": "Adjektiver", "lang": "Adjektiver",
  "kurz": "Adjektiver", "unhöflich": "Adjektiver", "frei": "Adjektiver", "möglich": "Adjektiver",
  "wichtig": "Adjektiver", "letzt": "Adjektiver", "nächst": "Adjektiver", "gewiss": "Adjektiver",
  "schwer": "Adjektiver", "leicht": "Adjektiver", "bewölkt": "Adjektiver",
  "sonnig": "Adjektiver", "stürmisch": "Adjektiver",
  // Adverb og bindeord
  "schon": "Adverb og bindeord", "noch": "Adverb og bindeord", "während": "Adverb og bindeord",
  "seit": "Adverb og bindeord", "zu viel": "Adverb og bindeord",
  "vielleicht": "Adverb og bindeord", "zuerst": "Adverb og bindeord",
  "dann": "Adverb og bindeord", "schliesslich": "Adverb og bindeord",
  "also": "Adverb og bindeord", "wann": "Adverb og bindeord", "wie": "Adverb og bindeord",
  "warum": "Adverb og bindeord", "weil": "Adverb og bindeord", "vor allem": "Adverb og bindeord",
  "trotzdem": "Adverb og bindeord", "eigentlich": "Adverb og bindeord",
  "dennoch": "Adverb og bindeord", "gemäss": "Adverb og bindeord", "bis": "Adverb og bindeord",
  "und": "Adverb og bindeord", "oder": "Adverb og bindeord", "aber": "Adverb og bindeord",
  "denn": "Adverb og bindeord", "wenn": "Adverb og bindeord", "sofort": "Adverb og bindeord",
  "wirklich": "Adverb og bindeord",
  // Tid og frekvens
  "Woche": "Tid og frekvens", "Monat": "Tid og frekvens", "Frühling": "Tid og frekvens",
  "Sommer": "Tid og frekvens", "Herbst": "Tid og frekvens", "Winter": "Tid og frekvens",
  "schnell": "Tid og frekvens", "jetzt": "Tid og frekvens", "immer": "Tid og frekvens",
  "nie": "Tid og frekvens", "oft": "Tid og frekvens", "manchmal": "Tid og frekvens",
  "früh": "Tid og frekvens", "spät": "Tid og frekvens", "bald": "Tid og frekvens",
  "gestern": "Tid og frekvens", "morgen": "Tid og frekvens", "Montag": "Tid og frekvens",
  "Dienstag": "Tid og frekvens", "Mittwoch": "Tid og frekvens", "Donnerstag": "Tid og frekvens",
  "Freitag": "Tid og frekvens", "Samstag": "Tid og frekvens", "Sonntag": "Tid og frekvens",
  "Januar": "Tid og frekvens", "Februar": "Tid og frekvens", "März": "Tid og frekvens",
  "April": "Tid og frekvens", "Mai": "Tid og frekvens", "Juni": "Tid og frekvens",
  "Juli": "Tid og frekvens", "August": "Tid og frekvens", "September": "Tid og frekvens",
  "Oktober": "Tid og frekvens", "November": "Tid og frekvens", "Dezember": "Tid og frekvens",
  "Stunde": "Tid og frekvens", "Minute": "Tid og frekvens", "Sekunde": "Tid og frekvens",
  "Morgen": "Tid og frekvens", "Abend": "Tid og frekvens", "Nacht": "Tid og frekvens",
  "heute": "Tid og frekvens", "Tag": "Tid og frekvens", "Jahr": "Tid og frekvens",
  "Zeit": "Tid og frekvens",
  // Steder – Paris
  "Museum": "Steder – Paris", "Quartier": "Steder – Paris", "Bäckerei": "Steder – Paris",
  "Champs-Élysées": "Steder – Paris",
  // Steder og rom
  "Stadt": "Steder og rom", "Strasse": "Steder og rom", "Bahnhof": "Steder og rom",
  "Bibliothek": "Steder og rom", "Weg": "Steder og rom", "Gebäude": "Steder og rom",
  "hoch": "Steder og rom", "niedrig": "Steder og rom", "zwischen": "Steder og rom",
  "Restaurant": "Steder og rom", "Supermarkt": "Steder og rom", "Apotheke": "Steder og rom",
  "Post": "Steder og rom", "hinter": "Steder og rom", "vor": "Steder og rom",
  "Gemeindehaus": "Steder og rom", "Hotel": "Steder og rom",
  // Familie og relasjoner
  "Mann": "Familie og relasjoner", "Frau": "Familie og relasjoner",
  "Kind": "Familie og relasjoner", "Junge": "Familie og relasjoner",
  "Mädchen": "Familie og relasjoner", "Baby": "Familie og relasjoner",
  "Freund": "Familie og relasjoner", "Freundin": "Familie og relasjoner",
  "Leute": "Familie og relasjoner", "Nachbar": "Familie og relasjoner",
  "Nachbarin": "Familie og relasjoner",
  // Kropp og helse
  "essen": "Kropp og helse", "trinken": "Kropp og helse", "schlafen": "Kropp og helse",
  "aufstehen": "Kropp og helse", "sich waschen": "Kropp og helse",
  "schlafen gehen": "Kropp og helse", "Spital": "Kropp og helse",
  // Klær og utseende
  "Regenmantel": "Klær og utseende",
  // Mat og drikke
  "Café": "Mat og drikke", "Rechnung": "Mat og drikke", "Vorspeise": "Mat og drikke",
  "Dessert": "Mat og drikke", "Zmorge": "Mat og drikke", "Zmittag": "Mat og drikke",
  "Znacht": "Mat og drikke",
  // Hjem og hverdagsliv
  "Haus": "Hjem og hverdagsliv", "Garten": "Hjem og hverdagsliv",
  "Wohnung": "Hjem og hverdagsliv", "Zimmer": "Hjem og hverdagsliv",
  "Küche": "Hjem og hverdagsliv", "Wohnzimmer": "Hjem og hverdagsliv",
  "Fenster": "Hjem og hverdagsliv", "Tür": "Hjem og hverdagsliv", "Stuhl": "Hjem og hverdagsliv",
  "Tisch": "Hjem og hverdagsliv", "Bett": "Hjem og hverdagsliv",
  "Schlüssel": "Hjem og hverdagsliv", "Licht": "Hjem og hverdagsliv",
  "Lärm": "Hjem og hverdagsliv", "Natel": "Hjem og hverdagsliv",
  "Computer": "Hjem og hverdagsliv", "Korridor": "Hjem og hverdagsliv",
  "Miete": "Hjem og hverdagsliv",
  // Shopping og tjenester
  "kaufen": "Shopping og tjenester", "Geld": "Shopping og tjenester",
  "Laden": "Shopping og tjenester", "Tasche": "Shopping og tjenester",
  "teuer": "Shopping og tjenester", "Speisekarte": "Shopping og tjenester",
  "bezahlen": "Shopping og tjenester", "Bank": "Shopping og tjenester",
  "Preis": "Shopping og tjenester", "günstig": "Shopping og tjenester",
  "Grösse": "Shopping og tjenester", "Ausverkauf": "Shopping og tjenester",
  "Markt": "Shopping og tjenester", "gratis": "Shopping og tjenester",
  // Transport og reiser
  "Auto": "Transport og reiser", "Zug": "Transport og reiser", "Bus": "Transport og reiser",
  "Flugzeug": "Transport og reiser", "Boot": "Transport og reiser",
  "U-Bahn": "Transport og reiser", "Taxi": "Transport og reiser",
  "Billett": "Transport og reiser", "Perron": "Transport og reiser",
  "Fahrplan": "Transport og reiser", "Verspätung": "Transport og reiser",
  "Anschluss": "Transport og reiser", "Koffer": "Transport og reiser",
  "Flughafen": "Transport og reiser", "Hin- und Rückfahrt": "Transport og reiser",
  "Velo": "Transport og reiser", "Start": "Transport og reiser", "Ziel": "Transport og reiser",
  // Natur og vær
  "Sonne": "Natur og vær", "Mond": "Natur og vær", "Himmel": "Natur og vær",
  "Wolke": "Natur og vær", "Wind": "Natur og vær", "Regen": "Natur og vær",
  "Schnee": "Natur og vær", "Meer": "Natur og vær", "Fluss": "Natur og vær",
  "Wald": "Natur og vær", "Baum": "Natur og vær", "Blume": "Natur og vær",
  "Berg": "Natur og vær", "Anstieg": "Natur og vær",
  // Land og geografi
  "Land": "Land og geografi", "Welt": "Land og geografi",
  // Kunst og kultur
  "Buch": "Kunst og kultur", "Kino": "Kunst og kultur", "Jahrhundert": "Kunst og kultur",
  "Publikum": "Kunst og kultur",
  // Sport og fritid
  "spielen": "Sport og fritid", "verlieren": "Sport og fritid", "gewinnen": "Sport og fritid",
  "Mannschaft": "Sport og fritid", "Champion": "Sport og fritid",
  "Championin": "Sport og fritid", "Sieg": "Sport og fritid",
  // Tour de France
  "Pass": "Tour de France", "Zähler": "Tour de France", "Peloton": "Tour de France",
  "Etappe": "Tour de France", "Sprint": "Tour de France", "Angriff": "Tour de France",
  "angreifen": "Tour de France", "Ausreissen": "Tour de France", "Klassement": "Tour de France",
  "Kletterer": "Tour de France", "sprinten": "Tour de France", "Flachfahrer": "Tour de France",
  "Helfer": "Tour de France", "Domestique": "Tour de France", "Kapitän": "Tour de France",
  "Leader": "Tour de France", "Fahrer": "Tour de France", "Radfahrer": "Tour de France",
  "Sportdirektor": "Tour de France", "Kommissär": "Tour de France", "Betreuer": "Tour de France",
  "Mechaniker": "Tour de France", "Sieger": "Tour de France", "Lenker": "Tour de France",
  "Sattel": "Tour de France", "Rad": "Tour de France", "Kette": "Tour de France",
  "Schaltwerk": "Tour de France", "Pedal": "Tour de France", "Bremse": "Tour de France",
  "Helm": "Tour de France", "Trikot": "Tour de France", "Radhose": "Tour de France",
  "Trinkflasche": "Tour de France", "Satteltasche": "Tour de France", "Tacho": "Tour de France",
  "Ohrhörer": "Tour de France", "Gelbes Trikot": "Tour de France",
  "Grünes Trikot": "Tour de France", "Gepunktetes Trikot": "Tour de France",
  "Weisses Trikot": "Tour de France", "Zeitfahren": "Tour de France",
  "Auffahrt": "Tour de France", "Abfahrt": "Tour de France",
  "Ausreissergruppe": "Tour de France", "Aufgabe": "Tour de France",
  "Verpflegung": "Tour de France", "Podium": "Tour de France",
  "Tour de France": "Tour de France", "Pyrenäen": "Tour de France", "Alpen": "Tour de France",
  "Puncheur": "Tour de France", "Abenteurer": "Tour de France",
  // Utdanning og arbeid
  "arbeiten": "Utdanning og arbeid", "Arbeit": "Utdanning og arbeid",
  "Schule": "Utdanning og arbeid", "Büro": "Utdanning og arbeid",
  "Lehrer": "Utdanning og arbeid", "Arzt": "Utdanning og arbeid",
  // Samfunn og politikk
  "Geschichte": "Samfunn og politikk",
};
