export const STATIC_VOCAB = {
  core: [
    { fr: "comprendre", no: "å forstå", phonetic: "kåpråndər" },
    { fr: "demander", no: "å spørre / å be om", phonetic: "dəmådæ" },
    { fr: "donner", no: "å gi", phonetic: "donæ" },
    { fr: "prendre", no: "å ta", phonetic: "pråndrə" },
    { fr: "mettre", no: "å sette / å legge", phonetic: "mætrə" },
    { fr: "partir", no: "å dra / å reise", phonetic: "partir" },
    { fr: "trouver", no: "å finne", phonetic: "truvæ" },
    { fr: "penser", no: "å tenke", phonetic: "påsæ" },
    { fr: "croire", no: "å tro", phonetic: "krwar" },
    { fr: "sentir", no: "å kjenne / å lukte", phonetic: "såtir" },
    { fr: "entendre", no: "å høre", phonetic: "åtåndrə" },
    { fr: "rester", no: "å bli / å forbli", phonetic: "ræstæ" },
    { fr: "arriver", no: "å ankomme / å komme", phonetic: "arivæ" },
    { fr: "passer", no: "å passere / å tilbringe", phonetic: "pasæ" },
    { fr: "jouer", no: "å spille / å leke", phonetic: "sjuæ" },
    { fr: "travailler", no: "å jobbe / å arbeide", phonetic: "travajæ" },
    { fr: "chercher", no: "å lete etter / å søke", phonetic: "sjærsjæ" },
    { fr: "acheter", no: "å kjøpe", phonetic: "asjøtæ" },
    { fr: "ouvrir", no: "å åpne", phonetic: "uvrir" },
    { fr: "fermer", no: "å lukke / å stenge", phonetic: "færmæ" },
    { fr: "connaître", no: "å kjenne (noen/noe)", phonetic: "konætrə" },
    { fr: "appeler", no: "å ringe / å kalle", phonetic: "aplæ" },
    { fr: "attendre", no: "å vente", phonetic: "atåndrə" },
    { fr: "commencer", no: "å begynne", phonetic: "komsæ" },
    { fr: "finir", no: "å avslutte / å fullføre", phonetic: "finir" },
    { fr: "habiter", no: "å bo", phonetic: "abitæ" },
    { fr: "vivre", no: "å leve", phonetic: "vivrə" },
    { fr: "changer", no: "å endre / å bytte", phonetic: "sjåsjæ" },
    { fr: "essayer", no: "å prøve", phonetic: "æsæjæ" },
    { fr: "répondre", no: "å svare", phonetic: "repåndrə" },
    { fr: "perdre", no: "å miste / å tape", phonetic: "pærdrə" },
    { fr: "gagner", no: "å vinne / å tjene", phonetic: "ganjæ" },
    { fr: "aider", no: "å hjelpe", phonetic: "ædæ" },
    { fr: "continuer", no: "å fortsette", phonetic: "kåtinuæ" },
    { fr: "porter", no: "å bære / å ha på seg", phonetic: "portæ" },
    { fr: "marcher", no: "å gå / å fungere", phonetic: "marsjæ" },
    { fr: "courir", no: "å løpe", phonetic: "kurir" },
    { fr: "rentrer", no: "å komme hjem / å returnere", phonetic: "råtræ" },
    { fr: "sortir", no: "å gå ut", phonetic: "sortir" },
    { fr: "monter", no: "å gå opp / å stige", phonetic: "måtæ" },
    { fr: "descendre", no: "å gå ned", phonetic: "desåndrə" },
    { fr: "sembler", no: "å virke / å synes", phonetic: "såblæ" },
    { fr: "permettre", no: "å tillate", phonetic: "pærmætrə" },
    { fr: "devoir", no: "å måtte / å skylde", phonetic: "dəvwar" },
    { fr: "la maison", no: "huset", phonetic: "la mæzå" },
    { fr: "le livre", no: "boken", phonetic: "lə livrə" },
    { fr: "la voiture", no: "bilen", phonetic: "la vwatyr" },
    { fr: "l'argent", no: "pengene / sølv", phonetic: "larsjå" },
    { fr: "le travail", no: "arbeidet / jobben", phonetic: "lə travaj" },
    { fr: "la ville", no: "byen", phonetic: "la vil" },
    { fr: "le pays", no: "landet", phonetic: "lə pæi" },
    { fr: "la rue", no: "gaten", phonetic: "la ry" },
    { fr: "la gare", no: "togstasjonen", phonetic: "la gar" },
    { fr: "l'école", no: "skolen", phonetic: "lekol" },
    { fr: "la bibliothèque", no: "biblioteket", phonetic: "la biblijotek" },
    { fr: "le musée", no: "museet", phonetic: "lə myzæ" },
    { fr: "le cinéma", no: "kinoen", phonetic: "lə sinema" },
    { fr: "le jardin", no: "hagen", phonetic: "lə sjardæn" },
    { fr: "le magasin", no: "butikken", phonetic: "lə magazæn" },
    { fr: "le bureau", no: "kontoret / skrivebordet", phonetic: "lə byro" },
    { fr: "l'appartement", no: "leiligheten", phonetic: "lapartəmå" },
    { fr: "la chambre", no: "soverommet", phonetic: "la sjåbrə" },
    { fr: "la cuisine", no: "kjøkkenet", phonetic: "la kwizin" },
    { fr: "le salon", no: "stuen", phonetic: "lə salå" },
    { fr: "la fenêtre", no: "vinduet", phonetic: "la fənætrə" },
    { fr: "la porte", no: "døren", phonetic: "la port" },
    { fr: "la chaise", no: "stolen", phonetic: "la sjæz" },
    { fr: "la table", no: "bordet", phonetic: "la tablə" },
    { fr: "le lit", no: "sengen", phonetic: "lə li" },
    { fr: "le chemin", no: "veien / stien", phonetic: "lə sjəmæn" },
    { fr: "la clé", no: "nøkkelen", phonetic: "la klæ" },
    { fr: "le sac", no: "vesken / sekken", phonetic: "lə sak" },
    { fr: "le mot", no: "ordet", phonetic: "lə mo" },
    { fr: "la question", no: "spørsmålet", phonetic: "la kæstjå" },
    { fr: "la réponse", no: "svaret", phonetic: "la repås" },
    { fr: "le problème", no: "problemet", phonetic: "lə problæm" },
    { fr: "la lumière", no: "lyset", phonetic: "la lumjær" },
    { fr: "le bruit", no: "støyen / lyden", phonetic: "lə brwi" },
    { fr: "le quartier", no: "bydelen / nabolaget", phonetic: "lə kartjæ" },
    { fr: "le bâtiment", no: "bygningen", phonetic: "lə batimå" },
    { fr: "grand", no: "stor", phonetic: "grå" },
    { fr: "petit", no: "liten", phonetic: "pəti" },
    { fr: "bon", no: "god / bra", phonetic: "bå" },
    { fr: "mauvais", no: "dårlig / slett", phonetic: "movæ" },
    { fr: "beau", no: "vakker / flott", phonetic: "bo" },
    { fr: "nouveau", no: "ny", phonetic: "nuvo" },
    { fr: "vieux", no: "gammel", phonetic: "vjø" },
    { fr: "jeune", no: "ung", phonetic: "sjøn" },
    { fr: "fort", no: "sterk / høy (lyd)", phonetic: "for" },
    { fr: "faible", no: "svak", phonetic: "fæblə" },
    { fr: "lent", no: "sakte / langsom", phonetic: "lå" },
    { fr: "rapide", no: "rask / hurtig", phonetic: "rapid" },
    { fr: "facile", no: "lett / enkel", phonetic: "fasil" },
    { fr: "difficile", no: "vanskelig", phonetic: "difisil" },
    { fr: "intéressant", no: "interessant", phonetic: "æntæresså" },
    { fr: "ennuyeux", no: "kjedelig", phonetic: "ånwijø" },
    { fr: "content", no: "fornøyd / glad", phonetic: "kåtå" },
    { fr: "triste", no: "trist / lei seg", phonetic: "trist" },
    { fr: "fatigué", no: "trøtt", phonetic: "fatigæ" },
    { fr: "malade", no: "syk", phonetic: "malad" },
    { fr: "propre", no: "ren", phonetic: "proprə" },
    { fr: "sale", no: "skitten", phonetic: "sal" },
    { fr: "plein", no: "full", phonetic: "plæn" },
    { fr: "vide", no: "tom", phonetic: "vid" },
    { fr: "seul", no: "alene", phonetic: "søl" },
    { fr: "vrai", no: "sann / ekte", phonetic: "væ" },
    { fr: "faux", no: "falsk / feil", phonetic: "fo" },
    { fr: "maintenant", no: "nå", phonetic: "mæntənå" },
    { fr: "toujours", no: "alltid", phonetic: "tusjur" },
    { fr: "jamais", no: "aldri", phonetic: "sjamæ" },
    { fr: "souvent", no: "ofte", phonetic: "suvå" },
    { fr: "parfois", no: "noen ganger / av og til", phonetic: "parfwa" },
    { fr: "tôt", no: "tidlig", phonetic: "to" },
    { fr: "tard", no: "sent", phonetic: "tar" },
    { fr: "bientôt", no: "snart", phonetic: "bjænto" },
    { fr: "déjà", no: "allerede", phonetic: "dæsja" },
    { fr: "encore", no: "ennå / igjen", phonetic: "åkor" },
    { fr: "pendant", no: "i løpet av / mens", phonetic: "påndå" },
    { fr: "depuis", no: "siden / fra", phonetic: "dəpwi" },
    { fr: "hier", no: "i går", phonetic: "jær" },
    { fr: "demain", no: "i morgen", phonetic: "dəmæn" },
    { fr: "la semaine", no: "uken", phonetic: "la səmæn" },
    { fr: "le mois", no: "måneden", phonetic: "lə mwa" },
    { fr: "le printemps", no: "våren", phonetic: "lə præntå" },
    { fr: "l'été", no: "sommeren", phonetic: "letæ" },
    { fr: "l'automne", no: "høsten", phonetic: "loton" },
    { fr: "l'hiver", no: "vinteren", phonetic: "livær" },
    { fr: "combien", no: "hvor mye / hvor mange", phonetic: "kåbjæn" },
    { fr: "assez", no: "nok / ganske", phonetic: "asæ" },
    { fr: "trop", no: "for mye / altfor", phonetic: "tro" },
    { fr: "peu", no: "lite / litt", phonetic: "pø" },
    { fr: "plusieurs", no: "flere", phonetic: "plyzjør" },
    { fr: "chaque", no: "hver / hvert", phonetic: "sjak" },
    { fr: "rien", no: "ingenting", phonetic: "rjæn" },
    { fr: "quelqu'un", no: "noen (person)", phonetic: "kælkøn" },
    { fr: "quelque chose", no: "noe", phonetic: "kælkə sjoz" },
    { fr: "ensemble", no: "sammen", phonetic: "åsåblə" },
    { fr: "peut-être", no: "kanskje", phonetic: "pøtætrə" },
    { fr: "bien sûr", no: "selvfølgelig", phonetic: "bjæn syr" },
    { fr: "d'abord", no: "først", phonetic: "dabor" },
    { fr: "ensuite", no: "deretter / så", phonetic: "åswit" },
    { fr: "enfin", no: "til slutt / endelig", phonetic: "åfæn" },
    { fr: "donc", no: "altså / derfor", phonetic: "dåk" },
    { fr: "quand", no: "når", phonetic: "kå" },
    { fr: "comment", no: "hvordan", phonetic: "komå" },
    { fr: "pourquoi", no: "hvorfor", phonetic: "purkwa" },
    { fr: "parce que", no: "fordi", phonetic: "parskə" },
    { fr: "tout le monde", no: "alle / alle sammen", phonetic: "tu lə måd" },
    { fr: "surtout", no: "særlig / fremfor alt", phonetic: "syrtu" },
    { fr: "d'accord", no: "greit / enig", phonetic: "dakor" },
    { fr: "quand même", no: "likevel / allikevel", phonetic: "kå mæm" },
    { fr: "en fait", no: "faktisk / egentlig", phonetic: "å fæ" },
    { fr: "pourtant", no: "likevel / men allikevel", phonetic: "purtå" },
    { fr: "donc", no: "altså / derfor", phonetic: "dåk" },
    { fr: "ainsi", no: "slik / på denne måten", phonetic: "æsi" },
  ],
  everyday: [
    { fr: "le restaurant", no: "restauranten", phonetic: "lə ræstorå" },
    { fr: "le café", no: "kafeen", phonetic: "lə kafæ" },
    { fr: "la carte", no: "menyen", phonetic: "la kart" },
    { fr: "l'addition", no: "regningen", phonetic: "ladissjå" },
    { fr: "le serveur", no: "kelneren (mann)", phonetic: "lə særvør" },
    { fr: "la serveuse", no: "kelneren (kvinne)", phonetic: "la særvøz" },
    { fr: "commander", no: "å bestille", phonetic: "komådæ" },
    { fr: "la commande", no: "bestillingen", phonetic: "la komåd" },
    { fr: "le pourboire", no: "drikkepengene", phonetic: "lə purboar" },
    { fr: "payer", no: "å betale", phonetic: "pæjæ" },
    { fr: "une table pour deux", no: "et bord for to", phonetic: "yn tablə pur dø" },
    { fr: "je voudrais", no: "jeg vil gjerne ha", phonetic: "sjə vudræ" },
    { fr: "l'entrée", no: "forretten", phonetic: "låtræ" },
    { fr: "le plat principal", no: "hovedretten", phonetic: "lə pla præsipal" },
    { fr: "le dessert", no: "desserten", phonetic: "lə desær" },
    { fr: "un verre de", no: "et glass", phonetic: "øn vær də" },
    { fr: "une bouteille de", no: "en flaske", phonetic: "yn butæj də" },
    { fr: "sans gluten", no: "glutenfri", phonetic: "så glytæn" },
    { fr: "végétarien", no: "vegetarisk", phonetic: "vesjætarjæn" },
    { fr: "c'est délicieux", no: "det er deilig", phonetic: "sæ delisjø" },
    { fr: "le supermarché", no: "supermarkedet", phonetic: "lə sypærmarsjæ" },
    { fr: "la boulangerie", no: "bakeriet", phonetic: "la bulåsjəri" },
    { fr: "la pharmacie", no: "apoteket", phonetic: "la farmasi" },
    { fr: "la banque", no: "banken", phonetic: "la båk" },
    { fr: "la poste", no: "postkontoret", phonetic: "la post" },
    { fr: "le prix", no: "prisen", phonetic: "lə pri" },
    { fr: "cher", no: "dyr", phonetic: "sjær" },
    { fr: "bon marché", no: "billig", phonetic: "bå marsjæ" },
    { fr: "la taille", no: "størrelsen", phonetic: "la taj" },
    { fr: "la pointure", no: "skostørrelsen", phonetic: "la poanityr" },
    { fr: "le rayon", no: "avdelingen (i butikk)", phonetic: "lə ræjå" },
    { fr: "la caisse", no: "kassen", phonetic: "la kæs" },
    { fr: "le ticket de caisse", no: "kvitteringen", phonetic: "lə tikæ də kæs" },
    { fr: "la réduction", no: "rabatten", phonetic: "la rædykssjå" },
    { fr: "les soldes", no: "salget / utsalg", phonetic: "læ sold" },
    { fr: "à gauche", no: "til venstre", phonetic: "a gosjə" },
    { fr: "à droite", no: "til høyre", phonetic: "a drwat" },
    { fr: "tout droit", no: "rett frem", phonetic: "tu drwa" },
    { fr: "près de", no: "nær / i nærheten av", phonetic: "præ də" },
    { fr: "loin de", no: "langt fra", phonetic: "loæn də" },
    { fr: "à côté de", no: "ved siden av", phonetic: "a kotæ də" },
    { fr: "derrière", no: "bak", phonetic: "dærjær" },
    { fr: "devant", no: "foran", phonetic: "dəvå" },
    { fr: "en face de", no: "overfor / rett overfor", phonetic: "å fas də" },
    { fr: "au coin de", no: "i hjørnet av", phonetic: "o koæn də" },
    { fr: "le carrefour", no: "veikrysset", phonetic: "lə karfur" },
    { fr: "traverser", no: "å krysse", phonetic: "traværsæ" },
    { fr: "continuer jusqu'à", no: "fortsett til", phonetic: "kåtinuæ sjyska" },
    { fr: "tourner", no: "å svinge / å dreie", phonetic: "turnæ" },
    { fr: "le métro", no: "T-banen", phonetic: "lə metro" },
    { fr: "le bus", no: "bussen", phonetic: "lə bys" },
    { fr: "le ticket", no: "billetten", phonetic: "lə tikæ" },
    { fr: "le quai", no: "perrongen", phonetic: "lə kæ" },
    { fr: "l'horaire", no: "ruteplanen", phonetic: "lorær" },
    { fr: "le retard", no: "forsinkelsen", phonetic: "lə rətar" },
    { fr: "en retard", no: "forsinket", phonetic: "å rətar" },
    { fr: "à l'heure", no: "i tide / presis", phonetic: "a lør" },
    { fr: "la correspondance", no: "forbindelsen / byttet", phonetic: "la korəspåds" },
    { fr: "composter", no: "å stemple billetten", phonetic: "kåpostæ" },
    { fr: "la station", no: "stasjonen", phonetic: "la stasjå" },
    { fr: "le tramway", no: "trikken", phonetic: "lə tramwæ" },
    { fr: "le taxi", no: "taxien", phonetic: "lə taksi" },
    { fr: "se réveiller", no: "å våkne", phonetic: "sə revæjæ" },
    { fr: "se lever", no: "å stå opp", phonetic: "sə ləvæ" },
    { fr: "se doucher", no: "å dusje", phonetic: "sə dusjæ" },
    { fr: "se laver", no: "å vaske seg", phonetic: "sə lavæ" },
    { fr: "s'habiller", no: "å kle på seg", phonetic: "sabijæ" },
    { fr: "le petit-déjeuner", no: "frokosten", phonetic: "lə pəti dæsjønæ" },
    { fr: "le déjeuner", no: "lunsjen", phonetic: "lə dæsjønæ" },
    { fr: "le dîner", no: "middagen / kveldsmaten", phonetic: "lə dinæ" },
    { fr: "se coucher", no: "å legge seg", phonetic: "sə kusjæ" },
    { fr: "dormir", no: "å sove", phonetic: "dormir" },
    { fr: "se brosser les dents", no: "å pusse tennene", phonetic: "sə brosæ læ då" },
    { fr: "prendre le bus", no: "ta bussen", phonetic: "pråndrə lə bys" },
    { fr: "rentrer à la maison", no: "gå hjem", phonetic: "råtræ a la mæzå" },
    { fr: "faire la cuisine", no: "å lage mat", phonetic: "fær la kwizin" },
    { fr: "faire les courses", no: "å handle", phonetic: "fær læ kurs" },
    { fr: "Bonjour !", no: "God dag! / Hei!", phonetic: "båsjur" },
    { fr: "Salut !", no: "Hei! (uformelt)", phonetic: "saly" },
    { fr: "Comment allez-vous ?", no: "Hvordan har du det? (formelt)", phonetic: "komå talæ vu" },
    { fr: "Comment ça va ?", no: "Hvordan går det?", phonetic: "komå sa va" },
    { fr: "Ça va bien", no: "Det går bra", phonetic: "sa va bjæn" },
    { fr: "Enchanté(e)", no: "Hyggelig å møte deg", phonetic: "åsjåtæ" },
    { fr: "À bientôt", no: "Vi sees snart", phonetic: "a bjænto" },
    { fr: "À tout à l'heure", no: "Vi sees straks", phonetic: "a tut a lør" },
    { fr: "Allô", no: "Hallo (i telefon)", phonetic: "alo" },
    { fr: "Je vous appelle de la part de", no: "Jeg ringer på vegne av", phonetic: "sjə vu zaplə də la par də" },
    { fr: "Pouvez-vous rappeler ?", no: "Kan du ringe tilbake?", phonetic: "puvæ vu raplæ" },
    { fr: "Ne quittez pas", no: "Ikke legg på / Vent litt", phonetic: "nə kitæ pa" },
    { fr: "zéro", no: "null", phonetic: "zero" },
    { fr: "un", no: "én / ett", phonetic: "øn" },
    { fr: "deux", no: "to", phonetic: "dø" },
    { fr: "trois", no: "tre", phonetic: "trwa" },
    { fr: "quatre", no: "fire", phonetic: "katrə" },
    { fr: "cinq", no: "fem", phonetic: "sænk" },
    { fr: "six", no: "seks", phonetic: "sis" },
    { fr: "sept", no: "syv", phonetic: "sæt" },
    { fr: "huit", no: "åtte", phonetic: "wit" },
    { fr: "neuf", no: "ni", phonetic: "nøf" },
    { fr: "dix", no: "ti", phonetic: "dis" },
    { fr: "vingt", no: "tjue", phonetic: "væn" },
    { fr: "trente", no: "tretti", phonetic: "trå" },
    { fr: "cent", no: "hundre", phonetic: "så" },
    { fr: "mille", no: "tusen", phonetic: "mil" },
    { fr: "Il est quelle heure ?", no: "Hva er klokka?", phonetic: "il æ kæl ør" },
    { fr: "Il est midi", no: "Klokka er tolv (middag)", phonetic: "il æ midi" },
    { fr: "Il est minuit", no: "Klokka er tolv (natt)", phonetic: "il æ minwi" },
    { fr: "le matin", no: "om morgenen", phonetic: "lə matæn" },
    { fr: "l'après-midi", no: "ettermiddagen", phonetic: "lapræ midi" },
    { fr: "le soir", no: "om kvelden", phonetic: "lə swar" },
    { fr: "la nuit", no: "natten", phonetic: "la nwi" },
    { fr: "lundi", no: "mandag", phonetic: "løndi" },
    { fr: "mardi", no: "tirsdag", phonetic: "mardi" },
    { fr: "mercredi", no: "onsdag", phonetic: "mærkredi" },
    { fr: "jeudi", no: "torsdag", phonetic: "sjødi" },
    { fr: "vendredi", no: "fredag", phonetic: "vådrədi" },
    { fr: "samedi", no: "lørdag", phonetic: "samdi" },
    { fr: "dimanche", no: "søndag", phonetic: "dimåsjə" },
    { fr: "janvier", no: "januar", phonetic: "sjåvjæ" },
    { fr: "février", no: "februar", phonetic: "fevrijæ" },
    { fr: "mars", no: "mars", phonetic: "mars" },
    { fr: "avril", no: "april", phonetic: "avril" },
    { fr: "mai", no: "mai", phonetic: "mæ" },
    { fr: "juin", no: "juni", phonetic: "sjwæn" },
    { fr: "juillet", no: "juli", phonetic: "sjwijæ" },
    { fr: "août", no: "august", phonetic: "u" },
    { fr: "septembre", no: "september", phonetic: "sæptåbrə" },
    { fr: "octobre", no: "oktober", phonetic: "oktobrə" },
    { fr: "novembre", no: "november", phonetic: "novåbrə" },
    { fr: "décembre", no: "desember", phonetic: "desåbrə" },
    { fr: "Il fait beau", no: "Det er fint vær", phonetic: "il fæ bo" },
    { fr: "Il pleut", no: "Det regner", phonetic: "il plø" },
    { fr: "Il neige", no: "Det snør", phonetic: "il næsjə" },
    { fr: "Il fait chaud", no: "Det er varmt", phonetic: "il fæ sjo" },
    { fr: "Il fait froid", no: "Det er kaldt", phonetic: "il fæ frwa" },
    { fr: "Il y a du vent", no: "Det blåser", phonetic: "il ja dy vå" },
    { fr: "nuageux", no: "overskyet", phonetic: "nwasjo" },
    { fr: "ensoleillé", no: "solrikt", phonetic: "åsoljæjæ" },
    { fr: "orageux", no: "tordenvær", phonetic: "orasjo" },
    { fr: "la pluie", no: "regnet", phonetic: "la plwi" },
    { fr: "la neige", no: "snøen", phonetic: "la næsjə" },
    { fr: "le soleil", no: "solen", phonetic: "lə solæj" },
    { fr: "la température", no: "temperaturen", phonetic: "la tåpæratyr" },
    { fr: "le parapluie", no: "paraplyen", phonetic: "lə paraplwi" },
    { fr: "l'imperméable", no: "regnfrakken", phonetic: "læpærmeable" },
    { fr: "le marché", no: "torget / markedet", phonetic: "lə marsjæ" },
    { fr: "le centre-ville", no: "bysentrum", phonetic: "lə såtrə vil" },
    { fr: "l'hôpital", no: "sykehuset", phonetic: "lopital" },
    { fr: "la mairie", no: "rådhuset", phonetic: "la mæri" },
    { fr: "la police", no: "politiet", phonetic: "la polis" },
    { fr: "les toilettes", no: "toalettene", phonetic: "læ twalæt" },
    { fr: "l'hôtel", no: "hotellet", phonetic: "lotæl" },
    { fr: "réserver", no: "å reservere / å bestille", phonetic: "rezærvæ" },
    { fr: "une chambre", no: "et rom", phonetic: "yn sjåbrə" },
    { fr: "le passeport", no: "passet", phonetic: "lə paspor" },
    { fr: "la valise", no: "kofferten", phonetic: "la valiz" },
    { fr: "l'aéroport", no: "flyplassen", phonetic: "laeroport" },
    { fr: "le vol", no: "flyturen", phonetic: "lə vol" },
    { fr: "l'avion", no: "flyet", phonetic: "lavjå" },
    { fr: "le train", no: "toget", phonetic: "lə træn" },
    { fr: "le billet", no: "billetten", phonetic: "lə bijæ" },
    { fr: "aller simple", no: "enkeltbillett", phonetic: "alæ sæplə" },
    { fr: "aller-retour", no: "tur-retur billett", phonetic: "alæ rətur" },
    { fr: "la salle d'attente", no: "venterommet", phonetic: "la sal datåt" },
    { fr: "l'office de tourisme", no: "turistkontoret", phonetic: "lofis də turism" },
    { fr: "la carte postale", no: "postkort", phonetic: "la kart postal" },
    { fr: "un timbre", no: "et frimerke", phonetic: "øn tæmbrə" },
    { fr: "envoyer", no: "å sende", phonetic: "åvwajæ" },
    { fr: "la connexion Wi-Fi", no: "Wi-Fi-tilkoblingen", phonetic: "la konækssjå wifi" },
    { fr: "le code", no: "koden", phonetic: "lə kod" },
    { fr: "charger le téléphone", no: "lade telefonen", phonetic: "sjarsjæ lə telefon" },
    { fr: "l'application", no: "appen", phonetic: "laplikassjå" },
    { fr: "gratuit", no: "gratis", phonetic: "gratwi" },
    { fr: "ouvert", no: "åpen", phonetic: "uvær" },
    { fr: "fermé", no: "stengt", phonetic: "færmæ" },
    { fr: "interdit", no: "forbudt", phonetic: "æntærdi" },
    { fr: "obligatoire", no: "obligatorisk / påkrevd", phonetic: "obligatwar" },
    { fr: "l'urgence", no: "nødsituasjonen / akutten", phonetic: "lyrsjås" },
    { fr: "Au secours !", no: "Hjelp!", phonetic: "o səkur" },
    { fr: "J'ai besoin d'aide", no: "Jeg trenger hjelp", phonetic: "sjæ bəzoæn dæd" },
    { fr: "le quartier", no: "bydelen / nabolaget", phonetic: "lə kartjæ" },
    { fr: "l'immeuble", no: "bygningen / boligblokken", phonetic: "limøblə" },
    { fr: "l'ascenseur", no: "heisen", phonetic: "lasåsør" },
    { fr: "le couloir", no: "gangen / korridoren", phonetic: "lə kulwar" },
    { fr: "la clé", no: "nøkkelen", phonetic: "la klæ" },
    { fr: "le loyer", no: "husleien", phonetic: "lə lwajæ" },
    { fr: "emménager", no: "å flytte inn", phonetic: "æmenasje" },
    { fr: "déménager", no: "å flytte ut", phonetic: "demənasjæ" },
    { fr: "le voisin", no: "naboen (mann)", phonetic: "lə vwazæ" },
    { fr: "la voisine", no: "naboen (kvinne)", phonetic: "la vwazin" },
    { fr: "la poubelle", no: "søppelbøtten", phonetic: "la pubæl" },
    { fr: "le courrier", no: "posten / brevet", phonetic: "lə kurjæ" },
    { fr: "la boîte aux lettres", no: "postkassen", phonetic: "la bwat o lætr" },
    { fr: "le robinet", no: "kranen", phonetic: "lə robinæ" },
    { fr: "la douche", no: "dusjen", phonetic: "la dusj" },
    { fr: "le chauffage", no: "oppvarmingen / varmen", phonetic: "lə sjofasjə" },
    { fr: "l'électricité", no: "elektrisiteten", phonetic: "lælæktrisite" },
    { fr: "le compteur", no: "måleren", phonetic: "lə kåtør" },
    { fr: "brancher", no: "å koble til / å plugge inn", phonetic: "bråsjæ" },
    { fr: "débrancher", no: "å koble fra / å trekke ut", phonetic: "debråsjæ" },
  ],
  tdf: [
    { fr: "le peloton", no: "feltet (sykkelfeltet)", phonetic: "lə pəlotå" },
    { fr: "l'étape", no: "etappen", phonetic: "letap" },
    { fr: "le col", no: "fjellovergangen", phonetic: "lə kol" },
    { fr: "le sprint", no: "spurten", phonetic: "lə sprænt" },
    { fr: "l'attaque", no: "angrepet", phonetic: "latak" },
    { fr: "attaquer", no: "å angripe / å rykke", phonetic: "atakæ" },
    { fr: "la fuite", no: "utbryterflukten", phonetic: "la fwit" },
    { fr: "le classement", no: "stillingen / klassementet", phonetic: "lə klasmå" },
    { fr: "le grimpeur", no: "klatreren", phonetic: "lə græmpør" },
    { fr: "le sprinter", no: "spurteren", phonetic: "lə spræntær" },
    { fr: "le rouleur", no: "rulleren (god på flate)", phonetic: "lə rulør" },
    { fr: "l'équipier", no: "lagkameraten / hjelperen", phonetic: "lekipjæ" },
    { fr: "le domestique", no: "hjelperytteren", phonetic: "lə domestik" },
    { fr: "le capitaine de route", no: "lagets vegfører", phonetic: "lə kapitæn də rut" },
    { fr: "le leader", no: "lederen", phonetic: "lə lidær" },
    { fr: "le vélo", no: "sykkelen", phonetic: "lə velo" },
    { fr: "le guidon", no: "styret (på sykkel)", phonetic: "lə gidå" },
    { fr: "la selle", no: "setet / sadelen", phonetic: "la sæl" },
    { fr: "la roue", no: "hjulet", phonetic: "la ru" },
    { fr: "la chaîne", no: "kjeden", phonetic: "la sjæn" },
    { fr: "le dérailleur", no: "girkassetten", phonetic: "lə derajør" },
    { fr: "la pédale", no: "pedalen", phonetic: "la pedal" },
    { fr: "le frein", no: "bremsen", phonetic: "lə fræn" },
    { fr: "le casque", no: "hjelmen", phonetic: "lə kask" },
    { fr: "le maillot", no: "trøyen", phonetic: "lə majo" },
    { fr: "le cuissard", no: "sykkelshortsen", phonetic: "lə kwissar" },
    { fr: "le bidon", no: "drikkeboksen / flasken", phonetic: "lə bidå" },
    { fr: "le maillot jaune", no: "den gule trøya (sammenlagsleder)", phonetic: "lə majo sjun" },
    { fr: "le maillot vert", no: "den grønne trøya (spurter)", phonetic: "lə majo vær" },
    { fr: "le maillot à pois", no: "den prikkete trøya (klatrer)", phonetic: "lə majo a pwa" },
    { fr: "le maillot blanc", no: "den hvite trøya (beste unge)", phonetic: "lə majo blå" },
    { fr: "le contre-la-montre", no: "tempoetappen", phonetic: "lə kåtrə la måtrə" },
    { fr: "l'étape de montagne", no: "fjelleetappen", phonetic: "letap də måtanjə" },
    { fr: "l'étape de plaine", no: "flatetappen", phonetic: "letap də plæn" },
    { fr: "la montagne", no: "fjellet", phonetic: "la måtanjə" },
    { fr: "la plaine", no: "sletten", phonetic: "la plæn" },
    { fr: "Alpe d'Huez", no: "Alpe d'Huez (kjent fjell)", phonetic: "alp dyæ" },
    { fr: "le Mont Ventoux", no: "Mont Ventoux (kjent fjell)", phonetic: "lə må våtu" },
    { fr: "le Tourmalet", no: "Tourmalet (kjent pass)", phonetic: "lə turmale" },
    { fr: "les Champs-Élysées", no: "Champs-Élysées (avslutning i Paris)", phonetic: "læ sjåzæliæzæ" },
    { fr: "les Pyrénées", no: "Pyreneene", phonetic: "læ pirenæ" },
    { fr: "les Alpes", no: "Alpene", phonetic: "læ zalp" },
    { fr: "la Bretagne", no: "Bretagne (region)", phonetic: "la brətanjə" },
    { fr: "l'échappée", no: "utbrytergruppen", phonetic: "lejapæ" },
    { fr: "le peloton de tête", no: "teten av feltet", phonetic: "lə pəlotå də tæt" },
    { fr: "l'abandon", no: "opgitt / utgått av rittet", phonetic: "labådå" },
    { fr: "abandonner", no: "å gi opp / å trekke seg", phonetic: "abådone" },
    { fr: "la chute", no: "veltet / fallet", phonetic: "la sjyt" },
    { fr: "chuter", no: "å velte / å falle", phonetic: "sjytæ" },
    { fr: "la crevaison", no: "punkteringen", phonetic: "la krəvæzå" },
    { fr: "crever", no: "å punktere", phonetic: "krəvæ" },
    { fr: "le ravitaillement", no: "depotet / matinntak underveis", phonetic: "lə ravitajmå" },
    { fr: "la zone de ravitaillement", no: "depotsonen", phonetic: "la zon də ravitajmå" },
    { fr: "le temps", no: "tiden", phonetic: "lə tå" },
    { fr: "le retard", no: "tidsforskjellen / etterslepet", phonetic: "lə rətar" },
    { fr: "le kilomètre", no: "kilometeren", phonetic: "lə kilometrə" },
    { fr: "la vitesse", no: "farten / hastigheten", phonetic: "la vitæs" },
    { fr: "la moyenne", no: "gjennomsnittet", phonetic: "la mwajæn" },
    { fr: "le classement général", no: "sammenlagtklassementet", phonetic: "lə klasmå sjenæral" },
    { fr: "le podium", no: "podiet", phonetic: "lə podjom" },
    { fr: "la victoire", no: "seieren", phonetic: "la viktoar" },
    { fr: "gagner l'étape", no: "vinne etappen", phonetic: "ganjæ letap" },
    { fr: "le vainqueur", no: "vinneren", phonetic: "lə vænkør" },
    { fr: "le directeur sportif", no: "sportslig leder / sportsdirektøren", phonetic: "lə diræktør sportif" },
    { fr: "le commissaire", no: "dommeren / kommissæren", phonetic: "lə komisær" },
    { fr: "le soigneur", no: "massøren / medisinsk personell", phonetic: "lə swainjør" },
    { fr: "le mécano", no: "mekanikeren", phonetic: "lə mekano" },
    { fr: "l'équipe", no: "laget", phonetic: "lekip" },
    { fr: "la formation", no: "oppstillingen / laget", phonetic: "la formassjå" },
    { fr: "le coureur", no: "rytteren / syklisten", phonetic: "lə kurør" },
    { fr: "le cycliste", no: "syklisten", phonetic: "lə siklist" },
    { fr: "pédaler", no: "å tråkke / å sykle", phonetic: "pedalæ" },
    { fr: "grimper", no: "å klatre / å gå oppover", phonetic: "græmpæ" },
    { fr: "descendre", no: "å kjøre ned", phonetic: "desåndrə" },
    { fr: "sprinter", no: "å spurte", phonetic: "spræntæ" },
    { fr: "s'échapper", no: "å rykke fra / å stikke av", phonetic: "sejapæ" },
    { fr: "distancer", no: "å ta avstand / å rykke fra", phonetic: "diståsæ" },
    { fr: "rattraper", no: "å ta igjen", phonetic: "ratrapæ" },
    { fr: "le départ", no: "starten", phonetic: "lə depar" },
    { fr: "l'arrivée", no: "mål / ankomst", phonetic: "larivæ" },
    { fr: "la ligne d'arrivée", no: "mållinjen", phonetic: "la linji darivæ" },
    { fr: "la ligne de départ", no: "startlinjen", phonetic: "la linji də depar" },
    { fr: "le peloton principal", no: "hovedfeltet", phonetic: "lə pəlotå præsipal" },
    { fr: "la bordure", no: "kantvindbryteren / echelon", phonetic: "la bordyr" },
    { fr: "rouler en bordure", no: "kjøre echelon", phonetic: "rulæ å bordyr" },
    { fr: "le vent de face", no: "motvinden", phonetic: "lə vå də fas" },
    { fr: "le vent de côté", no: "sidevinden", phonetic: "lə vå də kotæ" },
    { fr: "l'aspiration", no: "slipstrømmen", phonetic: "laspirassjå" },
    { fr: "rouler dans la roue", no: "sykle i slipstrømmen", phonetic: "rulæ då la ru" },
    { fr: "le braquet", no: "giringen / gjengerforholdet", phonetic: "lə brakæ" },
    { fr: "le développement", no: "utviklingen / gjengerforhold", phonetic: "lə devlopəmå" },
    { fr: "la cadence", no: "tråkkfrekvensen", phonetic: "la kadås" },
    { fr: "le watt", no: "wattene (effektmål)", phonetic: "lə wat" },
    { fr: "la puissance", no: "kraften / effekten", phonetic: "la pwisås" },
    { fr: "la forme", no: "formen", phonetic: "la form" },
    { fr: "en grande forme", no: "i toppform", phonetic: "å grå form" },
    { fr: "le Tour de France", no: "Tour de France", phonetic: "lə tur də fråns" },
    { fr: "la Grande Boucle", no: "den store løkken (kallenavn TdF)", phonetic: "la grå buklə" },
    { fr: "le Giro d'Italia", no: "Giro d'Italia", phonetic: "lə sjiro ditalia" },
    { fr: "la Vuelta", no: "Vuelta a España", phonetic: "la vuælta" },
    { fr: "le Grand Tour", no: "Grand Tour (3 store rittet)", phonetic: "lə grå tur" },
    { fr: "Paris-Roubaix", no: "Paris-Roubaix (klassiker)", phonetic: "pari rubæ" },
    { fr: "la Classique", no: "klassikeren (ritt)", phonetic: "la klasik" },
    { fr: "le Monument", no: "monumentet (et av de 5 store)", phonetic: "lə monumå" },
    { fr: "la côte", no: "kneiken / stigningen", phonetic: "la kot" },
    { fr: "le sommet", no: "toppen / fjellets topp", phonetic: "lə somæ" },
    { fr: "hors catégorie", no: "utenfor kategori (vanskeligste klatringa)", phonetic: "or kategori" },
    { fr: "première catégorie", no: "første kategori (klatring)", phonetic: "prəmjær kategori" },
    { fr: "deuxième catégorie", no: "andre kategori (klatring)", phonetic: "døzjæm kategori" },
    { fr: "troisième catégorie", no: "tredje kategori (klatring)", phonetic: "trwazjæm kategori" },
    { fr: "quatrième catégorie", no: "fjerde kategori (klatring)", phonetic: "katrjæm kategori" },
    { fr: "le palmarès", no: "merittlisten / seierlisten", phonetic: "lə palmaræs" },
    { fr: "le dossard", no: "startnummeret", phonetic: "lə dossar" },
    { fr: "l'étape reine", no: "kongeetappen", phonetic: "letap ræn" },
    { fr: "la voiture balai", no: "bilen som plukker opp de siste", phonetic: "la vwatyr balæ" },
    { fr: "la caravane", no: "karavanen", phonetic: "la karavan" },
    { fr: "le podium de Paris", no: "pallen i Paris", phonetic: "lə podjom də pari" },
    { fr: "le classement par équipes", no: "lagklassementet", phonetic: "lə klasmå par ekip" },
    { fr: "le bonification", no: "bonussekunder", phonetic: "lə bonifikassjå" },
    { fr: "les secondes de bonification", no: "bonussekunder", phonetic: "læ səkåd də bonifikassjå" },
    { fr: "le drapeau à damier", no: "ruteflagget (mål)", phonetic: "lə drapo a damjæ" },
    { fr: "lever les bras", no: "å løfte armene (i mål)", phonetic: "ləvæ læ bra" },
    { fr: "franchir la ligne", no: "å passere mållinjen", phonetic: "frånsjir la linji" },
    { fr: "la sacoche", no: "sykkelveska / sadelbagen", phonetic: "la sakosjə" },
    { fr: "le compteur", no: "sykkeldatamaskinen / måleren", phonetic: "lə kåtør" },
    { fr: "le GPS", no: "GPSen", phonetic: "lə sjepees" },
    { fr: "l'oreillette", no: "ørestykket (kommunikasjon)", phonetic: "lorəjæt" },
    { fr: "la voiture suiveuse", no: "følgebilen", phonetic: "la vwatyr swivøz" },
    { fr: "le Tour est en route", no: "touren er i gang", phonetic: "lə tur æ å rut" },
    { fr: "le contre-la-montre par équipes", no: "lagtempo", phonetic: "lə kåtrə la måtrə par ekip" },
    { fr: "la jonction", no: "sammenslåingen / samlingen", phonetic: "la sjåksjå" },
    { fr: "faire la jonction", no: "å ta igjen / å koble seg på", phonetic: "fær la sjåksjå" },
    { fr: "le peloton s'étire", no: "feltet strekker seg ut", phonetic: "lə pəlotå setir" },
    { fr: "nerveux", no: "nervøs / spent", phonetic: "nærvø" },
    { fr: "le final", no: "avslutningen", phonetic: "lə final" },
    { fr: "le dernier kilomètre", no: "siste kilometeren", phonetic: "lə dærnjæ kilometrə" },
    { fr: "le flamme rouge", no: "den røde flammen (1 km igjen)", phonetic: "lə flam rusjə" },
    { fr: "la montée", no: "oppstigningen / kneiken", phonetic: "la måtæ" },
    { fr: "la descente", no: "nedstigningen / utforbakken", phonetic: "la desåt" },
    { fr: "le virage", no: "svingen", phonetic: "lə virasj" },
    { fr: "épinglé", no: "hårnålssving", phonetic: "epænjlæ" },
    { fr: "le lacet", no: "sikksakken / hårnålssving", phonetic: "lə lasæ" },
    { fr: "en peloton", no: "i felt", phonetic: "å pəlotå" },
    { fr: "en solitaire", no: "alene / solo", phonetic: "å solitær" },
    { fr: "la gloire", no: "æren / berømmelsen", phonetic: "la gloar" },
    { fr: "le champion", no: "mesteren / vinneren", phonetic: "lə sjåpjå" },
    { fr: "la championne", no: "mesteren (kvinne)", phonetic: "la sjåpjon" },
    { fr: "l'exploit", no: "bragden", phonetic: "læksplwa" },
    { fr: "légendaire", no: "legendarisk", phonetic: "lesjådær" },
    { fr: "historique", no: "historisk", phonetic: "istorik" },
    { fr: "magnifique", no: "strålende / praktfull", phonetic: "manifik" },
    { fr: "impressionnant", no: "imponerende", phonetic: "æmpræsjonå" },
    { fr: "le record", no: "rekorden", phonetic: "lə rəkor" },
    { fr: "battre un record", no: "å slå en rekord", phonetic: "batrə øn rəkor" },
    { fr: "la performance", no: "prestasjonen", phonetic: "la pærformås" },
    { fr: "le classement par points", no: "poengsumklassementet", phonetic: "lə klasmå par poæn" },
    { fr: "le classement de la montagne", no: "klatrerklassementet", phonetic: "lə klasmå də la måtanjə" },
    { fr: "la prime", no: "premien / bonusen", phonetic: "la prim" },
    { fr: "neutralisé", no: "nøytralisert", phonetic: "nøtralizæ" },
    { fr: "hors délai", no: "utenfor tidsskjemaet", phonetic: "or delæ" },
    { fr: "le délai", no: "tidsgrensen", phonetic: "lə delæ" },
    { fr: "la pénalité", no: "boten / straffen", phonetic: "la penalitæ" },
    { fr: "disqualifié", no: "diskvalifisert", phonetic: "diskwalifijæ" },
    { fr: "le drapeau rouge", no: "det røde flagget (stopp!)", phonetic: "lə drapo rusjə" },
    { fr: "neutraliser", no: "å nøytralisere (stoppe rittet)", phonetic: "nøtralizæ" },
    { fr: "redémarrer", no: "å starte igjen", phonetic: "rədemarær" },
    { fr: "la chaussée", no: "veibanen", phonetic: "la sjosæ" },
    { fr: "les pavés", no: "brosteinsbelgene", phonetic: "læ pavæ" },
    { fr: "le gravier", no: "grusen", phonetic: "lə gravjæ" },
    { fr: "la côte d'azur", no: "Azurkysten", phonetic: "la kot dazyr" },
    { fr: "l'Alsace", no: "Alsace (region i Frankrike)", phonetic: "lalsas" },
    { fr: "la Provence", no: "Provence (region)", phonetic: "la provås" },
    { fr: "le Massif Central", no: "Massif Central (platå)", phonetic: "lə masif såtral" },
    { fr: "le Jura", no: "Jura-fjellene", phonetic: "lə sjyra" },
    { fr: "le Vercors", no: "Vercors (fjellområde)", phonetic: "ləværkor" },
    { fr: "le Galibier", no: "Galibier (kjent pass)", phonetic: "lə galibijæ" },
    { fr: "l'Izoard", no: "Izoard (kjent pass)", phonetic: "lizwar" },
    { fr: "la Madeleine", no: "Madeleine (kjent pass)", phonetic: "la madlæn" },
    { fr: "le Télégraphe", no: "Télégraphe (kjent pass)", phonetic: "lə telegraf" },
    { fr: "combatif", no: "kamplysten / aggressiv", phonetic: "kåbatif" },
    { fr: "le prix de la combativité", no: "prisen for kampvilje", phonetic: "lə pri də la kåbativitæ" },
    { fr: "la roue de secours", no: "reservehjulet", phonetic: "la ru də səkur" },
    { fr: "changer la roue", no: "å skifte hjul", phonetic: "sjåsjæ la ru" },
    { fr: "le mécano de route", no: "veimedmekanikeren", phonetic: "lə mekano də rut" },
    { fr: "les flammes", no: "flammene (dekorasjon langs ruta)", phonetic: "læ flam" },
    { fr: "le public", no: "publikummet", phonetic: "lə pyblik" },
    { fr: "les spectateurs", no: "tilskuerne", phonetic: "læ spæktatør" },
    { fr: "applaudir", no: "å klappe / å applaudere", phonetic: "aplodyr" },
    { fr: "encourager", no: "å heie på / å oppmuntre", phonetic: "åkurasjæ" },
    { fr: "Allez !", no: "Kom igjen! / Kjør på!", phonetic: "alæ" },
    { fr: "Courage !", no: "Stå på! / Ikke gi opp!", phonetic: "kurasjə" },
    { fr: "Bravo !", no: "Bravo! / Godt gjort!", phonetic: "bravo" },
    { fr: "la pente", no: "bakken / hellingen", phonetic: "la påt" },
    { fr: "le pavé", no: "brosteinen / bulkete underlag", phonetic: "lə pavæ" },
    { fr: "le contre-la-montre", no: "tempoetappe / enkeltstart", phonetic: "lə kåtrə la måtr" },
    { fr: "la bonification", no: "bonussekunder", phonetic: "la bonifikassjå" },
    { fr: "le peloton de tête", no: "ledende gruppe", phonetic: "lə pəlotå də tæt" },
    { fr: "l'échappée belle", no: "det vellykkede utbruddet", phonetic: "lejapæ bæl" },
    { fr: "rouler à bloc", no: "å kjøre for fullt", phonetic: "rulæ a blok" },
    { fr: "le maillot à pois", no: "klatretrøyen (med prikker)", phonetic: "lə majo a pwa" },
  ],
  senses: [
    { fr: "rouge", no: "rød", phonetic: "rusjə" },
    { fr: "bleu", no: "blå", phonetic: "blø" },
    { fr: "vert", no: "grønn", phonetic: "vær" },
    { fr: "jaune", no: "gul", phonetic: "sjun" },
    { fr: "orange", no: "oransje", phonetic: "orånsjə" },
    { fr: "violet", no: "lilla / fiolett", phonetic: "vjolæ" },
    { fr: "rose", no: "rosa", phonetic: "roz" },
    { fr: "noir", no: "svart", phonetic: "nwar" },
    { fr: "blanc", no: "hvit", phonetic: "blå" },
    { fr: "gris", no: "grå", phonetic: "gri" },
    { fr: "brun", no: "brun", phonetic: "bræn" },
    { fr: "beige", no: "beige", phonetic: "bæsjə" },
    { fr: "turquoise", no: "turkis", phonetic: "tyrkwaz" },
    { fr: "bordeaux", no: "mørkerød / bordeauxfarge", phonetic: "bordo" },
    { fr: "doré", no: "gyllen", phonetic: "doræ" },
    { fr: "argenté", no: "sølvfarget", phonetic: "arsjåtæ" },
    { fr: "ivoire", no: "elfenbensfarget", phonetic: "ivoar" },
    { fr: "écarlate", no: "skarlagenrød", phonetic: "ekarlat" },
    { fr: "indigo", no: "indigo", phonetic: "ændigo" },
    { fr: "ocre", no: "oker (gul-brun farge)", phonetic: "okrə" },
    { fr: "rond", no: "rund", phonetic: "rå" },
    { fr: "carré", no: "firkantet / kvadratisk", phonetic: "karæ" },
    { fr: "rectangulaire", no: "rektangulær", phonetic: "ræktångyler" },
    { fr: "triangulaire", no: "trekantet", phonetic: "trijångylær" },
    { fr: "ovale", no: "oval", phonetic: "oval" },
    { fr: "en spirale", no: "i spiralform", phonetic: "å spiral" },
    { fr: "courbé", no: "buet / krum", phonetic: "kurbæ" },
    { fr: "anguleux", no: "kantet / angular", phonetic: "ågylo" },
    { fr: "étroit", no: "smal", phonetic: "etrwa" },
    { fr: "large", no: "bred / vid", phonetic: "larsjə" },
    { fr: "épais", no: "tykk", phonetic: "epæ" },
    { fr: "mince", no: "tynn / slank", phonetic: "mæns" },
    { fr: "haut", no: "høy", phonetic: "o" },
    { fr: "bas", no: "lav", phonetic: "ba" },
    { fr: "profond", no: "dyp", phonetic: "profå" },
    { fr: "peu profond", no: "grunn / ikke dyp", phonetic: "pø profå" },
    { fr: "clair", no: "lys / klar", phonetic: "klær" },
    { fr: "sombre", no: "mørk", phonetic: "såbrə" },
    { fr: "brillant", no: "skinnende / blank", phonetic: "brijå" },
    { fr: "mat", no: "matt (uten glans)", phonetic: "mat" },
    { fr: "lumineux", no: "lysende / lyst", phonetic: "lyminø" },
    { fr: "opaque", no: "ugjennomsiktig", phonetic: "opak" },
    { fr: "transparent", no: "gjennomsiktig", phonetic: "tråsparå" },
    { fr: "scintillant", no: "glitrende / funklende", phonetic: "sæntijå" },
    { fr: "doux", no: "myk / blid / mild", phonetic: "du" },
    { fr: "rugueux", no: "ru / grov (overflate)", phonetic: "rygo" },
    { fr: "lisse", no: "glatt / jevn", phonetic: "lis" },
    { fr: "dur", no: "hard", phonetic: "dyr" },
    { fr: "mou", no: "myk / bløt", phonetic: "mu" },
    { fr: "velours", no: "fløyel / fløyelsaktig", phonetic: "vəlur" },
    { fr: "granuleux", no: "kornete / grovkornet", phonetic: "granylø" },
    { fr: "collant", no: "klissete / klebrig", phonetic: "kolå" },
    { fr: "le bruit", no: "støyen / lyden", phonetic: "lə brwi" },
    { fr: "le silence", no: "stillheten", phonetic: "lə silåns" },
    { fr: "le son", no: "lyden / tonen", phonetic: "lə så" },
    { fr: "la mélodie", no: "melodien", phonetic: "la melodyi" },
    { fr: "le rythme", no: "rytmen", phonetic: "lə ritm" },
    { fr: "fort", no: "høy (lyd) / sterk", phonetic: "for" },
    { fr: "faible", no: "svak / lav (lyd)", phonetic: "fæblə" },
    { fr: "aigu", no: "høyfrekvent / skarp", phonetic: "egu" },
    { fr: "grave", no: "lavfrekvent / dyp (lyd)", phonetic: "grav" },
    { fr: "sourd", no: "dempet / hul (lyd)", phonetic: "sur" },
    { fr: "strident", no: "skjærende / skingrende", phonetic: "stridå" },
    { fr: "doux (son)", no: "myk lyd / behagelig lyd", phonetic: "du" },
    { fr: "l'odeur", no: "lukten", phonetic: "lodør" },
    { fr: "le parfum", no: "parfymen / duften", phonetic: "lə parfæn" },
    { fr: "floral", no: "blomsterduftende", phonetic: "floral" },
    { fr: "musqué", no: "moskusduftende", phonetic: "myskæ" },
    { fr: "frais", no: "frisk / kjølig (lukt)", phonetic: "fræ" },
    { fr: "rance", no: "harsk", phonetic: "råns" },
    { fr: "fumé", no: "røkt / røykaktig", phonetic: "fymæ" },
    { fr: "sucré", no: "søt", phonetic: "sykræ" },
    { fr: "salé", no: "salt", phonetic: "salæ" },
    { fr: "amer", no: "bitter", phonetic: "amær" },
    { fr: "acide", no: "sur / syrlig", phonetic: "asid" },
    { fr: "piquant", no: "sterk / pikant / krydret", phonetic: "pikå" },
    { fr: "la saveur", no: "smaken", phonetic: "la savør" },
    { fr: "le goût", no: "smaken", phonetic: "lə gu" },
    { fr: "fade", no: "smakløs / kraftløs", phonetic: "fad" },
    { fr: "relevé", no: "krydret / sterk i smaken", phonetic: "rəlvæ" },
    { fr: "voir", no: "å se", phonetic: "vwar" },
    { fr: "entendre", no: "å høre", phonetic: "åtåndrə" },
    { fr: "sentir", no: "å lukte / å kjenne", phonetic: "såtir" },
    { fr: "toucher", no: "å ta på / å berøre", phonetic: "tusjæ" },
    { fr: "goûter", no: "å smake", phonetic: "gutæ" },
    { fr: "écouter", no: "å lytte", phonetic: "ekutæ" },
    { fr: "regarder", no: "å se på / å betrakte", phonetic: "rəgardæ" },
    { fr: "observer", no: "å observere / å iaktta", phonetic: "obsærvæ" },
    { fr: "la couleur", no: "fargen", phonetic: "la kulør" },
    { fr: "la forme", no: "formen", phonetic: "la form" },
    { fr: "la texture", no: "teksturen", phonetic: "la tækstyr" },
    { fr: "la lumière", no: "lyset", phonetic: "la lymjær" },
    { fr: "l'ombre", no: "skyggen", phonetic: "låmbrə" },
    { fr: "le contraste", no: "kontrasten", phonetic: "lə kåtrast" },
    { fr: "vif", no: "livlig / sterk (om farge)", phonetic: "vif" },
    { fr: "pâle", no: "blek / lys", phonetic: "pal" },
    { fr: "foncé", no: "mørk (nyanse)", phonetic: "fåsæ" },
    { fr: "cru", no: "skrikende / rå (om farge)", phonetic: "kry" },
    { fr: "nuancé", no: "nyansert", phonetic: "nwåsæ" },
    { fr: "terne", no: "mattgrå / kjedelig (om farge)", phonetic: "tærn" },
    { fr: "chatoyant", no: "skiftende / iriserende", phonetic: "sjatojå" },
    { fr: "chaud (couleur)", no: "varm (farge)", phonetic: "sjo" },
    { fr: "froid (couleur)", no: "kald (farge)", phonetic: "frwa" },
    { fr: "le sens du toucher", no: "berøringssansen", phonetic: "lə såns dy tusjæ" },
    { fr: "le sens de la vue", no: "synet", phonetic: "lə såns də la vy" },
    { fr: "le sens de l'ouïe", no: "hørselen", phonetic: "lə såns də lwi" },
    { fr: "le sens de l'odorat", no: "luktesansen", phonetic: "lə såns də lodora" },
    { fr: "le sens du goût", no: "smakssansen", phonetic: "lə såns dy gu" },
    { fr: "rugeux", no: "grov / ru (overflate)", phonetic: "rysjø" },
    { fr: "soyeux", no: "silkemyk", phonetic: "swajø" },
    { fr: "craquant", no: "sprø / knasende", phonetic: "krakå" },
    { fr: "crémeux", no: "kremet", phonetic: "kremø" },
    { fr: "épicé", no: "krydret / sterk", phonetic: "episæ" },
    { fr: "aigre", no: "sur / skarp i smaken", phonetic: "ægrə" },
    { fr: "umami", no: "umami (fyldig smak)", phonetic: "ymami" },
    { fr: "pétillant", no: "brusende / spruten", phonetic: "petijå" },
    { fr: "plat (boisson)", no: "ikke kullsyreholdig", phonetic: "pla" },
    { fr: "envoûtant", no: "fortryllende", phonetic: "åvutå" },
    { fr: "nauséabond", no: "kvalmende", phonetic: "nozeabå" },
    { fr: "velouté", no: "fløyelsmyk / silkeglatt", phonetic: "vəlutæ" },
  ],
  food: [
    { fr: "le poulet", no: "kyllingen", phonetic: "lə pulæ" },
    { fr: "le bœuf", no: "oksekjøttet", phonetic: "lə bøf" },
    { fr: "le porc", no: "svinekjøttet", phonetic: "lə por" },
    { fr: "l'agneau", no: "lammekjøttet", phonetic: "lanjo" },
    { fr: "le veau", no: "kalvekjøttet", phonetic: "lə vo" },
    { fr: "le lapin", no: "kaninen / kaninekjøttet", phonetic: "lə lapæn" },
    { fr: "le canard", no: "anden / andekjøttet", phonetic: "lə kanar" },
    { fr: "la dinde", no: "kalkunen", phonetic: "la dænd" },
    { fr: "les lardons", no: "baconbitene / strimlet bacon", phonetic: "læ lardå" },
    { fr: "le saucisson", no: "spekepølsen", phonetic: "lə sosisså" },
    { fr: "la saucisse", no: "pølsen", phonetic: "la sosis" },
    { fr: "le jambon", no: "skinken", phonetic: "lə sjåbå" },
    { fr: "le pâté", no: "patéen", phonetic: "lə patæ" },
    { fr: "le saumon", no: "laksenen", phonetic: "lə somå" },
    { fr: "le thon", no: "tunfisken", phonetic: "lə tå" },
    { fr: "le cabillaud", no: "torsken", phonetic: "lə kabijo" },
    { fr: "la sole", no: "sjøtungen (fisk)", phonetic: "la sol" },
    { fr: "les crevettes", no: "rekene", phonetic: "læ krəvæt" },
    { fr: "les moules", no: "muslingene / blåskjellene", phonetic: "læ mul" },
    { fr: "les huîtres", no: "østersene", phonetic: "læ witrə" },
    { fr: "le homard", no: "hummeren", phonetic: "lə omar" },
    { fr: "les sardines", no: "sardinene", phonetic: "læ sardin" },
    { fr: "la truite", no: "ørreten", phonetic: "la trwit" },
    { fr: "les anchois", no: "ansjoserene", phonetic: "læ zåsjwa" },
    { fr: "le bar", no: "havabboren", phonetic: "lə bar" },
    { fr: "la carotte", no: "gulroten", phonetic: "la karot" },
    { fr: "la pomme de terre", no: "poteten", phonetic: "la pom də tær" },
    { fr: "l'oignon", no: "løken", phonetic: "lonjå" },
    { fr: "l'ail", no: "hvitløken", phonetic: "laj" },
    { fr: "la tomate", no: "tomaten", phonetic: "la tomat" },
    { fr: "la laitue", no: "isbergsalaten", phonetic: "la læty" },
    { fr: "le brocoli", no: "brokkolien", phonetic: "lə brokoli" },
    { fr: "les haricots verts", no: "grønne bønner", phonetic: "læ ariko vær" },
    { fr: "le poivron", no: "paprikaen", phonetic: "lə pwavrå" },
    { fr: "le champignon", no: "soppen", phonetic: "lə sjåpinjå" },
    { fr: "la courgette", no: "squashen / zucchini", phonetic: "la kursjæt" },
    { fr: "l'aubergine", no: "auberginen", phonetic: "lobærsjin" },
    { fr: "le poireau", no: "purren", phonetic: "lə pwaro" },
    { fr: "les épinards", no: "spinaten", phonetic: "læ zepinat" },
    { fr: "les petits pois", no: "ertene", phonetic: "læ pəti pwa" },
    { fr: "le navet", no: "nepe", phonetic: "lə navæ" },
    { fr: "le céleri", no: "sellerien", phonetic: "lə selri" },
    { fr: "l'artichaut", no: "artisjokken", phonetic: "lartisjo" },
    { fr: "le concombre", no: "agurken", phonetic: "lə kåkåbrə" },
    { fr: "la betterave", no: "rødbeten", phonetic: "la bætrав" },
    { fr: "la pomme", no: "eplet", phonetic: "la pom" },
    { fr: "la poire", no: "pæren", phonetic: "la pwar" },
    { fr: "le raisin", no: "druen", phonetic: "lə ræzæn" },
    { fr: "la fraise", no: "jordbæret", phonetic: "la fræz" },
    { fr: "la cerise", no: "kirsebæret", phonetic: "la səriz" },
    { fr: "l'orange", no: "appelsinen", phonetic: "lorånsjə" },
    { fr: "le citron", no: "sitronen", phonetic: "lə sitrå" },
    { fr: "la pêche", no: "fersken", phonetic: "la pæsjə" },
    { fr: "l'abricot", no: "aprikosen", phonetic: "labriko" },
    { fr: "le melon", no: "melonen", phonetic: "lə məlå" },
    { fr: "la framboise", no: "bringebæret", phonetic: "la fråbwaz" },
    { fr: "la myrtille", no: "blåbæret", phonetic: "la mirtij" },
    { fr: "la banane", no: "bananen", phonetic: "la banan" },
    { fr: "l'ananas", no: "ananassen", phonetic: "lanana" },
    { fr: "la mangue", no: "mangoen", phonetic: "la måg" },
    { fr: "le kiwi", no: "kiwien", phonetic: "lə kiwi" },
    { fr: "la prune", no: "plommen", phonetic: "la pryn" },
    { fr: "le fromage", no: "osten", phonetic: "lə fromasj" },
    { fr: "le beurre", no: "smøret", phonetic: "lə bør" },
    { fr: "la crème", no: "fløten", phonetic: "la kræm" },
    { fr: "le lait", no: "melken", phonetic: "lə læ" },
    { fr: "le yaourt", no: "yoghurten", phonetic: "lə jaurt" },
    { fr: "les œufs", no: "eggene", phonetic: "læ zo" },
    { fr: "le gruyère", no: "gruyère-osten", phonetic: "lə gryjær" },
    { fr: "le brie", no: "brie-osten", phonetic: "lə bri" },
    { fr: "le camembert", no: "camembert-osten", phonetic: "lə kamåbær" },
    { fr: "le roquefort", no: "roquefort-osten", phonetic: "lə rokfor" },
    { fr: "la crème fraîche", no: "crème fraîche / rømme", phonetic: "la kræm fræsjə" },
    { fr: "le pain", no: "brødet", phonetic: "lə pæn" },
    { fr: "la baguette", no: "baguetten", phonetic: "la bagæt" },
    { fr: "la farine", no: "melet", phonetic: "la farin" },
    { fr: "le sucre", no: "sukkeret", phonetic: "lə sykrə" },
    { fr: "le sel", no: "saltet", phonetic: "lə sæl" },
    { fr: "le poivre", no: "pepperet", phonetic: "lə pwavrə" },
    { fr: "l'huile", no: "oljen", phonetic: "lwil" },
    { fr: "le vinaigre", no: "eddiken", phonetic: "lə vinægrə" },
    { fr: "les herbes", no: "urtene", phonetic: "læ zærb" },
    { fr: "les épices", no: "krydderne", phonetic: "læ zepis" },
    { fr: "le riz", no: "risen", phonetic: "lə ri" },
    { fr: "les pâtes", no: "pastaen", phonetic: "læ pat" },
    { fr: "les lentilles", no: "linsene", phonetic: "læ låtij" },
    { fr: "la moutarde", no: "sennepen", phonetic: "la mutard" },
    { fr: "le miel", no: "honningen", phonetic: "lə mjæl" },
    { fr: "la confiture", no: "syltetøyet", phonetic: "la kåfityr" },
    { fr: "cuire", no: "å koke / å tilberede", phonetic: "kwir" },
    { fr: "bouillir", no: "å koke (vann)", phonetic: "bujir" },
    { fr: "frire", no: "å fritere / å steke i olje", phonetic: "frir" },
    { fr: "griller", no: "å grille", phonetic: "grijæ" },
    { fr: "rôtir", no: "å steke i ovn", phonetic: "rotir" },
    { fr: "mijoter", no: "å småkoke / å putre", phonetic: "misjotæ" },
    { fr: "couper", no: "å kutte / å skjære", phonetic: "kupæ" },
    { fr: "hacher", no: "å hakke", phonetic: "asjæ" },
    { fr: "mélanger", no: "å blande / å røre", phonetic: "melåsjæ" },
    { fr: "assaisonner", no: "å krydre / å smake til", phonetic: "asæzonæ" },
    { fr: "faire revenir", no: "å steke lett / å surre", phonetic: "fær rəvənir" },
    { fr: "éplucher", no: "å skrelle", phonetic: "eplysjæ" },
    { fr: "râper", no: "å rive (ost etc.)", phonetic: "rapæ" },
    { fr: "émincer", no: "å skjære i tynne skiver", phonetic: "emænsæ" },
    { fr: "faire mariner", no: "å marinere", phonetic: "fær marinæ" },
    { fr: "la casserole", no: "kjelen / gryta", phonetic: "la kasrol" },
    { fr: "la poêle", no: "stekepanna", phonetic: "la pwal" },
    { fr: "le four", no: "ovnen", phonetic: "lə fur" },
    { fr: "le couteau", no: "kniven", phonetic: "lə kuto" },
    { fr: "la planche à découper", no: "fjøla", phonetic: "la plåsjə a dekupæ" },
    { fr: "le saladier", no: "salatbollen", phonetic: "lə saladjæ" },
    { fr: "la passoire", no: "silen / dørslaget", phonetic: "la pasoar" },
    { fr: "le fouet", no: "vispen", phonetic: "lə fuæ" },
    { fr: "la spatule", no: "spatelen / stekespaden", phonetic: "la spatyl" },
    { fr: "la louche", no: "øsen / suppeskjeen", phonetic: "la lusjə" },
    { fr: "la soupe", no: "suppen", phonetic: "la sup" },
    { fr: "la salade", no: "salaten", phonetic: "la salad" },
    { fr: "l'omelette", no: "omeletten", phonetic: "lomælet" },
    { fr: "la quiche", no: "quichen", phonetic: "la kisjə" },
    { fr: "la ratatouille", no: "ratatouille (grønnsaksgryterett)", phonetic: "la ratatuj" },
    { fr: "le coq au vin", no: "coq au vin (kylling i vin)", phonetic: "lə kok o væn" },
    { fr: "le bœuf bourguignon", no: "bœuf bourguignon (okse i rødvin)", phonetic: "lə bøf burginjå" },
    { fr: "la crêpe", no: "pannekaken", phonetic: "la kræp" },
    { fr: "la tarte", no: "terten", phonetic: "la tart" },
    { fr: "la mousse au chocolat", no: "sjokolademousse", phonetic: "la mus o sjokola" },
    { fr: "la tartiflette", no: "tartiflette (potet og osteform)", phonetic: "la tartiflet" },
    { fr: "le gratin dauphinois", no: "potetskinke (gratin)", phonetic: "lə gratæn dofinwa" },
    { fr: "la bouillabaisse", no: "bouillabaisse (fiskesuppe)", phonetic: "la bujabæs" },
    { fr: "le cassoulet", no: "cassoulet (bønnegryte)", phonetic: "lə kasuæ" },
    { fr: "la blanquette de veau", no: "blanquette de veau (kalvegryte)", phonetic: "la blåkæt də vo" },
    { fr: "le pot-au-feu", no: "pot-au-feu (kokt kjøtt og grønnsaker)", phonetic: "lə pot o fø" },
    { fr: "l'eau", no: "vannet", phonetic: "lo" },
    { fr: "le vin", no: "vinen", phonetic: "lə væn" },
    { fr: "la bière", no: "ølet", phonetic: "la bjær" },
    { fr: "le jus", no: "juicen", phonetic: "lə sjy" },
    { fr: "le café", no: "kaffen", phonetic: "lə kafæ" },
    { fr: "le thé", no: "teen", phonetic: "lə tæ" },
    { fr: "le champagne", no: "champagnen", phonetic: "lə sjåpanjə" },
    { fr: "le cidre", no: "eplesidervinen / cidren", phonetic: "lə sidrə" },
    { fr: "l'eau minérale", no: "mineralvannet", phonetic: "lo mineral" },
    { fr: "le sirop", no: "sirupen", phonetic: "lə siro" },
    { fr: "le vin rouge", no: "rødvinen", phonetic: "lə væn rusjə" },
    { fr: "le vin blanc", no: "hvitvinen", phonetic: "lə væn blå" },
    { fr: "le vin rosé", no: "rosévinen", phonetic: "lə væn rozæ" },
    { fr: "l'apéritif", no: "aperitifen", phonetic: "laperitif" },
    { fr: "le digestif", no: "digestiven", phonetic: "lə disjæstif" },
    { fr: "l'entrée", no: "forretten", phonetic: "låtræ" },
    { fr: "le plat du jour", no: "dagens rett", phonetic: "lə pla dy sjur" },
    { fr: "le menu", no: "menyen / setmenyen", phonetic: "lə məny" },
    { fr: "la recette", no: "oppskriften", phonetic: "la rəsæt" },
    { fr: "les ingrédients", no: "ingrediensene", phonetic: "læ zægrediå" },
    { fr: "la portion", no: "porsjonen", phonetic: "la porssjå" },
    { fr: "la garniture", no: "tilbehøret / pynt", phonetic: "la garnityr" },
    { fr: "la sauce", no: "sausen", phonetic: "la sos" },
    { fr: "la vinaigrette", no: "vinaigrettedressingen", phonetic: "la vinægræt" },
    { fr: "la béchamel", no: "béchamelsausen", phonetic: "la besjamæl" },
    { fr: "le bouillon", no: "kraftkoket / buljongen", phonetic: "lə bujå" },
    { fr: "la marinade", no: "marinaden", phonetic: "la marinad" },
    { fr: "cru", no: "rå (mat)", phonetic: "kry" },
    { fr: "cuit", no: "tilberedt / kokt", phonetic: "kwi" },
    { fr: "bien cuit", no: "gjennomstekt", phonetic: "bjæn kwi" },
    { fr: "à point", no: "medium (kjøtt)", phonetic: "a pwoæn" },
    { fr: "saignant", no: "blodig / lite stekt", phonetic: "sænjå" },
    { fr: "croustillant", no: "sprø", phonetic: "krustijå" },
    { fr: "fondant", no: "smeltende / myk", phonetic: "fådå" },
    { fr: "le four à micro-ondes", no: "mikrobølgeovnen", phonetic: "lə fur a mikro åd" },
    { fr: "le réfrigérateur", no: "kjøleskapet", phonetic: "lə refrischæratør" },
    { fr: "le congélateur", no: "fryseren", phonetic: "lə kåsjælatør" },
    { fr: "la recette de famille", no: "familieoppskriften", phonetic: "la rəsæt də famij" },
    { fr: "le marché aux puces", no: "loppemarknedet", phonetic: "lə marsjæ o pys" },
    { fr: "la fromagerie", no: "ostebutikken", phonetic: "la fromasjəri" },
    { fr: "la charcuterie", no: "kjøttdelikatessen", phonetic: "la sjarkytəri" },
    { fr: "la pâtisserie", no: "konditoriet", phonetic: "la patisəri" },
    { fr: "le croissant", no: "croissanten", phonetic: "lə krwasså" },
    { fr: "le pain au chocolat", no: "pain au chocolat", phonetic: "lə pæn o sjokola" },
    { fr: "la brioche", no: "briosjen", phonetic: "la brijosjə" },
    { fr: "le macaron", no: "makaronen", phonetic: "lə makarå" },
    { fr: "l'éclair", no: "eclairén", phonetic: "leklær" },
    { fr: "la tarte tatin", no: "tarte tatin (epleomvendt kake)", phonetic: "la tart tatæn" },
    { fr: "la madeleine", no: "madeleinekaken", phonetic: "la madlæn" },
    { fr: "le nougat", no: "nougaten", phonetic: "lə nuga" },
    { fr: "les fruits de mer", no: "sjømat", phonetic: "læ frwi də mær" },
    { fr: "la fondue", no: "fonduen", phonetic: "la fådy" },
    { fr: "la raclette", no: "racletten (smeltet ostegrill)", phonetic: "la raklæt" },
    { fr: "le foie gras", no: "foie gras (gaasselever)", phonetic: "lə fwa gra" },
    { fr: "la truffe", no: "trøffelen", phonetic: "la tryf" },
    { fr: "la noix", no: "valnøtten", phonetic: "la nwa" },
    { fr: "l'amande", no: "mandelen", phonetic: "lamåd" },
    { fr: "la noisette", no: "hasselnøtten", phonetic: "la nwazæt" },
    { fr: "la pistache", no: "pistasjen", phonetic: "la pistasjə" },
    { fr: "la cannelle", no: "kanel", phonetic: "la kanæl" },
    { fr: "le gingembre", no: "ingefæren", phonetic: "lə sjænjåbrə" },
    { fr: "le cumin", no: "spiskummen", phonetic: "lə kymæn" },
    { fr: "le curry", no: "curryen", phonetic: "lə kyri" },
    { fr: "le paprika", no: "paprikapulveret", phonetic: "lə paprika" },
    { fr: "le basilic", no: "basilikumet", phonetic: "lə bazilik" },
    { fr: "le thym", no: "timian", phonetic: "lə tæn" },
    { fr: "le romarin", no: "rosmarin", phonetic: "lə romaræn" },
    { fr: "le persil", no: "persillen", phonetic: "lə pærsil" },
    { fr: "la ciboulette", no: "gressløken", phonetic: "la sibulæt" },
    { fr: "l'estragon", no: "estragon", phonetic: "læstragå" },
    { fr: "le laurier", no: "laurbærbladet", phonetic: "lə lorjæ" },
  ],
};
