export const STATIC_VOCAB = {
  core: [
    // VERBS
    { fr:"comprendre",no:"å forstå",p:"kåpråndər",forms:[["je comprends","pr"],["nous comprenons","pr"],["ils comprennent","pr"],["j'ai compris","pc"],["je comprenais","imp"],["je comprendrai","f"],["je comprendrais","c"],["comprends","impv"],["compris","pp"]] },
    { fr:"demander",no:"å spørre / å be om",p:"dəmådæ",forms:[["je demande","pr"],["nous demandons","pr"],["ils demandent","pr"],["j'ai demandé","pc"],["je demandais","imp"],["je demanderai","f"],["je demanderais","c"],["demande","impv"],["demandé","pp"]] },
    { fr:"donner",no:"å gi",p:"donæ",forms:[["je donne","pr"],["nous donnons","pr"],["ils donnent","pr"],["j'ai donné","pc"],["je donnais","imp"],["je donnerai","f"],["je donnerais","c"],["donne","impv"],["donné","pp"]] },
    { fr:"prendre",no:"å ta",p:"pråndrə",forms:[["je prends","pr"],["nous prenons","pr"],["ils prennent","pr"],["j'ai pris","pc"],["je prenais","imp"],["je prendrai","f"],["je prendrais","c"],["prends","impv"],["pris","pp"]] },
    { fr:"mettre",no:"å sette / å legge",p:"mætrə",forms:[["je mets","pr"],["nous mettons","pr"],["ils mettent","pr"],["j'ai mis","pc"],["je mettais","imp"],["je mettrai","f"],["je mettrais","c"],["mets","impv"],["mis","pp"]] },
    { fr:"partir",no:"å dra / å reise",p:"partir",forms:[["je pars","pr"],["nous partons","pr"],["ils partent","pr"],["je suis parti","pc"],["je partais","imp"],["je partirai","f"],["je partirais","c"],["pars","impv"],["parti","pp"]] },
    { fr:"trouver",no:"å finne",p:"truvæ",forms:[["je trouve","pr"],["nous trouvons","pr"],["ils trouvent","pr"],["j'ai trouvé","pc"],["je trouvais","imp"],["je trouverai","f"],["je trouverais","c"],["trouve","impv"],["trouvé","pp"]] },
    { fr:"penser",no:"å tenke",p:"påsæ",forms:[["je pense","pr"],["nous pensons","pr"],["ils pensent","pr"],["j'ai pensé","pc"],["je pensais","imp"],["je penserai","f"],["je penserais","c"],["pense","impv"],["pensé","pp"]] },
    { fr:"croire",no:"å tro",p:"krwar",forms:[["je crois","pr"],["nous croyons","pr"],["ils croient","pr"],["j'ai cru","pc"],["je croyais","imp"],["je croirai","f"],["je croirais","c"],["crois","impv"],["cru","pp"]] },
    { fr:"sentir",no:"å kjenne / å lukte",p:"såtir",forms:[["je sens","pr"],["nous sentons","pr"],["ils sentent","pr"],["j'ai senti","pc"],["je sentais","imp"],["je sentirai","f"],["je sentirais","c"],["sens","impv"],["senti","pp"]] },
    { fr:"entendre",no:"å høre",p:"åtåndrə",forms:[["j'entends","pr"],["nous entendons","pr"],["ils entendent","pr"],["j'ai entendu","pc"],["j'entendais","imp"],["j'entendrai","f"],["j'entendrais","c"],["entends","impv"],["entendu","pp"]] },
    { fr:"rester",no:"å bli / å forbli",p:"ræstæ",forms:[["je reste","pr"],["nous restons","pr"],["ils restent","pr"],["je suis resté","pc"],["je restais","imp"],["je resterai","f"],["je resterais","c"],["reste","impv"],["resté","pp"]] },
    { fr:"arriver",no:"å ankomme / å komme",p:"arivæ",forms:[["j'arrive","pr"],["nous arrivons","pr"],["ils arrivent","pr"],["je suis arrivé","pc"],["j'arrivais","imp"],["j'arriverai","f"],["j'arriverais","c"],["arrive","impv"],["arrivé","pp"]] },
    { fr:"passer",no:"å passere / å tilbringe",p:"pasæ",forms:[["je passe","pr"],["nous passons","pr"],["ils passent","pr"],["j'ai passé","pc"],["je passais","imp"],["je passerai","f"],["je passerais","c"],["passe","impv"],["passé","pp"]] },
    { fr:"jouer",no:"å spille / å leke",p:"sjuæ",forms:[["je joue","pr"],["nous jouons","pr"],["ils jouent","pr"],["j'ai joué","pc"],["je jouais","imp"],["je jouerai","f"],["je jouerais","c"],["joue","impv"],["joué","pp"]] },
    { fr:"travailler",no:"å jobbe / å arbeide",p:"travajæ",forms:[["je travaille","pr"],["nous travaillons","pr"],["ils travaillent","pr"],["j'ai travaillé","pc"],["je travaillais","imp"],["je travaillerai","f"],["je travaillerais","c"],["travaille","impv"],["travaillé","pp"]] },
    { fr:"chercher",no:"å lete etter / å søke",p:"sjærsjæ",forms:[["je cherche","pr"],["nous cherchons","pr"],["ils cherchent","pr"],["j'ai cherché","pc"],["je cherchais","imp"],["je chercherai","f"],["je chercherais","c"],["cherche","impv"],["cherché","pp"]] },
    { fr:"acheter",no:"å kjøpe",p:"asjøtæ",forms:[["j'achète","pr"],["nous achetons","pr"],["ils achètent","pr"],["j'ai acheté","pc"],["j'achetais","imp"],["j'achèterai","f"],["j'achèterais","c"],["achète","impv"],["acheté","pp"]] },
    { fr:"ouvrir",no:"å åpne",p:"uvrir",forms:[["j'ouvre","pr"],["nous ouvrons","pr"],["ils ouvrent","pr"],["j'ai ouvert","pc"],["j'ouvrais","imp"],["j'ouvrirai","f"],["j'ouvrirais","c"],["ouvre","impv"],["ouvert","pp"]] },
    { fr:"fermer",no:"å lukke / å stenge",p:"færmæ",forms:[["je ferme","pr"],["nous fermons","pr"],["ils ferment","pr"],["j'ai fermé","pc"],["je fermais","imp"],["je fermerai","f"],["je fermerais","c"],["ferme","impv"],["fermé","pp"]] },
    { fr:"connaître",no:"å kjenne (noen/noe)",p:"konætrə",forms:[["je connais","pr"],["nous connaissons","pr"],["ils connaissent","pr"],["j'ai connu","pc"],["je connaissais","imp"],["je connaîtrai","f"],["je connaîtrais","c"],["connais","impv"],["connu","pp"]] },
    { fr:"appeler",no:"å ringe / å kalle",p:"aplæ",forms:[["j'appelle","pr"],["nous appelons","pr"],["ils appellent","pr"],["j'ai appelé","pc"],["j'appelais","imp"],["j'appellerai","f"],["j'appellerais","c"],["appelle","impv"],["appelé","pp"]] },
    { fr:"attendre",no:"å vente",p:"atåndrə",forms:[["j'attends","pr"],["nous attendons","pr"],["ils attendent","pr"],["j'ai attendu","pc"],["j'attendais","imp"],["j'attendrai","f"],["j'attendrais","c"],["attends","impv"],["attendu","pp"]] },
    { fr:"commencer",no:"å begynne",p:"komsæ",forms:[["je commence","pr"],["nous commençons","pr"],["ils commencent","pr"],["j'ai commencé","pc"],["je commençais","imp"],["je commencerai","f"],["je commencerais","c"],["commence","impv"],["commencé","pp"]] },
    { fr:"finir",no:"å avslutte / å fullføre",p:"finir",forms:[["je finis","pr"],["nous finissons","pr"],["ils finissent","pr"],["j'ai fini","pc"],["je finissais","imp"],["je finirai","f"],["je finirais","c"],["finis","impv"],["fini","pp"]] },
    { fr:"habiter",no:"å bo",p:"abitæ",forms:[["j'habite","pr"],["nous habitons","pr"],["ils habitent","pr"],["j'ai habité","pc"],["j'habitais","imp"],["j'habiterai","f"],["j'habiterais","c"],["habite","impv"],["habité","pp"]] },
    { fr:"vivre",no:"å leve",p:"vivrə",forms:[["je vis","pr"],["nous vivons","pr"],["ils vivent","pr"],["j'ai vécu","pc"],["je vivais","imp"],["je vivrai","f"],["je vivrais","c"],["vis","impv"],["vécu","pp"]] },
    { fr:"changer",no:"å endre / å bytte",p:"sjåsjæ",forms:[["je change","pr"],["nous changeons","pr"],["ils changent","pr"],["j'ai changé","pc"],["je changeais","imp"],["je changerai","f"],["je changerais","c"],["change","impv"],["changé","pp"]] },
    { fr:"essayer",no:"å prøve",p:"æsæjæ",forms:[["j'essaie","pr"],["nous essayons","pr"],["ils essaient","pr"],["j'ai essayé","pc"],["j'essayais","imp"],["j'essaierai","f"],["j'essaierais","c"],["essaie","impv"],["essayé","pp"]] },
    { fr:"répondre",no:"å svare",p:"repåndrə",forms:[["je réponds","pr"],["nous répondons","pr"],["ils répondent","pr"],["j'ai répondu","pc"],["je répondais","imp"],["je répondrai","f"],["je répondrais","c"],["réponds","impv"],["répondu","pp"]] },
    { fr:"perdre",no:"å miste / å tape",p:"pærdrə",forms:[["je perds","pr"],["nous perdons","pr"],["ils perdent","pr"],["j'ai perdu","pc"],["je perdais","imp"],["je perdrai","f"],["je perdrais","c"],["perds","impv"],["perdu","pp"]] },
    { fr:"gagner",no:"å vinne / å tjene",p:"ganjæ",forms:[["je gagne","pr"],["nous gagnons","pr"],["ils gagnent","pr"],["j'ai gagné","pc"],["je gagnais","imp"],["je gagnerai","f"],["je gagnerais","c"],["gagne","impv"],["gagné","pp"]] },
    { fr:"aider",no:"å hjelpe",p:"ædæ",forms:[["j'aide","pr"],["nous aidons","pr"],["ils aident","pr"],["j'ai aidé","pc"],["j'aidais","imp"],["j'aiderai","f"],["j'aiderais","c"],["aide","impv"],["aidé","pp"]] },
    { fr:"continuer",no:"å fortsette",p:"kåtinuæ",forms:[["je continue","pr"],["nous continuons","pr"],["ils continuent","pr"],["j'ai continué","pc"],["je continuais","imp"],["je continuerai","f"],["je continuerais","c"],["continue","impv"],["continué","pp"]] },
    { fr:"porter",no:"å bære / å ha på seg",p:"portæ",forms:[["je porte","pr"],["nous portons","pr"],["ils portent","pr"],["j'ai porté","pc"],["je portais","imp"],["je porterai","f"],["je porterais","c"],["porte","impv"],["porté","pp"]] },
    { fr:"marcher",no:"å gå / å fungere",p:"marsjæ",forms:[["je marche","pr"],["nous marchons","pr"],["ils marchent","pr"],["j'ai marché","pc"],["je marchais","imp"],["je marcherai","f"],["je marcherais","c"],["marche","impv"],["marché","pp"]] },
    { fr:"courir",no:"å løpe",p:"kurir",forms:[["je cours","pr"],["nous courons","pr"],["ils courent","pr"],["j'ai couru","pc"],["je courais","imp"],["je courrai","f"],["je courrais","c"],["cours","impv"],["couru","pp"]] },
    { fr:"rentrer",no:"å komme hjem / å returnere",p:"råtræ",forms:[["je rentre","pr"],["nous rentrons","pr"],["ils rentrent","pr"],["je suis rentré","pc"],["je rentrais","imp"],["je rentrerai","f"],["je rentrerais","c"],["rentre","impv"],["rentré","pp"]] },
    { fr:"sortir",no:"å gå ut",p:"sortir",forms:[["je sors","pr"],["nous sortons","pr"],["ils sortent","pr"],["je suis sorti","pc"],["je sortais","imp"],["je sortirai","f"],["je sortirais","c"],["sors","impv"],["sorti","pp"]] },
    { fr:"monter",no:"å gå opp / å stige",p:"måtæ",forms:[["je monte","pr"],["nous montons","pr"],["ils montent","pr"],["je suis monté","pc"],["je montais","imp"],["je monterai","f"],["je monterais","c"],["monte","impv"],["monté","pp"]] },
    { fr:"descendre",no:"å gå ned",p:"desåndrə",forms:[["je descends","pr"],["nous descendons","pr"],["ils descendent","pr"],["je suis descendu","pc"],["je descendais","imp"],["je descendrai","f"],["je descendrais","c"],["descends","impv"],["descendu","pp"]] },
    { fr:"sembler",no:"å virke / å synes",p:"såblæ",forms:[["je semble","pr"],["nous semblons","pr"],["ils semblent","pr"],["j'ai semblé","pc"],["je semblais","imp"],["je semblerai","f"],["je semblerais","c"],["semble","impv"],["semblé","pp"]] },
    { fr:"permettre",no:"å tillate",p:"pærmætrə",forms:[["je permets","pr"],["nous permettons","pr"],["ils permettent","pr"],["j'ai permis","pc"],["je permettais","imp"],["je permettrai","f"],["je permettrais","c"],["permets","impv"],["permis","pp"]] },
    { fr:"devoir",no:"å måtte / å skylde",p:"dəvwar",forms:[["je dois","pr"],["nous devons","pr"],["ils doivent","pr"],["j'ai dû","pc"],["je devais","imp"],["je devrai","f"],["je devrais","c"],["dois","impv"],["dû","pp"]] },
    // NOUNS
    { fr:"maison",no:"huset",p:"mæzå",forms:[["la maison","n"],["les maisons","np"]] },
    { fr:"livre",no:"boken",p:"livrə",forms:[["le livre","n"],["les livres","np"]] },
    { fr:"voiture",no:"bilen",p:"vwatyr",forms:[["la voiture","n"],["les voitures","np"]] },
    { fr:"argent",no:"pengene / sølv",p:"arsjå",forms:[["l'argent","n"]] },
    { fr:"travail",no:"arbeidet / jobben",p:"travaj",forms:[["le travail","n"],["les travaux","np"]] },
    { fr:"ville",no:"byen",p:"vil",forms:[["la ville","n"],["les villes","np"]] },
    { fr:"pays",no:"landet",p:"pæi",forms:[["le pays","n"],["les pays","np"]] },
    { fr:"rue",no:"gaten",p:"ry",forms:[["la rue","n"],["les rues","np"]] },
    { fr:"gare",no:"togstasjonen",p:"gar",forms:[["la gare","n"],["les gares","np"]] },
    { fr:"école",no:"skolen",p:"ekol",forms:[["l'école","n"],["les écoles","np"]] },
    { fr:"bibliothèque",no:"biblioteket",p:"biblijotek",forms:[["la bibliothèque","n"],["les bibliothèques","np"]] },
    { fr:"musée",no:"museet",p:"myzæ",forms:[["le musée","n"],["les musées","np"]] },
    { fr:"cinéma",no:"kinoen",p:"sinema",forms:[["le cinéma","n"],["les cinémas","np"]] },
    { fr:"jardin",no:"hagen",p:"sjardæn",forms:[["le jardin","n"],["les jardins","np"]] },
    { fr:"magasin",no:"butikken",p:"magazæn",forms:[["le magasin","n"],["les magasins","np"]] },
    { fr:"bureau",no:"kontoret / skrivebordet",p:"byro",forms:[["le bureau","n"],["les bureaux","np"]] },
    { fr:"appartement",no:"leiligheten",p:"apartəmå",forms:[["l'appartement","n"],["les appartements","np"]] },
    { fr:"chambre",no:"soverommet",p:"sjåbrə",forms:[["la chambre","n"],["les chambres","np"]] },
    { fr:"cuisine",no:"kjøkkenet",p:"kwizin",forms:[["la cuisine","n"],["les cuisines","np"]] },
    { fr:"salon",no:"stuen",p:"salå",forms:[["le salon","n"],["les salons","np"]] },
    { fr:"fenêtre",no:"vinduet",p:"fənætrə",forms:[["la fenêtre","n"],["les fenêtres","np"]] },
    { fr:"porte",no:"døren",p:"port",forms:[["la porte","n"],["les portes","np"]] },
    { fr:"chaise",no:"stolen",p:"sjæz",forms:[["la chaise","n"],["les chaises","np"]] },
    { fr:"table",no:"bordet",p:"tablə",forms:[["la table","n"],["les tables","np"]] },
    { fr:"lit",no:"sengen",p:"li",forms:[["le lit","n"],["les lits","np"]] },
    { fr:"chemin",no:"veien / stien",p:"sjəmæn",forms:[["le chemin","n"],["les chemins","np"]] },
    { fr:"clé",no:"nøkkelen",p:"klæ",forms:[["la clé","n"],["les clés","np"]] },
    { fr:"sac",no:"vesken / sekken",p:"sak",forms:[["le sac","n"],["les sacs","np"]] },
    { fr:"mot",no:"ordet",p:"mo",forms:[["le mot","n"],["les mots","np"]] },
    { fr:"question",no:"spørsmålet",p:"kæstjå",forms:[["la question","n"],["les questions","np"]] },
    { fr:"réponse",no:"svaret",p:"repås",forms:[["la réponse","n"],["les réponses","np"]] },
    { fr:"problème",no:"problemet",p:"problæm",forms:[["le problème","n"],["les problèmes","np"]] },
    { fr:"lumière",no:"lyset",p:"lymjær",forms:[["la lumière","n"],["les lumières","np"]] },
    { fr:"bruit",no:"støyen / lyden",p:"brwi",forms:[["le bruit","n"],["les bruits","np"]] },
    { fr:"quartier",no:"bydelen / nabolaget",p:"kartjæ",forms:[["le quartier","n"],["les quartiers","np"]] },
    { fr:"bâtiment",no:"bygningen",p:"batimå",forms:[["le bâtiment","n"],["les bâtiments","np"]] },
    { fr:"semaine",no:"uken",p:"səmæn",forms:[["la semaine","n"],["les semaines","np"]] },
    { fr:"mois",no:"måneden",p:"mwa",forms:[["le mois","n"],["les mois","np"]] },
    { fr:"printemps",no:"våren",p:"præntå",forms:[["le printemps","n"]] },
    { fr:"été",no:"sommeren",p:"etæ",forms:[["l'été","n"],["les étés","np"]] },
    { fr:"automne",no:"høsten",p:"oton",forms:[["l'automne","n"],["les automnes","np"]] },
    { fr:"hiver",no:"vinteren",p:"ivær",forms:[["l'hiver","n"],["les hivers","np"]] },
    // ADJECTIVES
    { fr:"grand",no:"stor",p:"grå",forms:[["grande","adj-f"],["grands","adj-mp"],["grandes","adj-fp"]] },
    { fr:"petit",no:"liten",p:"pəti",forms:[["petite","adj-f"],["petits","adj-mp"],["petites","adj-fp"]] },
    { fr:"bon",no:"god / bra",p:"bå",forms:[["bonne","adj-f"],["bons","adj-mp"],["bonnes","adj-fp"]] },
    { fr:"mauvais",no:"dårlig / slett",p:"movæ",forms:[["mauvaise","adj-f"],["mauvais","adj-mp"],["mauvaises","adj-fp"]] },
    { fr:"beau",no:"vakker / flott",p:"bo",forms:[["belle","adj-f"],["beaux","adj-mp"],["belles","adj-fp"]] },
    { fr:"nouveau",no:"ny",p:"nuvo",forms:[["nouvelle","adj-f"],["nouveaux","adj-mp"],["nouvelles","adj-fp"]] },
    { fr:"vieux",no:"gammel",p:"vjø",forms:[["vieille","adj-f"],["vieux","adj-mp"],["vieilles","adj-fp"]] },
    { fr:"jeune",no:"ung",p:"sjøn",forms:[["jeune","adj-f"],["jeunes","adj-mp"],["jeunes","adj-fp"]] },
    { fr:"fort",no:"sterk / høy (lyd)",p:"for",forms:[["forte","adj-f"],["forts","adj-mp"],["fortes","adj-fp"]] },
    { fr:"faible",no:"svak",p:"fæblə",forms:[["faible","adj-f"],["faibles","adj-mp"],["faibles","adj-fp"]] },
    { fr:"lent",no:"sakte / langsom",p:"lå",forms:[["lente","adj-f"],["lents","adj-mp"],["lentes","adj-fp"]] },
    { fr:"rapide",no:"rask / hurtig",p:"rapid",forms:[["rapide","adj-f"],["rapides","adj-mp"],["rapides","adj-fp"]] },
    { fr:"facile",no:"lett / enkel",p:"fasil",forms:[["facile","adj-f"],["faciles","adj-mp"],["faciles","adj-fp"]] },
    { fr:"difficile",no:"vanskelig",p:"difisil",forms:[["difficile","adj-f"],["difficiles","adj-mp"],["difficiles","adj-fp"]] },
    { fr:"intéressant",no:"interessant",p:"æntæresså",forms:[["intéressante","adj-f"],["intéressants","adj-mp"],["intéressantes","adj-fp"]] },
    { fr:"ennuyeux",no:"kjedelig",p:"ånwijø",forms:[["ennuyeuse","adj-f"],["ennuyeux","adj-mp"],["ennuyeuses","adj-fp"]] },
    { fr:"content",no:"fornøyd / glad",p:"kåtå",forms:[["contente","adj-f"],["contents","adj-mp"],["contentes","adj-fp"]] },
    { fr:"triste",no:"trist / lei seg",p:"trist",forms:[["triste","adj-f"],["tristes","adj-mp"],["tristes","adj-fp"]] },
    { fr:"fatigué",no:"trøtt",p:"fatigæ",forms:[["fatiguée","adj-f"],["fatigués","adj-mp"],["fatiguées","adj-fp"]] },
    { fr:"malade",no:"syk",p:"malad",forms:[["malade","adj-f"],["malades","adj-mp"],["malades","adj-fp"]] },
    { fr:"propre",no:"ren",p:"proprə",forms:[["propre","adj-f"],["propres","adj-mp"],["propres","adj-fp"]] },
    { fr:"sale",no:"skitten",p:"sal",forms:[["sale","adj-f"],["sales","adj-mp"],["sales","adj-fp"]] },
    { fr:"plein",no:"full",p:"plæn",forms:[["pleine","adj-f"],["pleins","adj-mp"],["pleines","adj-fp"]] },
    { fr:"vide",no:"tom",p:"vid",forms:[["vide","adj-f"],["vides","adj-mp"],["vides","adj-fp"]] },
    { fr:"seul",no:"alene",p:"søl",forms:[["seule","adj-f"],["seuls","adj-mp"],["seules","adj-fp"]] },
    { fr:"vrai",no:"sann / ekte",p:"væ",forms:[["vraie","adj-f"],["vrais","adj-mp"],["vraies","adj-fp"]] },
    { fr:"faux",no:"falsk / feil",p:"fo",forms:[["fausse","adj-f"],["faux","adj-mp"],["fausses","adj-fp"]] },
    // ADVERBS & PHRASES
    { fr:"maintenant",no:"nå",p:"mæntənå",forms:[] },
    { fr:"toujours",no:"alltid",p:"tusjur",forms:[] },
    { fr:"jamais",no:"aldri",p:"sjamæ",forms:[] },
    { fr:"souvent",no:"ofte",p:"suvå",forms:[] },
    { fr:"parfois",no:"noen ganger / av og til",p:"parfwa",forms:[] },
    { fr:"tôt",no:"tidlig",p:"to",forms:[] },
    { fr:"tard",no:"sent",p:"tar",forms:[] },
    { fr:"bientôt",no:"snart",p:"bjænto",forms:[] },
    { fr:"déjà",no:"allerede",p:"dæsja",forms:[] },
    { fr:"encore",no:"ennå / igjen",p:"åkor",forms:[] },
    { fr:"pendant",no:"i løpet av / mens",p:"påndå",forms:[] },
    { fr:"depuis",no:"siden / fra",p:"dəpwi",forms:[] },
    { fr:"hier",no:"i går",p:"jær",forms:[] },
    { fr:"demain",no:"i morgen",p:"dəmæn",forms:[] },
    { fr:"combien",no:"hvor mye / hvor mange",p:"kåbjæn",forms:[] },
    { fr:"assez",no:"nok / ganske",p:"asæ",forms:[] },
    { fr:"trop",no:"for mye / altfor",p:"tro",forms:[] },
    { fr:"peu",no:"lite / litt",p:"pø",forms:[] },
    { fr:"plusieurs",no:"flere",p:"plyzjør",forms:[] },
    { fr:"chaque",no:"hver / hvert",p:"sjak",forms:[] },
    { fr:"rien",no:"ingenting",p:"rjæn",forms:[] },
    { fr:"quelqu'un",no:"noen (person)",p:"kælkøn",forms:[] },
    { fr:"quelque chose",no:"noe",p:"kælkə sjoz",forms:[] },
    { fr:"ensemble",no:"sammen",p:"åsåblə",forms:[] },
    { fr:"peut-être",no:"kanskje",p:"pøtætrə",forms:[] },
    { fr:"bien sûr",no:"selvfølgelig",p:"bjæn syr",forms:[] },
    { fr:"d'abord",no:"først",p:"dabor",forms:[] },
    { fr:"ensuite",no:"deretter / så",p:"åswit",forms:[] },
    { fr:"enfin",no:"til slutt / endelig",p:"åfæn",forms:[] },
    { fr:"donc",no:"altså / derfor",p:"dåk",forms:[] },
    { fr:"quand",no:"når",p:"kå",forms:[] },
    { fr:"comment",no:"hvordan",p:"komå",forms:[] },
    { fr:"pourquoi",no:"hvorfor",p:"purkwa",forms:[] },
    { fr:"parce que",no:"fordi",p:"parskə",forms:[] },
    { fr:"tout le monde",no:"alle / alle sammen",p:"tu lə måd",forms:[] },
    { fr:"surtout",no:"særlig / fremfor alt",p:"syrtu",forms:[] },
    { fr:"d'accord",no:"greit / enig",p:"dakor",forms:[] },
    { fr:"quand même",no:"likevel / allikevel",p:"kå mæm",forms:[] },
    { fr:"en fait",no:"faktisk / egentlig",p:"å fæ",forms:[] },
    { fr:"pourtant",no:"likevel / men allikevel",p:"purtå",forms:[] },
    { fr:"ainsi",no:"slik / på denne måten",p:"æsi",forms:[] },
  ],
  everyday: [
    // RESTAURANT & SHOPPING
    { fr:"restaurant",no:"restauranten",p:"ræstorå",forms:[["le restaurant","n"],["les restaurants","np"]] },
    { fr:"café",no:"kafeen",p:"kafæ",forms:[["le café","n"],["les cafés","np"]] },
    { fr:"carte",no:"menyen / kartet",p:"kart",forms:[["la carte","n"],["les cartes","np"]] },
    { fr:"addition",no:"regningen",p:"adissjå",forms:[["l'addition","n"],["les additions","np"]] },
    { fr:"serveur",no:"kelneren (mann)",p:"særvør",forms:[["le serveur","n"],["les serveurs","np"],["la serveuse","n"]] },
    { fr:"serveuse",no:"kelneren (kvinne)",p:"særvøz",forms:[["la serveuse","n"],["les serveuses","np"]] },
    { fr:"commander",no:"å bestille",p:"komådæ",forms:[["je commande","pr"],["nous commandons","pr"],["ils commandent","pr"],["j'ai commandé","pc"],["je commandais","imp"],["je commanderai","f"],["je commanderais","c"],["commande","impv"],["commandé","pp"]] },
    { fr:"commande",no:"bestillingen",p:"komåd",forms:[["la commande","n"],["les commandes","np"]] },
    { fr:"pourboire",no:"drikkepengene",p:"purboar",forms:[["le pourboire","n"],["les pourboires","np"]] },
    { fr:"payer",no:"å betale",p:"pæjæ",forms:[["je paie","pr"],["nous payons","pr"],["ils paient","pr"],["j'ai payé","pc"],["je payais","imp"],["je paierai","f"],["je paierais","c"],["paie","impv"],["payé","pp"]] },
    { fr:"une table pour deux",no:"et bord for to",p:"yn tablə pur dø",forms:[] },
    { fr:"je voudrais",no:"jeg vil gjerne ha",p:"sjə vudræ",forms:[] },
    { fr:"entrée",no:"forretten",p:"åtræ",forms:[["l'entrée","n"],["les entrées","np"]] },
    { fr:"plat principal",no:"hovedretten",p:"pla præsipal",forms:[["le plat principal","n"],["les plats principaux","np"]] },
    { fr:"dessert",no:"desserten",p:"desær",forms:[["le dessert","n"],["les desserts","np"]] },
    { fr:"un verre de",no:"et glass med",p:"øn vær də",forms:[] },
    { fr:"une bouteille de",no:"en flaske med",p:"yn butæj də",forms:[] },
    { fr:"sans gluten",no:"glutenfri",p:"så glytæn",forms:[] },
    { fr:"végétarien",no:"vegetarisk",p:"vesjætarjæn",forms:[["végétarienne","adj-f"],["végétariens","adj-mp"],["végétariennes","adj-fp"]] },
    { fr:"c'est délicieux",no:"det er deilig",p:"sæ delisjø",forms:[] },
    { fr:"supermarché",no:"supermarkedet",p:"sypærmarsjæ",forms:[["le supermarché","n"],["les supermarchés","np"]] },
    { fr:"boulangerie",no:"bakeriet",p:"bulåsjəri",forms:[["la boulangerie","n"],["les boulangeries","np"]] },
    { fr:"pharmacie",no:"apoteket",p:"farmasi",forms:[["la pharmacie","n"],["les pharmacies","np"]] },
    { fr:"banque",no:"banken",p:"båk",forms:[["la banque","n"],["les banques","np"]] },
    { fr:"poste",no:"postkontoret",p:"post",forms:[["la poste","n"]] },
    { fr:"prix",no:"prisen",p:"pri",forms:[["le prix","n"],["les prix","np"]] },
    { fr:"cher",no:"dyr",p:"sjær",forms:[["chère","adj-f"],["chers","adj-mp"],["chères","adj-fp"]] },
    { fr:"bon marché",no:"billig",p:"bå marsjæ",forms:[] },
    { fr:"taille",no:"størrelsen",p:"taj",forms:[["la taille","n"],["les tailles","np"]] },
    { fr:"pointure",no:"skostørrelsen",p:"pwantyr",forms:[["la pointure","n"],["les pointures","np"]] },
    { fr:"rayon",no:"avdelingen (i butikk)",p:"ræjå",forms:[["le rayon","n"],["les rayons","np"]] },
    { fr:"caisse",no:"kassen",p:"kæs",forms:[["la caisse","n"],["les caisses","np"]] },
    { fr:"ticket de caisse",no:"kvitteringen",p:"tikæ də kæs",forms:[["le ticket de caisse","n"],["les tickets de caisse","np"]] },
    { fr:"réduction",no:"rabatten",p:"rædykssjå",forms:[["la réduction","n"],["les réductions","np"]] },
    { fr:"soldes",no:"salget / utsalg",p:"sold",forms:[["les soldes","np"]] },
    // DIRECTIONS
    { fr:"à gauche",no:"til venstre",p:"a gosjə",forms:[] },
    { fr:"à droite",no:"til høyre",p:"a drwat",forms:[] },
    { fr:"tout droit",no:"rett frem",p:"tu drwa",forms:[] },
    { fr:"près de",no:"nær / i nærheten av",p:"præ də",forms:[] },
    { fr:"loin de",no:"langt fra",p:"loæn də",forms:[] },
    { fr:"à côté de",no:"ved siden av",p:"a kotæ də",forms:[] },
    { fr:"derrière",no:"bak",p:"dærjær",forms:[] },
    { fr:"devant",no:"foran",p:"dəvå",forms:[] },
    { fr:"en face de",no:"overfor / rett overfor",p:"å fas də",forms:[] },
    { fr:"au coin de",no:"i hjørnet av",p:"o koæn də",forms:[] },
    { fr:"carrefour",no:"veikrysset",p:"karfur",forms:[["le carrefour","n"],["les carrefours","np"]] },
    { fr:"traverser",no:"å krysse",p:"traværsæ",forms:[["je traverse","pr"],["nous traversons","pr"],["ils traversent","pr"],["j'ai traversé","pc"],["je traversais","imp"],["je traverserai","f"],["je traverserais","c"],["traverse","impv"],["traversé","pp"]] },
    { fr:"continuer jusqu'à",no:"fortsett til",p:"kåtinuæ sjyska",forms:[] },
    { fr:"tourner",no:"å svinge / å dreie",p:"turnæ",forms:[["je tourne","pr"],["nous tournons","pr"],["ils tournent","pr"],["j'ai tourné","pc"],["je tournais","imp"],["je tournerai","f"],["je tournerais","c"],["tourne","impv"],["tourné","pp"]] },
    // TRANSPORT
    { fr:"métro",no:"T-banen",p:"metro",forms:[["le métro","n"],["les métros","np"]] },
    { fr:"bus",no:"bussen",p:"bys",forms:[["le bus","n"],["les bus","np"]] },
    { fr:"ticket",no:"billetten",p:"tikæ",forms:[["le ticket","n"],["les tickets","np"]] },
    { fr:"quai",no:"perrongen",p:"kæ",forms:[["le quai","n"],["les quais","np"]] },
    { fr:"horaire",no:"ruteplanen",p:"orær",forms:[["l'horaire","n"],["les horaires","np"]] },
    { fr:"retard",no:"forsinkelsen",p:"rətar",forms:[["le retard","n"],["les retards","np"]] },
    { fr:"en retard",no:"forsinket",p:"å rətar",forms:[] },
    { fr:"à l'heure",no:"i tide / presis",p:"a lør",forms:[] },
    { fr:"correspondance",no:"forbindelsen / byttet",p:"korəspådåns",forms:[["la correspondance","n"],["les correspondances","np"]] },
    { fr:"composter",no:"å stemple billetten",p:"kåpostæ",forms:[["je composte","pr"],["nous compostons","pr"],["ils compostent","pr"],["j'ai composté","pc"],["je compostais","imp"],["je composterai","f"],["je composterais","c"],["composte","impv"],["composté","pp"]] },
    { fr:"station",no:"stasjonen",p:"stasjå",forms:[["la station","n"],["les stations","np"]] },
    { fr:"tramway",no:"trikken",p:"tramwæ",forms:[["le tramway","n"],["les tramways","np"]] },
    { fr:"taxi",no:"taxien",p:"taksi",forms:[["le taxi","n"],["les taxis","np"]] },
    // DAILY ROUTINE
    { fr:"se réveiller",no:"å våkne",p:"sə revæjæ",forms:[["je me réveille","pr"],["nous nous réveillons","pr"],["ils se réveillent","pr"],["je me suis réveillé","pc"],["je me réveillais","imp"],["je me réveillerai","f"],["réveille-toi","impv"],["réveillé","pp"]] },
    { fr:"se lever",no:"å stå opp",p:"sə ləvæ",forms:[["je me lève","pr"],["nous nous levons","pr"],["ils se lèvent","pr"],["je me suis levé","pc"],["je me levais","imp"],["je me lèverai","f"],["lève-toi","impv"],["levé","pp"]] },
    { fr:"se doucher",no:"å dusje",p:"sə dusjæ",forms:[["je me douche","pr"],["nous nous douchons","pr"],["ils se douchent","pr"],["je me suis douché","pc"],["je me douchais","imp"],["je me doucherai","f"],["douche-toi","impv"],["douché","pp"]] },
    { fr:"se laver",no:"å vaske seg",p:"sə lavæ",forms:[["je me lave","pr"],["nous nous lavons","pr"],["ils se lavent","pr"],["je me suis lavé","pc"],["je me lavais","imp"],["je me laverai","f"],["lave-toi","impv"],["lavé","pp"]] },
    { fr:"s'habiller",no:"å kle på seg",p:"sabijæ",forms:[["je m'habille","pr"],["nous nous habillons","pr"],["ils s'habillent","pr"],["je me suis habillé","pc"],["je m'habillais","imp"],["je m'habillerai","f"],["habille-toi","impv"],["habillé","pp"]] },
    { fr:"petit-déjeuner",no:"frokosten",p:"pəti dæsjønæ",forms:[["le petit-déjeuner","n"],["les petits-déjeuners","np"]] },
    { fr:"déjeuner",no:"lunsjen",p:"dæsjønæ",forms:[["le déjeuner","n"],["les déjeuners","np"]] },
    { fr:"dîner",no:"middagen / kveldsmaten",p:"dinæ",forms:[["le dîner","n"],["les dîners","np"]] },
    { fr:"se coucher",no:"å legge seg",p:"sə kusjæ",forms:[["je me couche","pr"],["nous nous couchons","pr"],["ils se couchent","pr"],["je me suis couché","pc"],["je me couchais","imp"],["je me coucherai","f"],["couche-toi","impv"],["couché","pp"]] },
    { fr:"dormir",no:"å sove",p:"dormir",forms:[["je dors","pr"],["nous dormons","pr"],["ils dorment","pr"],["j'ai dormi","pc"],["je dormais","imp"],["je dormirai","f"],["je dormirais","c"],["dors","impv"],["dormi","pp"]] },
    { fr:"se brosser les dents",no:"å pusse tennene",p:"sə brosæ læ då",forms:[] },
    { fr:"prendre le bus",no:"ta bussen",p:"pråndrə lə bys",forms:[] },
    { fr:"rentrer à la maison",no:"gå hjem",p:"råtræ a la mæzå",forms:[] },
    { fr:"faire la cuisine",no:"å lage mat",p:"fær la kwizin",forms:[] },
    { fr:"faire les courses",no:"å handle",p:"fær læ kurs",forms:[] },
    // GREETINGS & PHRASES
    { fr:"Bonjour !",no:"God dag! / Hei!",p:"båsjur",forms:[] },
    { fr:"Salut !",no:"Hei! (uformelt)",p:"saly",forms:[] },
    { fr:"Comment allez-vous ?",no:"Hvordan har du det? (formelt)",p:"komå talæ vu",forms:[] },
    { fr:"Comment ça va ?",no:"Hvordan går det?",p:"komå sa va",forms:[] },
    { fr:"Ça va bien",no:"Det går bra",p:"sa va bjæn",forms:[] },
    { fr:"Enchanté(e)",no:"Hyggelig å møte deg",p:"åsjåtæ",forms:[] },
    { fr:"À bientôt",no:"Vi sees snart",p:"a bjænto",forms:[] },
    { fr:"À tout à l'heure",no:"Vi sees straks",p:"a tut a lør",forms:[] },
    { fr:"Allô",no:"Hallo (i telefon)",p:"alo",forms:[] },
    { fr:"Je vous appelle de la part de",no:"Jeg ringer på vegne av",p:"sjə vu zaplə də la par də",forms:[] },
    { fr:"Pouvez-vous rappeler ?",no:"Kan du ringe tilbake?",p:"puvæ vu raplæ",forms:[] },
    { fr:"Ne quittez pas",no:"Ikke legg på / Vent litt",p:"nə kitæ pa",forms:[] },
    // NUMBERS
    { fr:"zéro",no:"null",p:"zero",forms:[] },
    { fr:"un",no:"én / ett",p:"øn",forms:[] },
    { fr:"deux",no:"to",p:"dø",forms:[] },
    { fr:"trois",no:"tre",p:"trwa",forms:[] },
    { fr:"quatre",no:"fire",p:"katrə",forms:[] },
    { fr:"cinq",no:"fem",p:"sænk",forms:[] },
    { fr:"six",no:"seks",p:"sis",forms:[] },
    { fr:"sept",no:"syv",p:"sæt",forms:[] },
    { fr:"huit",no:"åtte",p:"wit",forms:[] },
    { fr:"neuf",no:"ni",p:"nøf",forms:[] },
    { fr:"dix",no:"ti",p:"dis",forms:[] },
    { fr:"vingt",no:"tjue",p:"væn",forms:[] },
    { fr:"trente",no:"tretti",p:"trå",forms:[] },
    { fr:"cent",no:"hundre",p:"så",forms:[] },
    { fr:"mille",no:"tusen",p:"mil",forms:[] },
    // TIME
    { fr:"Il est quelle heure ?",no:"Hva er klokka?",p:"il æ kæl ør",forms:[] },
    { fr:"Il est midi",no:"Klokka er tolv (middag)",p:"il æ midi",forms:[] },
    { fr:"Il est minuit",no:"Klokka er tolv (natt)",p:"il æ minwi",forms:[] },
    { fr:"matin",no:"morgenen",p:"matæn",forms:[["le matin","n"],["les matins","np"]] },
    { fr:"après-midi",no:"ettermiddagen",p:"apræ midi",forms:[["l'après-midi","n"],["les après-midis","np"]] },
    { fr:"soir",no:"kvelden",p:"swar",forms:[["le soir","n"],["les soirs","np"]] },
    { fr:"nuit",no:"natten",p:"nwi",forms:[["la nuit","n"],["les nuits","np"]] },
    { fr:"lundi",no:"mandag",p:"løndi",forms:[] },
    { fr:"mardi",no:"tirsdag",p:"mardi",forms:[] },
    { fr:"mercredi",no:"onsdag",p:"mærkredi",forms:[] },
    { fr:"jeudi",no:"torsdag",p:"sjødi",forms:[] },
    { fr:"vendredi",no:"fredag",p:"vådrədi",forms:[] },
    { fr:"samedi",no:"lørdag",p:"samdi",forms:[] },
    { fr:"dimanche",no:"søndag",p:"dimåsjə",forms:[] },
    { fr:"janvier",no:"januar",p:"sjåvjæ",forms:[] },
    { fr:"février",no:"februar",p:"fevrijæ",forms:[] },
    { fr:"mars",no:"mars",p:"mars",forms:[] },
    { fr:"avril",no:"april",p:"avril",forms:[] },
    { fr:"mai",no:"mai",p:"mæ",forms:[] },
    { fr:"juin",no:"juni",p:"sjwæn",forms:[] },
    { fr:"juillet",no:"juli",p:"sjwijæ",forms:[] },
    { fr:"août",no:"august",p:"u",forms:[] },
    { fr:"septembre",no:"september",p:"sæptåbrə",forms:[] },
    { fr:"octobre",no:"oktober",p:"oktobrə",forms:[] },
    { fr:"novembre",no:"november",p:"novåbrə",forms:[] },
    { fr:"décembre",no:"desember",p:"desåbrə",forms:[] },
    // WEATHER
    { fr:"Il fait beau",no:"Det er fint vær",p:"il fæ bo",forms:[] },
    { fr:"Il pleut",no:"Det regner",p:"il plø",forms:[] },
    { fr:"Il neige",no:"Det snør",p:"il næsjə",forms:[] },
    { fr:"Il fait chaud",no:"Det er varmt",p:"il fæ sjo",forms:[] },
    { fr:"Il fait froid",no:"Det er kaldt",p:"il fæ frwa",forms:[] },
    { fr:"Il y a du vent",no:"Det blåser",p:"il ja dy vå",forms:[] },
    { fr:"nuageux",no:"overskyet",p:"nwasjo",forms:[["nuageuse","adj-f"],["nuageux","adj-mp"],["nuageuses","adj-fp"]] },
    { fr:"ensoleillé",no:"solrikt",p:"åsoljæjæ",forms:[["ensoleillée","adj-f"],["ensoleillés","adj-mp"],["ensoleillées","adj-fp"]] },
    { fr:"orageux",no:"tordenvær",p:"orasjo",forms:[["orageuse","adj-f"],["orageux","adj-mp"],["orageuses","adj-fp"]] },
    { fr:"pluie",no:"regnet",p:"plwi",forms:[["la pluie","n"],["les pluies","np"]] },
    { fr:"neige",no:"snøen",p:"næsjə",forms:[["la neige","n"]] },
    { fr:"soleil",no:"solen",p:"solæj",forms:[["le soleil","n"],["les soleils","np"]] },
    { fr:"température",no:"temperaturen",p:"tåpæratyr",forms:[["la température","n"],["les températures","np"]] },
    { fr:"parapluie",no:"paraplyen",p:"paraplwi",forms:[["le parapluie","n"],["les parapluies","np"]] },
    { fr:"imperméable",no:"regnfrakken",p:"æpærmeable",forms:[["l'imperméable","n"],["les imperméables","np"]] },
    // CITY & TRAVEL
    { fr:"marché",no:"torget / markedet",p:"marsjæ",forms:[["le marché","n"],["les marchés","np"]] },
    { fr:"centre-ville",no:"bysentrum",p:"såtrə vil",forms:[["le centre-ville","n"],["les centres-villes","np"]] },
    { fr:"hôpital",no:"sykehuset",p:"opital",forms:[["l'hôpital","n"],["les hôpitaux","np"]] },
    { fr:"mairie",no:"rådhuset",p:"mæri",forms:[["la mairie","n"],["les mairies","np"]] },
    { fr:"police",no:"politiet",p:"polis",forms:[["la police","n"]] },
    { fr:"toilettes",no:"toalettene",p:"twalæt",forms:[["les toilettes","np"]] },
    { fr:"hôtel",no:"hotellet",p:"otæl",forms:[["l'hôtel","n"],["les hôtels","np"]] },
    { fr:"réserver",no:"å reservere / å bestille",p:"rezærvæ",forms:[["je réserve","pr"],["nous réservons","pr"],["ils réservent","pr"],["j'ai réservé","pc"],["je réservais","imp"],["je réserverai","f"],["je réserverais","c"],["réserve","impv"],["réservé","pp"]] },
    { fr:"passeport",no:"passet",p:"paspor",forms:[["le passeport","n"],["les passeports","np"]] },
    { fr:"valise",no:"kofferten",p:"valiz",forms:[["la valise","n"],["les valises","np"]] },
    { fr:"aéroport",no:"flyplassen",p:"aeroport",forms:[["l'aéroport","n"],["les aéroports","np"]] },
    { fr:"vol",no:"flyturen",p:"vol",forms:[["le vol","n"],["les vols","np"]] },
    { fr:"avion",no:"flyet",p:"avjå",forms:[["l'avion","n"],["les avions","np"]] },
    { fr:"train",no:"toget",p:"træn",forms:[["le train","n"],["les trains","np"]] },
    { fr:"billet",no:"billetten",p:"bijæ",forms:[["le billet","n"],["les billets","np"]] },
    { fr:"aller simple",no:"enkeltbillett",p:"alæ sæplə",forms:[] },
    { fr:"aller-retour",no:"tur-retur billett",p:"alæ rətur",forms:[] },
    { fr:"salle d'attente",no:"venterommet",p:"sal datåt",forms:[["la salle d'attente","n"],["les salles d'attente","np"]] },
    { fr:"office de tourisme",no:"turistkontoret",p:"ofis də turism",forms:[["l'office de tourisme","n"]] },
    { fr:"carte postale",no:"postkort",p:"kart postal",forms:[["la carte postale","n"],["les cartes postales","np"]] },
    { fr:"timbre",no:"frimerke",p:"tæmbrə",forms:[["le timbre","n"],["les timbres","np"]] },
    { fr:"envoyer",no:"å sende",p:"åvwajæ",forms:[["j'envoie","pr"],["nous envoyons","pr"],["ils envoient","pr"],["j'ai envoyé","pc"],["j'envoyais","imp"],["j'enverrai","f"],["j'enverrais","c"],["envoie","impv"],["envoyé","pp"]] },
    { fr:"connexion Wi-Fi",no:"Wi-Fi-tilkoblingen",p:"konækssjå wifi",forms:[["la connexion Wi-Fi","n"]] },
    { fr:"code",no:"koden",p:"kod",forms:[["le code","n"],["les codes","np"]] },
    { fr:"charger le téléphone",no:"lade telefonen",p:"sjarsjæ lə telefon",forms:[] },
    { fr:"application",no:"appen",p:"aplikassjå",forms:[["l'application","n"],["les applications","np"]] },
    { fr:"gratuit",no:"gratis",p:"gratwi",forms:[["gratuite","adj-f"],["gratuits","adj-mp"],["gratuites","adj-fp"]] },
    { fr:"ouvert",no:"åpen",p:"uvær",forms:[["ouverte","adj-f"],["ouverts","adj-mp"],["ouvertes","adj-fp"]] },
    { fr:"fermé",no:"stengt",p:"færmæ",forms:[["fermée","adj-f"],["fermés","adj-mp"],["fermées","adj-fp"]] },
    { fr:"interdit",no:"forbudt",p:"æntærdi",forms:[["interdite","adj-f"],["interdits","adj-mp"],["interdites","adj-fp"]] },
    { fr:"obligatoire",no:"obligatorisk / påkrevd",p:"obligatwar",forms:[["obligatoire","adj-f"],["obligatoires","adj-mp"],["obligatoires","adj-fp"]] },
    { fr:"urgence",no:"nødsituasjonen / akutten",p:"yrsjåns",forms:[["l'urgence","n"],["les urgences","np"]] },
    { fr:"Au secours !",no:"Hjelp!",p:"o səkur",forms:[] },
    { fr:"J'ai besoin d'aide",no:"Jeg trenger hjelp",p:"sjæ bəzoæn dæd",forms:[] },
    // HOUSING
    { fr:"immeuble",no:"bygningen / boligblokken",p:"imøblə",forms:[["l'immeuble","n"],["les immeubles","np"]] },
    { fr:"ascenseur",no:"heisen",p:"asåsør",forms:[["l'ascenseur","n"],["les ascenseurs","np"]] },
    { fr:"couloir",no:"gangen / korridoren",p:"kulwar",forms:[["le couloir","n"],["les couloirs","np"]] },
    { fr:"loyer",no:"husleien",p:"lwajæ",forms:[["le loyer","n"],["les loyers","np"]] },
    { fr:"emménager",no:"å flytte inn",p:"æmenasje",forms:[["j'emménage","pr"],["nous emménageons","pr"],["ils emménagent","pr"],["j'ai emménagé","pc"],["j'emménageais","imp"],["j'emménagerai","f"],["j'emménagerais","c"],["emménage","impv"],["emménagé","pp"]] },
    { fr:"déménager",no:"å flytte ut",p:"demənasjæ",forms:[["je déménage","pr"],["nous déménageons","pr"],["ils déménagent","pr"],["j'ai déménagé","pc"],["je déménageais","imp"],["je déménagerai","f"],["je déménagerais","c"],["déménage","impv"],["déménagé","pp"]] },
    { fr:"voisin",no:"naboen (mann)",p:"vwazæn",forms:[["le voisin","n"],["les voisins","np"],["la voisine","n"]] },
    { fr:"voisine",no:"naboen (kvinne)",p:"vwazin",forms:[["la voisine","n"],["les voisines","np"]] },
    { fr:"poubelle",no:"søppelbøtten",p:"pubæl",forms:[["la poubelle","n"],["les poubelles","np"]] },
    { fr:"courrier",no:"posten / brevet",p:"kurjæ",forms:[["le courrier","n"]] },
    { fr:"boîte aux lettres",no:"postkassen",p:"bwat o lætr",forms:[["la boîte aux lettres","n"],["les boîtes aux lettres","np"]] },
    { fr:"robinet",no:"kranen",p:"robinæ",forms:[["le robinet","n"],["les robinets","np"]] },
    { fr:"douche",no:"dusjen",p:"dusj",forms:[["la douche","n"],["les douches","np"]] },
    { fr:"chauffage",no:"oppvarmingen / varmen",p:"sjofasjə",forms:[["le chauffage","n"]] },
    { fr:"électricité",no:"elektrisiteten",p:"ælæktrisite",forms:[["l'électricité","n"]] },
    { fr:"compteur",no:"måleren",p:"kåtør",forms:[["le compteur","n"],["les compteurs","np"]] },
    { fr:"brancher",no:"å koble til / å plugge inn",p:"bråsjæ",forms:[["je branche","pr"],["nous branchons","pr"],["ils branchent","pr"],["j'ai branché","pc"],["je branchais","imp"],["je brancherai","f"],["je brancherais","c"],["branche","impv"],["branché","pp"]] },
    { fr:"débrancher",no:"å koble fra / å trekke ut",p:"debråsjæ",forms:[["je débranche","pr"],["nous débranchers","pr"],["ils débranchent","pr"],["j'ai débranché","pc"],["je débranchais","imp"],["je débrancherai","f"],["je débrancherais","c"],["débranche","impv"],["débranché","pp"]] },
  ],
  tdf: [
    // RIDERS & ROLES
    { fr:"peloton",no:"feltet (sykkelfeltet)",p:"pəlotå",forms:[["le peloton","n"],["les pelotons","np"]] },
    { fr:"étape",no:"etappen",p:"etap",forms:[["l'étape","n"],["les étapes","np"]] },
    { fr:"col",no:"fjellovergangen",p:"kol",forms:[["le col","n"],["les cols","np"]] },
    { fr:"sprint",no:"spurten",p:"sprænt",forms:[["le sprint","n"],["les sprints","np"]] },
    { fr:"attaque",no:"angrepet",p:"atak",forms:[["l'attaque","n"],["les attaques","np"]] },
    { fr:"attaquer",no:"å angripe / å rykke",p:"atakæ",forms:[["j'attaque","pr"],["nous attaquons","pr"],["ils attaquent","pr"],["j'ai attaqué","pc"],["j'attaquais","imp"],["j'attaquerai","f"],["j'attaquerais","c"],["attaque","impv"],["attaqué","pp"]] },
    { fr:"fuite",no:"utbryterflukten",p:"fwit",forms:[["la fuite","n"],["les fuites","np"]] },
    { fr:"classement",no:"stillingen / klassementet",p:"klasmå",forms:[["le classement","n"],["les classements","np"]] },
    { fr:"grimpeur",no:"klatreren",p:"græmpør",forms:[["le grimpeur","n"],["les grimpeurs","np"]] },
    { fr:"sprinter",no:"spurteren / å spurte",p:"spræntær",forms:[["le sprinter","n"],["les sprinters","np"],["je sprinte","pr"],["nous sprintons","pr"],["ils sprintent","pr"],["j'ai sprinté","pc"],["sprinté","pp"]] },
    { fr:"rouleur",no:"rulleren (god på flate)",p:"rulør",forms:[["le rouleur","n"],["les rouleurs","np"]] },
    { fr:"équipier",no:"lagkameraten / hjelperen",p:"ekipjæ",forms:[["l'équipier","n"],["les équipiers","np"]] },
    { fr:"domestique",no:"hjelperytteren",p:"domestik",forms:[["le domestique","n"],["les domestiques","np"]] },
    { fr:"capitaine de route",no:"lagets vegfører",p:"kapitæn də rut",forms:[["le capitaine de route","n"]] },
    { fr:"leader",no:"lederen",p:"lidær",forms:[["le leader","n"],["les leaders","np"]] },
    { fr:"coureur",no:"rytteren / syklisten",p:"kurør",forms:[["le coureur","n"],["les coureurs","np"]] },
    { fr:"cycliste",no:"syklisten",p:"siklist",forms:[["le cycliste","n"],["les cyclistes","np"]] },
    { fr:"équipe",no:"laget",p:"ekip",forms:[["l'équipe","n"],["les équipes","np"]] },
    { fr:"directeur sportif",no:"sportsdirektøren",p:"diræktør sportif",forms:[["le directeur sportif","n"],["les directeurs sportifs","np"]] },
    { fr:"commissaire",no:"dommeren / kommissæren",p:"komisær",forms:[["le commissaire","n"],["les commissaires","np"]] },
    { fr:"soigneur",no:"massøren / medisinsk personell",p:"swainjør",forms:[["le soigneur","n"],["les soigneurs","np"]] },
    { fr:"mécano",no:"mekanikeren",p:"mekano",forms:[["le mécano","n"],["les mécanoss","np"]] },
    { fr:"vainqueur",no:"vinneren",p:"vænkør",forms:[["le vainqueur","n"],["les vainqueurs","np"]] },
    { fr:"champion",no:"mesteren / vinneren",p:"sjåpjå",forms:[["le champion","n"],["les champions","np"],["la championne","n"]] },
    { fr:"championne",no:"mesteren (kvinne)",p:"sjåpjon",forms:[["la championne","n"],["les championnes","np"]] },
    // BIKE PARTS
    { fr:"vélo",no:"sykkelen",p:"velo",forms:[["le vélo","n"],["les vélos","np"]] },
    { fr:"guidon",no:"styret (på sykkel)",p:"gidå",forms:[["le guidon","n"],["les guidons","np"]] },
    { fr:"selle",no:"sadelen",p:"sæl",forms:[["la selle","n"],["les selles","np"]] },
    { fr:"roue",no:"hjulet",p:"ru",forms:[["la roue","n"],["les roues","np"]] },
    { fr:"chaîne",no:"kjeden",p:"sjæn",forms:[["la chaîne","n"],["les chaînes","np"]] },
    { fr:"dérailleur",no:"girkassetten",p:"derajør",forms:[["le dérailleur","n"],["les dérailleurs","np"]] },
    { fr:"pédale",no:"pedalen",p:"pedal",forms:[["la pédale","n"],["les pédales","np"]] },
    { fr:"frein",no:"bremsen",p:"fræn",forms:[["le frein","n"],["les freins","np"]] },
    { fr:"casque",no:"hjelmen",p:"kask",forms:[["le casque","n"],["les casques","np"]] },
    { fr:"maillot",no:"trøyen",p:"majo",forms:[["le maillot","n"],["les maillots","np"]] },
    { fr:"cuissard",no:"sykkelshortsen",p:"kwissar",forms:[["le cuissard","n"],["les cuissards","np"]] },
    { fr:"bidon",no:"drikkeboksen / flasken",p:"bidå",forms:[["le bidon","n"],["les bidons","np"]] },
    { fr:"sacoche",no:"sykkelveska / sadelbagen",p:"sakosjə",forms:[["la sacoche","n"],["les sacoches","np"]] },
    { fr:"compteur",no:"sykkeldatamaskinen",p:"kåtør",forms:[["le compteur","n"],["les compteurs","np"]] },
    { fr:"GPS",no:"GPSen",p:"sjepees",forms:[["le GPS","n"]] },
    { fr:"oreillette",no:"ørestykket (kommunikasjon)",p:"orəjæt",forms:[["l'oreillette","n"],["les oreillettes","np"]] },
    // JERSEY TYPES
    { fr:"maillot jaune",no:"den gule trøya (sammenlagsleder)",p:"majo sjun",forms:[["le maillot jaune","n"]] },
    { fr:"maillot vert",no:"den grønne trøya (spurter)",p:"majo vær",forms:[["le maillot vert","n"]] },
    { fr:"maillot à pois",no:"den prikkete trøya (klatrer)",p:"majo a pwa",forms:[["le maillot à pois","n"]] },
    { fr:"maillot blanc",no:"den hvite trøya (beste unge)",p:"majo blå",forms:[["le maillot blanc","n"]] },
    // RACE TYPES & TERRAIN
    { fr:"contre-la-montre",no:"tempoetappen",p:"kåtrə la måtrə",forms:[["le contre-la-montre","n"]] },
    { fr:"étape de montagne",no:"fjelleetappen",p:"etap də måtanjə",forms:[["l'étape de montagne","n"]] },
    { fr:"étape de plaine",no:"flatetappen",p:"etap də plæn",forms:[["l'étape de plaine","n"]] },
    { fr:"montagne",no:"fjellet",p:"måtanjə",forms:[["la montagne","n"],["les montagnes","np"]] },
    { fr:"plaine",no:"sletten",p:"plæn",forms:[["la plaine","n"],["les plaines","np"]] },
    { fr:"côte",no:"kneiken / stigningen",p:"kot",forms:[["la côte","n"],["les côtes","np"]] },
    { fr:"sommet",no:"toppen",p:"somæ",forms:[["le sommet","n"],["les sommets","np"]] },
    { fr:"montée",no:"oppstigningen",p:"måtæ",forms:[["la montée","n"],["les montées","np"]] },
    { fr:"descente",no:"nedstigningen / utforbakken",p:"desåt",forms:[["la descente","n"],["les descentes","np"]] },
    { fr:"virage",no:"svingen",p:"virasj",forms:[["le virage","n"],["les virages","np"]] },
    { fr:"lacet",no:"hårnålssving",p:"lasæ",forms:[["le lacet","n"],["les lacets","np"]] },
    { fr:"pente",no:"bakken / hellingen",p:"påt",forms:[["la pente","n"],["les pentes","np"]] },
    { fr:"pavé",no:"brosteinen",p:"pavæ",forms:[["le pavé","n"],["les pavés","np"]] },
    { fr:"chaussée",no:"veibanen",p:"sjosæ",forms:[["la chaussée","n"],["les chaussées","np"]] },
    { fr:"gravier",no:"grusen",p:"gravjæ",forms:[["le gravier","n"]] },
    // RACE ELEMENTS
    { fr:"échappée",no:"utbrytergruppen",p:"lejapæ",forms:[["l'échappée","n"],["les échappées","np"]] },
    { fr:"abandon",no:"utgått av rittet",p:"abådå",forms:[["l'abandon","n"],["les abandons","np"]] },
    { fr:"abandonner",no:"å gi opp / å trekke seg",p:"abådone",forms:[["j'abandonne","pr"],["nous abandonnons","pr"],["ils abandonnent","pr"],["j'ai abandonné","pc"],["j'abandonnais","imp"],["j'abandonnerai","f"],["j'abandonnerais","c"],["abandonne","impv"],["abandonné","pp"]] },
    { fr:"chute",no:"veltet / fallet",p:"sjyt",forms:[["la chute","n"],["les chutes","np"]] },
    { fr:"chuter",no:"å velte / å falle",p:"sjytæ",forms:[["je chute","pr"],["nous chutons","pr"],["ils chutent","pr"],["j'ai chuté","pc"],["je chutais","imp"],["je chuterai","f"],["je chuterais","c"],["chute","impv"],["chuté","pp"]] },
    { fr:"crevaison",no:"punkteringen",p:"krəvæzå",forms:[["la crevaison","n"],["les crevaisonsons","np"]] },
    { fr:"crever",no:"å punktere",p:"krəvæ",forms:[["je crève","pr"],["nous crevons","pr"],["ils crèvent","pr"],["j'ai crevé","pc"],["je crevais","imp"],["je crèverai","f"],["je crèverais","c"],["crève","impv"],["crevé","pp"]] },
    { fr:"ravitaillement",no:"depotet / matinntak underveis",p:"ravitajmå",forms:[["le ravitaillement","n"]] },
    { fr:"zone de ravitaillement",no:"depotsonen",p:"zon də ravitajmå",forms:[["la zone de ravitaillement","n"]] },
    { fr:"départ",no:"starten",p:"depar",forms:[["le départ","n"],["les départs","np"]] },
    { fr:"arrivée",no:"mål / ankomst",p:"arivæ",forms:[["l'arrivée","n"],["les arrivées","np"]] },
    { fr:"ligne d'arrivée",no:"mållinjen",p:"linji darivæ",forms:[["la ligne d'arrivée","n"]] },
    { fr:"ligne de départ",no:"startlinjen",p:"linji də depar",forms:[["la ligne de départ","n"]] },
    { fr:"bordure",no:"kantvindbryteren / echelon",p:"bordyr",forms:[["la bordure","n"],["les bordures","np"]] },
    { fr:"aspiration",no:"slipstrømmen",p:"aspirassjå",forms:[["l'aspiration","n"]] },
    { fr:"braquet",no:"giringen / gjengerforholdet",p:"brakæ",forms:[["le braquet","n"],["les braquets","np"]] },
    { fr:"cadence",no:"tråkkfrekvensen",p:"kadåns",forms:[["la cadence","n"],["les cadences","np"]] },
    { fr:"watt",no:"wattene (effektmål)",p:"wat",forms:[["le watt","n"],["les watts","np"]] },
    { fr:"puissance",no:"kraften / effekten",p:"pwisåns",forms:[["la puissance","n"]] },
    { fr:"forme",no:"formen",p:"form",forms:[["la forme","n"],["les formes","np"]] },
    { fr:"vitesse",no:"farten / hastigheten",p:"vitæs",forms:[["la vitesse","n"],["les vitesses","np"]] },
    { fr:"moyenne",no:"gjennomsnittet",p:"mwajæn",forms:[["la moyenne","n"],["les moyennes","np"]] },
    { fr:"classement général",no:"sammenlagtklassementet",p:"klasmå sjenæral",forms:[["le classement général","n"]] },
    { fr:"podium",no:"podiet",p:"podjom",forms:[["le podium","n"],["les podiums","np"]] },
    { fr:"victoire",no:"seieren",p:"viktoar",forms:[["la victoire","n"],["les victoires","np"]] },
    { fr:"record",no:"rekorden",p:"rəkor",forms:[["le record","n"],["les records","np"]] },
    { fr:"performance",no:"prestasjonen",p:"pærformåns",forms:[["la performance","n"],["les performances","np"]] },
    { fr:"prime",no:"premien / bonusen",p:"prim",forms:[["la prime","n"],["les primes","np"]] },
    { fr:"délai",no:"tidsgrensen",p:"delæ",forms:[["le délai","n"],["les délais","np"]] },
    { fr:"pénalité",no:"boten / straffen",p:"penalitæ",forms:[["la pénalité","n"],["les pénalités","np"]] },
    { fr:"dossard",no:"startnummeret",p:"dossar",forms:[["le dossard","n"],["les dossards","np"]] },
    { fr:"palmarès",no:"merittlisten / seierlisten",p:"palmaræs",forms:[["le palmarès","n"]] },
    { fr:"bonification",no:"bonussekunder",p:"bonifikassjå",forms:[["la bonification","n"],["les bonifications","np"]] },
    { fr:"drapeau à damier",no:"ruteflagget (mål)",p:"drapo a damjæ",forms:[["le drapeau à damier","n"],["les drapeaux à damier","np"]] },
    { fr:"drapeau rouge",no:"det røde flagget (stopp!)",p:"drapo rusjə",forms:[["le drapeau rouge","n"]] },
    { fr:"voiture balai",no:"bilen som plukker opp de siste",p:"vwatyr balæ",forms:[["la voiture balai","n"]] },
    { fr:"voiture suiveuse",no:"følgebilen",p:"vwatyr swivøz",forms:[["la voiture suiveuse","n"]] },
    { fr:"caravane",no:"karavanen",p:"karavan",forms:[["la caravane","n"],["les caravanes","np"]] },
    { fr:"jonction",no:"sammenslåingen / samlingen",p:"sjåksjå",forms:[["la jonction","n"],["les jonctions","np"]] },
    { fr:"exploit",no:"bragden",p:"æksplwa",forms:[["l'exploit","n"],["les exploits","np"]] },
    { fr:"gloire",no:"æren / berømmelsen",p:"gloar",forms:[["la gloire","n"],["les gloires","np"]] },
    { fr:"flamme rouge",no:"den røde flammen (1 km igjen)",p:"flam rusjə",forms:[["la flamme rouge","n"]] },
    { fr:"étape reine",no:"kongeetappen",p:"etap ræn",forms:[["l'étape reine","n"]] },
    // VERBS
    { fr:"pédaler",no:"å tråkke / å sykle",p:"pedalæ",forms:[["je pédale","pr"],["nous pédalons","pr"],["ils pédalent","pr"],["j'ai pédalé","pc"],["je pédalais","imp"],["je pédalerai","f"],["je pédalerais","c"],["pédale","impv"],["pédalé","pp"]] },
    { fr:"grimper",no:"å klatre / å gå oppover",p:"græmpæ",forms:[["je grimpe","pr"],["nous grimpons","pr"],["ils grimpent","pr"],["j'ai grimpé","pc"],["je grimpais","imp"],["je grimperai","f"],["je grimperais","c"],["grimpe","impv"],["grimpé","pp"]] },
    { fr:"s'échapper",no:"å rykke fra / å stikke av",p:"lejapæ",forms:[["je m'échappe","pr"],["nous nous échappons","pr"],["ils s'échappent","pr"],["je me suis échappé","pc"],["je m'échappais","imp"],["je m'échapperai","f"],["échappe-toi","impv"],["échappé","pp"]] },
    { fr:"distancer",no:"å ta avstand / å rykke fra",p:"diståsæ",forms:[["je distance","pr"],["nous distançons","pr"],["ils distancent","pr"],["j'ai distancé","pc"],["je distançais","imp"],["je distancerai","f"],["je distancerais","c"],["distance","impv"],["distancé","pp"]] },
    { fr:"rattraper",no:"å ta igjen",p:"ratrapæ",forms:[["je rattrape","pr"],["nous rattrapons","pr"],["ils rattrapent","pr"],["j'ai rattrapé","pc"],["je rattrapais","imp"],["je rattraperai","f"],["je rattraperais","c"],["rattrape","impv"],["rattrapé","pp"]] },
    { fr:"rouler",no:"å sykle / å kjøre",p:"rulæ",forms:[["je roule","pr"],["nous roulons","pr"],["ils roulent","pr"],["j'ai roulé","pc"],["je roulais","imp"],["je roulerai","f"],["je roulerais","c"],["roule","impv"],["roulé","pp"]] },
    { fr:"franchir",no:"å passere / å krysse",p:"frånsjir",forms:[["je franchis","pr"],["nous franchissons","pr"],["ils franchissent","pr"],["j'ai franchi","pc"],["je franchissais","imp"],["je franchirai","f"],["je franchirais","c"],["franchis","impv"],["franchi","pp"]] },
    { fr:"applaudir",no:"å klappe / å applaudere",p:"aplodir",forms:[["j'applaudis","pr"],["nous applaudissons","pr"],["ils applaudissent","pr"],["j'ai applaudi","pc"],["j'applaudissais","imp"],["j'applaudirai","f"],["j'applaudirais","c"],["applaudis","impv"],["applaudi","pp"]] },
    { fr:"encourager",no:"å heie på / å oppmuntre",p:"åkurasjæ",forms:[["j'encourage","pr"],["nous encourageons","pr"],["ils encouragent","pr"],["j'ai encouragé","pc"],["j'encourageais","imp"],["j'encouragerai","f"],["j'encouragerais","c"],["encourage","impv"],["encouragé","pp"]] },
    { fr:"neutraliser",no:"å nøytralisere (stoppe rittet)",p:"nøtralizæ",forms:[["je neutralise","pr"],["nous neutralisons","pr"],["ils neutralisent","pr"],["j'ai neutralisé","pc"],["je neutralisais","imp"],["je neutraliserai","f"],["je neutraliserais","c"],["neutralise","impv"],["neutralisé","pp"]] },
    { fr:"redémarrer",no:"å starte igjen",p:"rədemarær",forms:[["je redémarre","pr"],["nous redémarrons","pr"],["ils redémarrent","pr"],["j'ai redémarré","pc"],["je redémarrais","imp"],["je redémarrerai","f"],["je redémarrerais","c"],["redémarre","impv"],["redémarré","pp"]] },
    // ADJECTIVES
    { fr:"nerveux",no:"nervøs / spent",p:"nærvø",forms:[["nerveuse","adj-f"],["nerveux","adj-mp"],["nerveuses","adj-fp"]] },
    { fr:"légendaire",no:"legendarisk",p:"lesjådær",forms:[["légendaire","adj-f"],["légendaires","adj-mp"],["légendaires","adj-fp"]] },
    { fr:"historique",no:"historisk",p:"istorik",forms:[["historique","adj-f"],["historiques","adj-mp"],["historiques","adj-fp"]] },
    { fr:"magnifique",no:"strålende / praktfull",p:"manifik",forms:[["magnifique","adj-f"],["magnifiques","adj-mp"],["magnifiques","adj-fp"]] },
    { fr:"impressionnant",no:"imponerende",p:"æmpræsjonå",forms:[["impressionnante","adj-f"],["impressionnants","adj-mp"],["impressionnantes","adj-fp"]] },
    { fr:"combatif",no:"kamplysten / aggressiv",p:"kåbatif",forms:[["combative","adj-f"],["combatifs","adj-mp"],["combatives","adj-fp"]] },
    // FIXED PHRASES
    { fr:"gagner l'étape",no:"vinne etappen",p:"ganjæ letap",forms:[] },
    { fr:"rouler en bordure",no:"kjøre echelon",p:"rulæ å bordyr",forms:[] },
    { fr:"rouler dans la roue",no:"sykle i slipstrømmen",p:"rulæ då la ru",forms:[] },
    { fr:"en grande forme",no:"i toppform",p:"å grå form",forms:[] },
    { fr:"en peloton",no:"i felt",p:"å pəlotå",forms:[] },
    { fr:"en solitaire",no:"alene / solo",p:"å solitær",forms:[] },
    { fr:"hors catégorie",no:"utenfor kategori (vanskeligste klatringa)",p:"or kategori",forms:[] },
    { fr:"hors délai",no:"utenfor tidsskjemaet",p:"or delæ",forms:[] },
    { fr:"lever les bras",no:"å løfte armene (i mål)",p:"ləvæ læ bra",forms:[] },
    { fr:"faire la jonction",no:"å ta igjen / å koble seg på",p:"fær la sjåksjå",forms:[] },
    { fr:"battre un record",no:"å slå en rekord",p:"batrə øn rəkor",forms:[] },
    { fr:"rouler à bloc",no:"å kjøre for fullt",p:"rulæ a blok",forms:[] },
    { fr:"le peloton s'étire",no:"feltet strekker seg ut",p:"lə pəlotå setir",forms:[] },
    { fr:"le Tour est en route",no:"touren er i gang",p:"lə tur æ å rut",forms:[] },
    { fr:"le contre-la-montre par équipes",no:"lagtempo",p:"kåtrə la måtrə par ekip",forms:[] },
    { fr:"changer la roue",no:"å skifte hjul",p:"sjåsjæ la ru",forms:[] },
    { fr:"Allez !",no:"Kom igjen! / Kjør på!",p:"alæ",forms:[] },
    { fr:"Courage !",no:"Stå på! / Ikke gi opp!",p:"kurasjə",forms:[] },
    { fr:"Bravo !",no:"Bravo! / Godt gjort!",p:"bravo",forms:[] },
    // GRAND TOURS & RACES
    { fr:"Tour de France",no:"Tour de France",p:"tur də fråns",forms:[] },
    { fr:"Grande Boucle",no:"den store løkken (kallenavn TdF)",p:"grå buklə",forms:[] },
    { fr:"Giro d'Italia",no:"Giro d'Italia",p:"sjiro ditalia",forms:[] },
    { fr:"Vuelta",no:"Vuelta a España",p:"vuælta",forms:[] },
    { fr:"Paris-Roubaix",no:"Paris-Roubaix (klassiker)",p:"pari rubæ",forms:[] },
    { fr:"Classique",no:"klassikeren (ritt)",p:"klasik",forms:[["la Classique","n"],["les Classiques","np"]] },
    // MOUNTAINS & REGIONS
    { fr:"Alpe d'Huez",no:"Alpe d'Huez (kjent fjell)",p:"alp dyæ",forms:[] },
    { fr:"Mont Ventoux",no:"Mont Ventoux (kjent fjell)",p:"må våtu",forms:[] },
    { fr:"Tourmalet",no:"Tourmalet (kjent pass)",p:"turmale",forms:[] },
    { fr:"Champs-Élysées",no:"Champs-Élysées (avslutning i Paris)",p:"sjåzæliæzæ",forms:[] },
    { fr:"Pyrénées",no:"Pyreneene",p:"pirenæ",forms:[] },
    { fr:"Alpes",no:"Alpene",p:"zalp",forms:[] },
    { fr:"Bretagne",no:"Bretagne (region)",p:"brətanjə",forms:[] },
    { fr:"côte d'azur",no:"Azurkysten",p:"kot dazyr",forms:[] },
    { fr:"Alsace",no:"Alsace (region)",p:"alsas",forms:[] },
    { fr:"Provence",no:"Provence (region)",p:"provåns",forms:[] },
    { fr:"Massif Central",no:"Massif Central (platå)",p:"masif såtral",forms:[] },
    { fr:"Galibier",no:"Galibier (kjent pass)",p:"galibijæ",forms:[] },
    { fr:"Izoard",no:"Izoard (kjent pass)",p:"izwar",forms:[] },
    { fr:"Madeleine",no:"Madeleine (kjent pass)",p:"madlæn",forms:[] },
    { fr:"Télégraphe",no:"Télégraphe (kjent pass)",p:"telegraf",forms:[] },
    // AUDIENCE
    { fr:"public",no:"publikummet",p:"pyblik",forms:[["le public","n"],["les publics","np"]] },
    { fr:"spectateur",no:"tilskueren",p:"spæktator",forms:[["le spectateur","n"],["les spectateurs","np"]] },
    { fr:"prix de la combativité",no:"prisen for kampvilje",p:"pri də la kåbativitæ",forms:[["le prix de la combativité","n"]] },
  ],
  senses: [
    // COLORS
    { fr:"rouge",no:"rød",p:"rusjə",forms:[["rouge","adj-f"],["rouges","adj-mp"],["rouges","adj-fp"]] },
    { fr:"bleu",no:"blå",p:"blø",forms:[["bleue","adj-f"],["bleus","adj-mp"],["bleues","adj-fp"]] },
    { fr:"vert",no:"grønn",p:"vær",forms:[["verte","adj-f"],["verts","adj-mp"],["vertes","adj-fp"]] },
    { fr:"jaune",no:"gul",p:"sjun",forms:[["jaune","adj-f"],["jaunes","adj-mp"],["jaunes","adj-fp"]] },
    { fr:"orange",no:"oransje",p:"orånsjə",forms:[["orange","adj-f"],["orange","adj-mp"],["orange","adj-fp"]] },
    { fr:"violet",no:"lilla / fiolett",p:"vjolæ",forms:[["violette","adj-f"],["violets","adj-mp"],["violettes","adj-fp"]] },
    { fr:"rose",no:"rosa",p:"roz",forms:[["rose","adj-f"],["roses","adj-mp"],["roses","adj-fp"]] },
    { fr:"noir",no:"svart",p:"nwar",forms:[["noire","adj-f"],["noirs","adj-mp"],["noires","adj-fp"]] },
    { fr:"blanc",no:"hvit",p:"blå",forms:[["blanche","adj-f"],["blancs","adj-mp"],["blanches","adj-fp"]] },
    { fr:"gris",no:"grå",p:"gri",forms:[["grise","adj-f"],["gris","adj-mp"],["grises","adj-fp"]] },
    { fr:"brun",no:"brun",p:"bræn",forms:[["brune","adj-f"],["bruns","adj-mp"],["brunes","adj-fp"]] },
    { fr:"beige",no:"beige",p:"bæsjə",forms:[["beige","adj-f"],["beiges","adj-mp"],["beiges","adj-fp"]] },
    { fr:"turquoise",no:"turkis",p:"tyrkwaz",forms:[["turquoise","adj-f"],["turquoise","adj-mp"],["turquoise","adj-fp"]] },
    { fr:"bordeaux",no:"mørkerød / bordeauxfarge",p:"bordo",forms:[["bordeaux","adj-f"],["bordeaux","adj-mp"],["bordeaux","adj-fp"]] },
    { fr:"doré",no:"gyllen",p:"doræ",forms:[["dorée","adj-f"],["dorés","adj-mp"],["dorées","adj-fp"]] },
    { fr:"argenté",no:"sølvfarget",p:"arsjåtæ",forms:[["argentée","adj-f"],["argentés","adj-mp"],["argentées","adj-fp"]] },
    { fr:"ivoire",no:"elfenbensfarget",p:"ivoar",forms:[["ivoire","adj-f"],["ivoire","adj-mp"],["ivoire","adj-fp"]] },
    { fr:"écarlate",no:"skarlagenrød",p:"ekarlat",forms:[["écarlate","adj-f"],["écarlates","adj-mp"],["écarlates","adj-fp"]] },
    { fr:"indigo",no:"indigo",p:"ændigo",forms:[["indigo","adj-f"],["indigo","adj-mp"],["indigo","adj-fp"]] },
    { fr:"ocre",no:"oker (gul-brun farge)",p:"okrə",forms:[["ocre","adj-f"],["ocre","adj-mp"],["ocre","adj-fp"]] },
    // SHAPES
    { fr:"rond",no:"rund",p:"rå",forms:[["ronde","adj-f"],["ronds","adj-mp"],["rondes","adj-fp"]] },
    { fr:"carré",no:"firkantet / kvadratisk",p:"karæ",forms:[["carrée","adj-f"],["carrés","adj-mp"],["carrées","adj-fp"]] },
    { fr:"rectangulaire",no:"rektangulær",p:"ræktångyler",forms:[["rectangulaire","adj-f"],["rectangulaires","adj-mp"],["rectangulaires","adj-fp"]] },
    { fr:"triangulaire",no:"trekantet",p:"trijångylær",forms:[["triangulaire","adj-f"],["triangulaires","adj-mp"],["triangulaires","adj-fp"]] },
    { fr:"ovale",no:"oval",p:"oval",forms:[["ovale","adj-f"],["ovales","adj-mp"],["ovales","adj-fp"]] },
    { fr:"courbé",no:"buet / krum",p:"kurbæ",forms:[["courbée","adj-f"],["courbés","adj-mp"],["courbées","adj-fp"]] },
    { fr:"anguleux",no:"kantet / angular",p:"ågylo",forms:[["anguleuse","adj-f"],["anguleux","adj-mp"],["anguleuses","adj-fp"]] },
    { fr:"étroit",no:"smal",p:"etrwa",forms:[["étroite","adj-f"],["étroits","adj-mp"],["étroites","adj-fp"]] },
    { fr:"large",no:"bred / vid",p:"larsjə",forms:[["large","adj-f"],["larges","adj-mp"],["larges","adj-fp"]] },
    { fr:"épais",no:"tykk",p:"epæ",forms:[["épaisse","adj-f"],["épais","adj-mp"],["épaisses","adj-fp"]] },
    { fr:"mince",no:"tynn / slank",p:"mæns",forms:[["mince","adj-f"],["minces","adj-mp"],["minces","adj-fp"]] },
    { fr:"profond",no:"dyp",p:"profå",forms:[["profonde","adj-f"],["profonds","adj-mp"],["profondes","adj-fp"]] },
    // LIGHT / TEXTURE adjectives
    { fr:"clair",no:"lys / klar",p:"klær",forms:[["claire","adj-f"],["clairs","adj-mp"],["claires","adj-fp"]] },
    { fr:"sombre",no:"mørk",p:"såbrə",forms:[["sombre","adj-f"],["sombres","adj-mp"],["sombres","adj-fp"]] },
    { fr:"brillant",no:"skinnende / blank",p:"brijå",forms:[["brillante","adj-f"],["brillants","adj-mp"],["brillantes","adj-fp"]] },
    { fr:"mat",no:"matt (uten glans)",p:"mat",forms:[["matte","adj-f"],["mats","adj-mp"],["mattes","adj-fp"]] },
    { fr:"lumineux",no:"lysende / lyst",p:"lyminø",forms:[["lumineuse","adj-f"],["lumineux","adj-mp"],["lumineuses","adj-fp"]] },
    { fr:"opaque",no:"ugjennomsiktig",p:"opak",forms:[["opaque","adj-f"],["opaques","adj-mp"],["opaques","adj-fp"]] },
    { fr:"transparent",no:"gjennomsiktig",p:"tråsparå",forms:[["transparente","adj-f"],["transparents","adj-mp"],["transparentes","adj-fp"]] },
    { fr:"scintillant",no:"glitrende / funklende",p:"sæntijå",forms:[["scintillante","adj-f"],["scintillants","adj-mp"],["scintillantes","adj-fp"]] },
    { fr:"doux",no:"myk / mild",p:"du",forms:[["douce","adj-f"],["doux","adj-mp"],["douces","adj-fp"]] },
    { fr:"rugueux",no:"ru / grov (overflate)",p:"rygo",forms:[["rugueuse","adj-f"],["rugueux","adj-mp"],["rugueuses","adj-fp"]] },
    { fr:"lisse",no:"glatt / jevn",p:"lis",forms:[["lisse","adj-f"],["lisses","adj-mp"],["lisses","adj-fp"]] },
    { fr:"dur",no:"hard",p:"dyr",forms:[["dure","adj-f"],["durs","adj-mp"],["dures","adj-fp"]] },
    { fr:"mou",no:"myk / bløt",p:"mu",forms:[["molle","adj-f"],["mous","adj-mp"],["molles","adj-fp"]] },
    { fr:"granuleux",no:"kornete / grovkornet",p:"granylø",forms:[["granuleuse","adj-f"],["granuleux","adj-mp"],["granuleuses","adj-fp"]] },
    { fr:"collant",no:"klissete / klebrig",p:"kolå",forms:[["collante","adj-f"],["collants","adj-mp"],["collantes","adj-fp"]] },
    // SOUND nouns
    { fr:"bruit",no:"støyen / lyden",p:"brwi",forms:[["le bruit","n"],["les bruits","np"]] },
    { fr:"silence",no:"stillheten",p:"silåns",forms:[["le silence","n"],["les silences","np"]] },
    { fr:"son",no:"lyden / tonen",p:"så",forms:[["le son","n"],["les sons","np"]] },
    { fr:"mélodie",no:"melodien",p:"melodyi",forms:[["la mélodie","n"],["les mélodies","np"]] },
    { fr:"rythme",no:"rytmen",p:"ritm",forms:[["le rythme","n"],["les rythmes","np"]] },
    // SOUND adjectives
    { fr:"fort",no:"høy (lyd) / sterk",p:"for",forms:[["forte","adj-f"],["forts","adj-mp"],["fortes","adj-fp"]] },
    { fr:"faible",no:"svak / lav (lyd)",p:"fæblə",forms:[["faible","adj-f"],["faibles","adj-mp"],["faibles","adj-fp"]] },
    { fr:"aigu",no:"høyfrekvent / skarp",p:"egu",forms:[["aiguë","adj-f"],["aigus","adj-mp"],["aiguës","adj-fp"]] },
    { fr:"grave",no:"lavfrekvent / dyp (lyd)",p:"grav",forms:[["grave","adj-f"],["graves","adj-mp"],["graves","adj-fp"]] },
    { fr:"sourd",no:"dempet / hul (lyd)",p:"sur",forms:[["sourde","adj-f"],["sourds","adj-mp"],["sourdes","adj-fp"]] },
    { fr:"strident",no:"skjærende / skingrende",p:"stridå",forms:[["stridente","adj-f"],["stridants","adj-mp"],["stridantes","adj-fp"]] },
    // SMELL / TASTE nouns
    { fr:"odeur",no:"lukten",p:"odør",forms:[["l'odeur","n"],["les odeurs","np"]] },
    { fr:"parfum",no:"parfymen / duften",p:"parfæn",forms:[["le parfum","n"],["les parfums","np"]] },
    { fr:"saveur",no:"smaken / smaksnoten",p:"savør",forms:[["la saveur","n"],["les saveurs","np"]] },
    { fr:"goût",no:"smaken",p:"gu",forms:[["le goût","n"],["les goûts","np"]] },
    // SMELL / TASTE adjectives
    { fr:"floral",no:"blomsterduftende",p:"floral",forms:[["florale","adj-f"],["floraux","adj-mp"],["florales","adj-fp"]] },
    { fr:"musqué",no:"moskusduftende",p:"myskæ",forms:[["musquée","adj-f"],["musqués","adj-mp"],["musquées","adj-fp"]] },
    { fr:"frais",no:"frisk / kjølig",p:"fræ",forms:[["fraîche","adj-f"],["frais","adj-mp"],["fraîches","adj-fp"]] },
    { fr:"rance",no:"harsk",p:"råns",forms:[["rance","adj-f"],["rances","adj-mp"],["rances","adj-fp"]] },
    { fr:"fumé",no:"røkt / røykaktig",p:"fymæ",forms:[["fumée","adj-f"],["fumés","adj-mp"],["fumées","adj-fp"]] },
    { fr:"sucré",no:"søt",p:"sykræ",forms:[["sucrée","adj-f"],["sucrés","adj-mp"],["sucrées","adj-fp"]] },
    { fr:"salé",no:"salt",p:"salæ",forms:[["salée","adj-f"],["salés","adj-mp"],["salées","adj-fp"]] },
    { fr:"amer",no:"bitter",p:"amær",forms:[["amère","adj-f"],["amers","adj-mp"],["amères","adj-fp"]] },
    { fr:"acide",no:"sur / syrlig",p:"asid",forms:[["acide","adj-f"],["acides","adj-mp"],["acides","adj-fp"]] },
    { fr:"piquant",no:"sterk / pikant / krydret",p:"pikå",forms:[["piquante","adj-f"],["piquants","adj-mp"],["piquantes","adj-fp"]] },
    { fr:"fade",no:"smakløs / kraftløs",p:"fad",forms:[["fade","adj-f"],["fades","adj-mp"],["fades","adj-fp"]] },
    { fr:"relevé",no:"krydret / sterk i smaken",p:"rəlvæ",forms:[["relevée","adj-f"],["relevés","adj-mp"],["relevées","adj-fp"]] },
    // SENSE PERCEPTION nouns
    { fr:"couleur",no:"fargen",p:"kulør",forms:[["la couleur","n"],["les couleurs","np"]] },
    { fr:"forme",no:"formen",p:"form",forms:[["la forme","n"],["les formes","np"]] },
    { fr:"texture",no:"teksturen",p:"tækstyr",forms:[["la texture","n"],["les textures","np"]] },
    { fr:"lumière",no:"lyset",p:"lymjær",forms:[["la lumière","n"],["les lumières","np"]] },
    { fr:"ombre",no:"skyggen",p:"åmbrə",forms:[["l'ombre","n"],["les ombres","np"]] },
    { fr:"contraste",no:"kontrasten",p:"kåtrast",forms:[["le contraste","n"],["les contrastes","np"]] },
    // SENSE VERBS
    { fr:"voir",no:"å se",p:"vwar",forms:[["je vois","pr"],["nous voyons","pr"],["ils voient","pr"],["j'ai vu","pc"],["je voyais","imp"],["je verrai","f"],["je verrais","c"],["vois","impv"],["vu","pp"]] },
    { fr:"entendre",no:"å høre",p:"åtåndrə",forms:[["j'entends","pr"],["nous entendons","pr"],["ils entendent","pr"],["j'ai entendu","pc"],["j'entendais","imp"],["j'entendrai","f"],["j'entendrais","c"],["entends","impv"],["entendu","pp"]] },
    { fr:"sentir",no:"å lukte / å kjenne",p:"såtir",forms:[["je sens","pr"],["nous sentons","pr"],["ils sentent","pr"],["j'ai senti","pc"],["je sentais","imp"],["je sentirai","f"],["je sentirais","c"],["sens","impv"],["senti","pp"]] },
    { fr:"toucher",no:"å ta på / å berøre",p:"tusjæ",forms:[["je touche","pr"],["nous touchons","pr"],["ils touchent","pr"],["j'ai touché","pc"],["je touchais","imp"],["je toucherai","f"],["je toucherais","c"],["touche","impv"],["touché","pp"]] },
    { fr:"goûter",no:"å smake",p:"gutæ",forms:[["je goûte","pr"],["nous goûtons","pr"],["ils goûtent","pr"],["j'ai goûté","pc"],["je goûtais","imp"],["je goûterai","f"],["je goûterais","c"],["goûte","impv"],["goûté","pp"]] },
    { fr:"écouter",no:"å lytte",p:"ekutæ",forms:[["j'écoute","pr"],["nous écoutons","pr"],["ils écoutent","pr"],["j'ai écouté","pc"],["j'écoutais","imp"],["j'écouterai","f"],["j'écouterais","c"],["écoute","impv"],["écouté","pp"]] },
    { fr:"regarder",no:"å se på / å betrakte",p:"rəgardæ",forms:[["je regarde","pr"],["nous regardons","pr"],["ils regardent","pr"],["j'ai regardé","pc"],["je regardais","imp"],["je regarderai","f"],["je regarderais","c"],["regarde","impv"],["regardé","pp"]] },
    { fr:"observer",no:"å observere / å iaktta",p:"obsærvæ",forms:[["j'observe","pr"],["nous observons","pr"],["ils observent","pr"],["j'ai observé","pc"],["j'observais","imp"],["j'observerai","f"],["j'observerais","c"],["observe","impv"],["observé","pp"]] },
    // MORE COLOR / TEXTURE adjectives
    { fr:"vif",no:"livlig / sterk (om farge)",p:"vif",forms:[["vive","adj-f"],["vifs","adj-mp"],["vives","adj-fp"]] },
    { fr:"pâle",no:"blek / lys",p:"pal",forms:[["pâle","adj-f"],["pâles","adj-mp"],["pâles","adj-fp"]] },
    { fr:"foncé",no:"mørk (nyanse)",p:"fåsæ",forms:[["foncée","adj-f"],["foncés","adj-mp"],["foncées","adj-fp"]] },
    { fr:"nuancé",no:"nyansert",p:"nwåsæ",forms:[["nuancée","adj-f"],["nuancés","adj-mp"],["nuancées","adj-fp"]] },
    { fr:"terne",no:"mattgrå / kjedelig (om farge)",p:"tærn",forms:[["terne","adj-f"],["ternes","adj-mp"],["ternes","adj-fp"]] },
    { fr:"chatoyant",no:"skiftende / iriserende",p:"sjatojå",forms:[["chatoyante","adj-f"],["chatoyants","adj-mp"],["chatoyantes","adj-fp"]] },
    { fr:"soyeux",no:"silkemyk",p:"swajø",forms:[["soyeuse","adj-f"],["soyeux","adj-mp"],["soyeuses","adj-fp"]] },
    { fr:"craquant",no:"sprø / knasende",p:"krakå",forms:[["craquante","adj-f"],["craquants","adj-mp"],["craquantes","adj-fp"]] },
    { fr:"crémeux",no:"kremet",p:"kremø",forms:[["crémeuse","adj-f"],["crémeux","adj-mp"],["crémeuses","adj-fp"]] },
    { fr:"épicé",no:"krydret / sterk",p:"episæ",forms:[["épicée","adj-f"],["épicés","adj-mp"],["épicées","adj-fp"]] },
    { fr:"aigre",no:"sur / skarp i smaken",p:"ægrə",forms:[["aigre","adj-f"],["aigres","adj-mp"],["aigres","adj-fp"]] },
    { fr:"pétillant",no:"brusende / musserende",p:"petijå",forms:[["pétillante","adj-f"],["pétillants","adj-mp"],["pétillantes","adj-fp"]] },
    { fr:"envoûtant",no:"fortryllende",p:"åvutå",forms:[["envoûtante","adj-f"],["envoûtants","adj-mp"],["envoûtantes","adj-fp"]] },
    { fr:"nauséabond",no:"kvalmende",p:"nozeabå",forms:[["nauséabonde","adj-f"],["nauséabonds","adj-mp"],["nauséabondes","adj-fp"]] },
    { fr:"velouté",no:"fløyelsmyk / silkeglatt",p:"vəlutæ",forms:[["veloutée","adj-f"],["veloutés","adj-mp"],["veloutées","adj-fp"]] },
    // SENSE PHRASES
    { fr:"le sens du toucher",no:"berøringssansen",p:"lə såns dy tusjæ",forms:[] },
    { fr:"le sens de la vue",no:"synet",p:"lə såns də la vy",forms:[] },
    { fr:"le sens de l'ouïe",no:"hørselen",p:"lə såns də lwi",forms:[] },
    { fr:"le sens de l'odorat",no:"luktesansen",p:"lə såns də lodora",forms:[] },
    { fr:"le sens du goût",no:"smakssansen",p:"lə såns dy gu",forms:[] },
  ],
  food: [
    { fr: "le poulet", no: "kyllingen", phonetic: "lə pulæ" },
    { fr: "le bœuf", no: "oksekjøttet", phonetic: "lə bøf" },
    { fr: "le porc", no: "svinekjøttet", phonetic: "lə por" },
    { fr: "l'agneau", no: "lammekjøttet", phonetic: "lanjo" },
    { fr: "le veau", no: "kalvekjøttet", phonetic: "lə vo" },
    { fr: "le lapin", no: "kaninen / kaninekjøttet", phonetic: "lə lapæn" },
    { fr: "le canard", no: "anden / andekjøttet", phonetic: "lə kanar" },
    { fr: "la dinde", no: "kalkunen", phonetic: "la dænd" },
    { fr: "les lardons", no: "baconbitene / strimlet bacon", phonetic: "læ lardå" },
    { fr: "le saucisson", no: "spekepølsen", phonetic: "lə sosisså" },
    { fr: "la saucisse", no: "pølsen", phonetic: "la sosis" },
    { fr: "le jambon", no: "skinken", phonetic: "lə sjåbå" },
    { fr: "le pâté", no: "patéen", phonetic: "lə patæ" },
    { fr: "le saumon", no: "laksenen", phonetic: "lə somå" },
    { fr: "le thon", no: "tunfisken", phonetic: "lə tå" },
    { fr: "le cabillaud", no: "torsken", phonetic: "lə kabijo" },
    { fr: "la sole", no: "sjøtungen (fisk)", phonetic: "la sol" },
    { fr: "les crevettes", no: "rekene", phonetic: "læ krəvæt" },
    { fr: "les moules", no: "muslingene / blåskjellene", phonetic: "læ mul" },
    { fr: "les huîtres", no: "østersene", phonetic: "læ witrə" },
    { fr: "le homard", no: "hummeren", phonetic: "lə omar" },
    { fr: "les sardines", no: "sardinene", phonetic: "læ sardin" },
    { fr: "la truite", no: "ørreten", phonetic: "la trwit" },
    { fr: "les anchois", no: "ansjoserene", phonetic: "læ zåsjwa" },
    { fr: "le bar", no: "havabboren", phonetic: "lə bar" },
    { fr: "la carotte", no: "gulroten", phonetic: "la karot" },
    { fr: "la pomme de terre", no: "poteten", phonetic: "la pom də tær" },
    { fr: "l'oignon", no: "løken", phonetic: "lonjå" },
    { fr: "l'ail", no: "hvitløken", phonetic: "laj" },
    { fr: "la tomate", no: "tomaten", phonetic: "la tomat" },
    { fr: "la laitue", no: "isbergsalaten", phonetic: "la læty" },
    { fr: "le brocoli", no: "brokkolien", phonetic: "lə brokoli" },
    { fr: "les haricots verts", no: "grønne bønner", phonetic: "læ ariko vær" },
    { fr: "le poivron", no: "paprikaen", phonetic: "lə pwavrå" },
    { fr: "le champignon", no: "soppen", phonetic: "lə sjåpinjå" },
    { fr: "la courgette", no: "squashen / zucchini", phonetic: "la kursjæt" },
    { fr: "l'aubergine", no: "auberginen", phonetic: "lobærsjin" },
    { fr: "le poireau", no: "purren", phonetic: "lə pwaro" },
    { fr: "les épinards", no: "spinaten", phonetic: "læ zepinat" },
    { fr: "les petits pois", no: "ertene", phonetic: "læ pəti pwa" },
    { fr: "le navet", no: "nepe", phonetic: "lə navæ" },
    { fr: "le céleri", no: "sellerien", phonetic: "lə selri" },
    { fr: "l'artichaut", no: "artisjokken", phonetic: "lartisjo" },
    { fr: "le concombre", no: "agurken", phonetic: "lə kåkåbrə" },
    { fr: "la betterave", no: "rødbeten", phonetic: "la bætrав" },
    { fr: "la pomme", no: "eplet", phonetic: "la pom" },
    { fr: "la poire", no: "pæren", phonetic: "la pwar" },
    { fr: "le raisin", no: "druen", phonetic: "lə ræzæn" },
    { fr: "la fraise", no: "jordbæret", phonetic: "la fræz" },
    { fr: "la cerise", no: "kirsebæret", phonetic: "la səriz" },
    { fr: "l'orange", no: "appelsinen", phonetic: "lorånsjə" },
    { fr: "le citron", no: "sitronen", phonetic: "lə sitrå" },
    { fr: "la pêche", no: "fersken", phonetic: "la pæsjə" },
    { fr: "l'abricot", no: "aprikosen", phonetic: "labriko" },
    { fr: "le melon", no: "melonen", phonetic: "lə məlå" },
    { fr: "la framboise", no: "bringebæret", phonetic: "la fråbwaz" },
    { fr: "la myrtille", no: "blåbæret", phonetic: "la mirtij" },
    { fr: "la banane", no: "bananen", phonetic: "la banan" },
    { fr: "l'ananas", no: "ananassen", phonetic: "lanana" },
    { fr: "la mangue", no: "mangoen", phonetic: "la måg" },
    { fr: "le kiwi", no: "kiwien", phonetic: "lə kiwi" },
    { fr: "la prune", no: "plommen", phonetic: "la pryn" },
    { fr: "le fromage", no: "osten", phonetic: "lə fromasj" },
    { fr: "le beurre", no: "smøret", phonetic: "lə bør" },
    { fr: "la crème", no: "fløten", phonetic: "la kræm" },
    { fr: "le lait", no: "melken", phonetic: "lə læ" },
    { fr: "le yaourt", no: "yoghurten", phonetic: "lə jaurt" },
    { fr: "les œufs", no: "eggene", phonetic: "læ zo" },
    { fr: "le gruyère", no: "gruyère-osten", phonetic: "lə gryjær" },
    { fr: "le brie", no: "brie-osten", phonetic: "lə bri" },
    { fr: "le camembert", no: "camembert-osten", phonetic: "lə kamåbær" },
    { fr: "le roquefort", no: "roquefort-osten", phonetic: "lə rokfor" },
    { fr: "la crème fraîche", no: "crème fraîche / rømme", phonetic: "la kræm fræsjə" },
    { fr: "le pain", no: "brødet", phonetic: "lə pæn" },
    { fr: "la baguette", no: "baguetten", phonetic: "la bagæt" },
    { fr: "la farine", no: "melet", phonetic: "la farin" },
    { fr: "le sucre", no: "sukkeret", phonetic: "lə sykrə" },
    { fr: "le sel", no: "saltet", phonetic: "lə sæl" },
    { fr: "le poivre", no: "pepperet", phonetic: "lə pwavrə" },
    { fr: "l'huile", no: "oljen", phonetic: "lwil" },
    { fr: "le vinaigre", no: "eddiken", phonetic: "lə vinægrə" },
    { fr: "les herbes", no: "urtene", phonetic: "læ zærb" },
    { fr: "les épices", no: "krydderne", phonetic: "læ zepis" },
    { fr: "le riz", no: "risen", phonetic: "lə ri" },
    { fr: "les pâtes", no: "pastaen", phonetic: "læ pat" },
    { fr: "les lentilles", no: "linsene", phonetic: "læ låtij" },
    { fr: "la moutarde", no: "sennepen", phonetic: "la mutard" },
    { fr: "le miel", no: "honningen", phonetic: "lə mjæl" },
    { fr: "la confiture", no: "syltetøyet", phonetic: "la kåfityr" },
    { fr: "cuire", no: "å koke / å tilberede", phonetic: "kwir" },
    { fr: "bouillir", no: "å koke (vann)", phonetic: "bujir" },
    { fr: "frire", no: "å fritere / å steke i olje", phonetic: "frir" },
    { fr: "griller", no: "å grille", phonetic: "grijæ" },
    { fr: "rôtir", no: "å steke i ovn", phonetic: "rotir" },
    { fr: "mijoter", no: "å småkoke / å putre", phonetic: "misjotæ" },
    { fr: "couper", no: "å kutte / å skjære", phonetic: "kupæ" },
    { fr: "hacher", no: "å hakke", phonetic: "asjæ" },
    { fr: "mélanger", no: "å blande / å røre", phonetic: "melåsjæ" },
    { fr: "assaisonner", no: "å krydre / å smake til", phonetic: "asæzonæ" },
    { fr: "faire revenir", no: "å steke lett / å surre", phonetic: "fær rəvənir" },
    { fr: "éplucher", no: "å skrelle", phonetic: "eplysjæ" },
    { fr: "râper", no: "å rive (ost etc.)", phonetic: "rapæ" },
    { fr: "émincer", no: "å skjære i tynne skiver", phonetic: "emænsæ" },
    { fr: "faire mariner", no: "å marinere", phonetic: "fær marinæ" },
    { fr: "la casserole", no: "kjelen / gryta", phonetic: "la kasrol" },
    { fr: "la poêle", no: "stekepanna", phonetic: "la pwal" },
    { fr: "le four", no: "ovnen", phonetic: "lə fur" },
    { fr: "le couteau", no: "kniven", phonetic: "lə kuto" },
    { fr: "la planche à découper", no: "fjøla", phonetic: "la plåsjə a dekupæ" },
    { fr: "le saladier", no: "salatbollen", phonetic: "lə saladjæ" },
    { fr: "la passoire", no: "silen / dørslaget", phonetic: "la pasoar" },
    { fr: "le fouet", no: "vispen", phonetic: "lə fuæ" },
    { fr: "la spatule", no: "spatelen / stekespaden", phonetic: "la spatyl" },
    { fr: "la louche", no: "øsen / suppeskjeen", phonetic: "la lusjə" },
    { fr: "la soupe", no: "suppen", phonetic: "la sup" },
    { fr: "la salade", no: "salaten", phonetic: "la salad" },
    { fr: "l'omelette", no: "omeletten", phonetic: "lomælet" },
    { fr: "la quiche", no: "quichen", phonetic: "la kisjə" },
    { fr: "la ratatouille", no: "ratatouille (grønnsaksgryterett)", phonetic: "la ratatuj" },
    { fr: "le coq au vin", no: "coq au vin (kylling i vin)", phonetic: "lə kok o væn" },
    { fr: "le bœuf bourguignon", no: "bœuf bourguignon (okse i rødvin)", phonetic: "lə bøf burginjå" },
    { fr: "la crêpe", no: "pannekaken", phonetic: "la kræp" },
    { fr: "la tarte", no: "terten", phonetic: "la tart" },
    { fr: "la mousse au chocolat", no: "sjokolademousse", phonetic: "la mus o sjokola" },
    { fr: "la tartiflette", no: "tartiflette (potet og osteform)", phonetic: "la tartiflet" },
    { fr: "le gratin dauphinois", no: "potetskinke (gratin)", phonetic: "lə gratæn dofinwa" },
    { fr: "la bouillabaisse", no: "bouillabaisse (fiskesuppe)", phonetic: "la bujabæs" },
    { fr: "le cassoulet", no: "cassoulet (bønnegryte)", phonetic: "lə kasuæ" },
    { fr: "la blanquette de veau", no: "blanquette de veau (kalvegryte)", phonetic: "la blåkæt də vo" },
    { fr: "le pot-au-feu", no: "pot-au-feu (kokt kjøtt og grønnsaker)", phonetic: "lə pot o fø" },
    { fr: "l'eau", no: "vannet", phonetic: "lo" },
    { fr: "le vin", no: "vinen", phonetic: "lə væn" },
    { fr: "la bière", no: "ølet", phonetic: "la bjær" },
    { fr: "le jus", no: "juicen", phonetic: "lə sjy" },
    { fr: "le café", no: "kaffen", phonetic: "lə kafæ" },
    { fr: "le thé", no: "teen", phonetic: "lə tæ" },
    { fr: "le champagne", no: "champagnen", phonetic: "lə sjåpanjə" },
    { fr: "le cidre", no: "eplesidervinen / cidren", phonetic: "lə sidrə" },
    { fr: "l'eau minérale", no: "mineralvannet", phonetic: "lo mineral" },
    { fr: "le sirop", no: "sirupen", phonetic: "lə siro" },
    { fr: "le vin rouge", no: "rødvinen", phonetic: "lə væn rusjə" },
    { fr: "le vin blanc", no: "hvitvinen", phonetic: "lə væn blå" },
    { fr: "le vin rosé", no: "rosévinen", phonetic: "lə væn rozæ" },
    { fr: "l'apéritif", no: "aperitifen", phonetic: "laperitif" },
    { fr: "le digestif", no: "digestiven", phonetic: "lə disjæstif" },
    { fr: "l'entrée", no: "forretten", phonetic: "låtræ" },
    { fr: "le plat du jour", no: "dagens rett", phonetic: "lə pla dy sjur" },
    { fr: "le menu", no: "menyen / setmenyen", phonetic: "lə məny" },
    { fr: "la recette", no: "oppskriften", phonetic: "la rəsæt" },
    { fr: "les ingrédients", no: "ingrediensene", phonetic: "læ zægrediå" },
    { fr: "la portion", no: "porsjonen", phonetic: "la porssjå" },
    { fr: "la garniture", no: "tilbehøret / pynt", phonetic: "la garnityr" },
    { fr: "la sauce", no: "sausen", phonetic: "la sos" },
    { fr: "la vinaigrette", no: "vinaigrettedressingen", phonetic: "la vinægræt" },
    { fr: "la béchamel", no: "béchamelsausen", phonetic: "la besjamæl" },
    { fr: "le bouillon", no: "kraftkoket / buljongen", phonetic: "lə bujå" },
    { fr: "la marinade", no: "marinaden", phonetic: "la marinad" },
    { fr: "cru", no: "rå (mat)", phonetic: "kry" },
    { fr: "cuit", no: "tilberedt / kokt", phonetic: "kwi" },
    { fr: "bien cuit", no: "gjennomstekt", phonetic: "bjæn kwi" },
    { fr: "à point", no: "medium (kjøtt)", phonetic: "a pwoæn" },
    { fr: "saignant", no: "blodig / lite stekt", phonetic: "sænjå" },
    { fr: "croustillant", no: "sprø", phonetic: "krustijå" },
    { fr: "fondant", no: "smeltende / myk", phonetic: "fådå" },
    { fr: "le four à micro-ondes", no: "mikrobølgeovnen", phonetic: "lə fur a mikro åd" },
    { fr: "le réfrigérateur", no: "kjøleskapet", phonetic: "lə refrischæratør" },
    { fr: "le congélateur", no: "fryseren", phonetic: "lə kåsjælatør" },
    { fr: "la recette de famille", no: "familieoppskriften", phonetic: "la rəsæt də famij" },
    { fr: "le marché aux puces", no: "loppemarknedet", phonetic: "lə marsjæ o pys" },
    { fr: "la fromagerie", no: "ostebutikken", phonetic: "la fromasjəri" },
    { fr: "la charcuterie", no: "kjøttdelikatessen", phonetic: "la sjarkytəri" },
    { fr: "la pâtisserie", no: "konditoriet", phonetic: "la patisəri" },
    { fr: "le croissant", no: "croissanten", phonetic: "lə krwasså" },
    { fr: "le pain au chocolat", no: "pain au chocolat", phonetic: "lə pæn o sjokola" },
    { fr: "la brioche", no: "briosjen", phonetic: "la brijosjə" },
    { fr: "le macaron", no: "makaronen", phonetic: "lə makarå" },
    { fr: "l'éclair", no: "eclairén", phonetic: "leklær" },
    { fr: "la tarte tatin", no: "tarte tatin (epleomvendt kake)", phonetic: "la tart tatæn" },
    { fr: "la madeleine", no: "madeleinekaken", phonetic: "la madlæn" },
    { fr: "le nougat", no: "nougaten", phonetic: "lə nuga" },
    { fr: "les fruits de mer", no: "sjømat", phonetic: "læ frwi də mær" },
    { fr: "la fondue", no: "fonduen", phonetic: "la fådy" },
    { fr: "la raclette", no: "racletten (smeltet ostegrill)", phonetic: "la raklæt" },
    { fr: "le foie gras", no: "foie gras (gaasselever)", phonetic: "lə fwa gra" },
    { fr: "la truffe", no: "trøffelen", phonetic: "la tryf" },
    { fr: "la noix", no: "valnøtten", phonetic: "la nwa" },
    { fr: "l'amande", no: "mandelen", phonetic: "lamåd" },
    { fr: "la noisette", no: "hasselnøtten", phonetic: "la nwazæt" },
    { fr: "la pistache", no: "pistasjen", phonetic: "la pistasjə" },
    { fr: "la cannelle", no: "kanel", phonetic: "la kanæl" },
    { fr: "le gingembre", no: "ingefæren", phonetic: "lə sjænjåbrə" },
    { fr: "le cumin", no: "spiskummen", phonetic: "lə kymæn" },
    { fr: "le curry", no: "curryen", phonetic: "lə kyri" },
    { fr: "le paprika", no: "paprikapulveret", phonetic: "lə paprika" },
    { fr: "le basilic", no: "basilikumet", phonetic: "lə bazilik" },
    { fr: "le thym", no: "timian", phonetic: "lə tæn" },
    { fr: "le romarin", no: "rosmarin", phonetic: "lə romaræn" },
    { fr: "le persil", no: "persillen", phonetic: "lə pærsil" },
    { fr: "la ciboulette", no: "gressløken", phonetic: "la sibulæt" },
    { fr: "l'estragon", no: "estragon", phonetic: "læstragå" },
    { fr: "le laurier", no: "laurbærbladet", phonetic: "lə lorjæ" },
  ],
};
